lib/jira/client/axios.js
lib/jira/install.js

Closes https://github.com/github/ecosystem-integrations/issues/195

Verify installation

---

lib/jira/connect.js

This section is supposed to open in the iframe, but it's currently opening in a new tab. Removing this for now since the page is not designed to be rendered outside of the iframe.

Remove web section since it's not opening in an iframe

---

lib/jira/connect.js

I've removed the `ADMIN` scope from the requested JIRA permissions and added `DELETE`.
I'm trying to get this implemented in our organization and InfoSec is balking at the wide-ranging scope of permissions requested for JIRA. I took a look through the JIRA REST API calls being made and none of them are documented as needing `ADMIN` in order to function. Additionally it looks like some of the API calls requires a scope (`DELETE`) that isn't specifically requested, so I added that.
Below are the JIRA REST API calls from this integration, along with their API documentation link and required scope. Please let me know if I missed any of them, or whether there is an undocumented reason why the `ADMIN` permission is needed.
**Get issue**
Used: …

Reduces the scope of requested JIRA permissions to only those currently in use

---

SUPPORT.md

Create a SUPPORT.md file to take advantage of GitHub's built in ability to help direct people to the correct place to get support: https://help.github.com/articles/adding-support-resources-to-your-project/
The content is lifted straight from the README.

Create SUPPORT.md file

---

README.md
lib/jira/util/index.js
package-lock.json
package.json
test/fixtures/text/existing-reference-link.rendered.md
test/fixtures/text/existing-reference-link.source.md
test/fixtures/text/multiple-links.rendered.md
test/fixtures/text/multiple-links.source.md
test/fixtures/text/previously-referenced.rendered.md
test/fixtures/text/previously-referenced.source.md
test/fixtures/text/valid-and-invalid-issues.rendered.md
test/fixtures/text/valid-and-invalid-issues.source.md
test/safe/issue-comment.test.js
test/safe/issue.test.js
test/safe/pull-request.test.js
test/unit/jira/util.test.js

Approved from #165. Had to open a non-forked branch to deploy from chatops.

De-duping issue links w/ reference syntax (#165)

---

lib/configure-robot.js
lib/run.js
package.json

This allows New Relic to be instrumented properly.

Move startup into its own file

---

lib/api/index.js
test/unit/api/__snapshots__/api.test.js.snap
test/unit/api/api.test.js

Adds Staff API access for GitHub staff that have `ADMIN` access in addition to `WRITE`.
CC https://github.com/github/ecosystem-primitives/issues/251

Add access for Admins of github too

---

SUPPORT.md

This pull request updates the `SUPPORT.md` file with the new Apps wording in the breadcrumbs for finding the integration settings in Jira.

Update SUPPORT.md with new Apps wording

---

app.yml

For first-time contributors, following the [app manifest flow](https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/) would be helpful. Therefore, this PR introduces an `app.yml` file with the permissions and events needed.

Add `app.yml`

---

CONTRIBUTING.md
README.md

This PR adds the build badge for TravisCI to the `README` doc! 🚀

Add build badge for TravisCI

---

lib/github/middleware.js
lib/models/axios-error-event-decorator.js
lib/worker/index.js
test/unit/models/axios-error-event-decorator.test.js

This adds a [Sentry event processor] for Axios errors, which improves the errors in Sentry in three ways:
1. **Adding request metadata.** This includes method, path, headers, body and more.
2. **Adding response metadata.** This status, headers, body, and more.
3. **Fine-grained grouping.** In addition to stacktrace and other default criteria, errors are separated based on request method, path, and response code.
Events for non-Axios errors are ignored.
[Sentry event processor]: https://docs.sentry.io/platforms/node/#eventprocessors

Supercharge Axios errors

---

bin/clean-old-jobs

This script was exiting non-zero when everything was fine. This fixes that.

Exit 0 when successful

---

package-lock.json
package.json

Upgrading from [Bull 3.4.7](https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md#v347) to [Bull 3.12.1](https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md#v3121)
biggest changes to note are from [Bull 3.5.3](https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md#v353) where ioredis was upgraded from 3.x to [4.x](https://github.com/luin/ioredis/blob/master/Changelog.md). Which has numerous performance, security, and stability improvements

Upgrade Bull to major redis cli improvements

---

lib/models/subscription.js
lib/sync/discovery.js
lib/sync/installation.js
lib/worker/index.js
lib/worker/metrics-job.js

This is in an effort to aid https://github.com/github/integrations-jira-internal/issues/17 which is more metrics on Jira to help us diagnose issues early. And to see positive trends when we push improvements.
This implements:
- How long does a complete sync take (per repo, per org)? (mean, 95th, max)
- How long does each job type take?(histogram)
- How often does each job fail?
- Aging jobs. How many have stayed PENDING for more than 24 hours?

More statsd sync metrics

---

.github/workflows/build.yml
docs/database-migrations.md

Describe how migrations are done in jira's heroku world and update the Actions yaml to fix the Postgres issue.
re-deploy the last commit via chatops `.deploy jira-integration to production`

Add documentation about database-migrations

---

lib/github/branch.js
lib/github/issue-comment.js
lib/github/issue.js
lib/github/middleware.js
lib/github/pull-request.js
lib/github/push.js

We have customer reports that things are intermittently making it to Jira. This is meant to help raise visibilty into where these noops are happening and why.
This is still WIP as I'd like to make sure I can stress these scenarios with github.com first. I would also like to log out more details about each of the Bots we're nooping.

Add statsd and logs for explicit noops

---

lib/models/octokit-error.js
test/models/octokit-error.test.js

This reverts commit 7c8e5018cb3c37a1e2cc23595b33fdd49029a2db from #332
This doesn't seem to do what I was hoping for.

Revert "Sets originalException"

---

lib/models/subscription.js
lib/worker/metrics-job.js

We're going to move forward with Looker for now

Drops datadog collection for aged syncs

---

lib/worker/index.js
package-lock.json
package.json

We are limited in # of allowed connections in Heroku's Redis, let's use Bull's suggestion on how to limit connections:
https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections

Use Bull's suggestions on limiting number of connections

---

lib/configure-robot.js
lib/ping.js

Allows us to monitor if the service is online and responding

Add a _ping endpoint for pingdom to hit

---

lib/jira/disable.js
lib/jira/enable.js
lib/jira/install.js
lib/jira/uninstall.js
lib/models/installation.js
lib/proto/v0/action.js
lib/tracking/index.js
test/setup/app.js
test/setup/env.js
test/setup/tracking.js
test/unit/frontend/github-configuration.test.js
test/unit/frontend/verify-jira-middleware.test.js
test/unit/jira/__snapshots__/disable.test.js.snap
test/unit/jira/__snapshots__/enable.test.js.snap
test/unit/jira/__snapshots__/install.test.js.snap
test/unit/jira/__snapshots__/uninstall.test.js.snap
test/unit/jira/disable.test.js
test/unit/jira/enable.test.js
test/unit/jira/install.test.js
test/unit/jira/uninstall.test.js
test/unit/sync/branch.test.js
test/unit/sync/commits.test.js
test/unit/sync/pull-requests.test.js
test/unit/tracking.test.js

This builds off of https://github.com/integrations/jira/pull/399.
Add Hydro Events for:
*  disable
*  enable
*  install
*  uninstall
Additionally cleaning up some td pollution by calling td.reset(). We didn't have tests for any of the above events, so I've added rudimentary frameworks for each, we can add cases for future regressions or issues we encounter.

Emit hydro events

---

lib/frontend/delete-github-subscription.js
lib/frontend/delete-jira-configuration.js
lib/frontend/post-github-configuration.js
test/unit/frontend/__snapshots__/delete-github-subscription.test.js.snap
test/unit/frontend/__snapshots__/delete-jira-configuration.test.js.snap
test/unit/frontend/__snapshots__/github-configuration.test.js.snap
test/unit/frontend/delete-github-subscription.test.js
test/unit/frontend/delete-jira-configuration.test.js
test/unit/frontend/github-configuration.test.js

These are things users do like delete/add/edit subscriptions and installations.
Previous PR #400 with Webhook events, PR #399 set up the original framework.
This is the 3rd of 3 PRs to track create/disable/delete actions taken on subscriptions and installations.

Instrument actions taken via the Jira Console

---

.env.example
CONTRIBUTING.md
docker-compose.yml

This PR updates CONTRIBUTING.md - reorders steps for local setup, adds missing variables, removes broken links. It also adds a docker-compose file so developers are able to run 2 containers (postgres and redis) running a single command.

ARC-16: Update CONTRIBUTING.md

---

.github/CODEOWNERS

Adding team members as codeowners so we can review/merge our own PRs :)

Adding Atlassian team as codeowners

---

lib/frontend/app.js
static/css/jira-configuration.css
views/jira-configuration.hbs

ARC-157 fix styling bug

---

lib/sync/discovery.js

Fix to resolve this [error](https://softwareteams.atlassian.net/jira/software/projects/ARC/boards/385?assignee=604894ffe19f910069497c6a&selectedIssue=ARC-75) that's currently being logged to the console.

ARC-75 update paginate promise to use endpoint instead

---

lib/run.js

This PR adds some logging to the application startup so we can investigate startup failures better.

ARC-227: add logging to application startup

---

src/api/index.ts
test/unit/api/__snapshots__/api.test.ts.snap
test/unit/api/api.test.ts

Updating the graphql query for the authorization process for the `/api` endpoints.  Instead of being who's an admin of a specific repository, made it about who's an admin of the fusion-arc organization as it seems simpler.

Update admin permissions

---

src/jira/connect.ts

In this PR I've changed the app descriptor to add another item in the navigation bar, so GitHub App configuration will be easily accessible from the Apps configuration pages:

Arc 267 add a new navigation item to configure GitHub app

---

package-lock.json
package.json

Upgrade issue key parsing library which now ignores issue keys with a single char e.g. F-67

ARC-360 upgrade issue key parser

---

src/frontend/app.ts
src/frontend/get-github-configuration.ts
src/frontend/get-github-setup.ts
src/frontend/get-github-subscriptions.ts
src/frontend/get-jira-configuration.ts
src/frontend/index.ts
src/frontend/list-github-installations.ts
src/frontend/post-github-setup.ts
views/github-configuration.hbs
views/github-error.hbs
views/github-installations.hbs
views/github-setup.hbs
views/github-subscriptions.hbs
views/jira-configuration.hbs

Adjusted Content Security Policy in accordance with Atlassian Security Guidelines

ARC-293 Adjusted Content Security Policy in accordance with Atlassian Security Guidelines

---

github-for-jira.sd.yml

Moving from shared RDS to Dedicated RDS to allow to connect to it directly for the migration.

ARC-271 Adding dedicated RDS to service descriptor

---

db-migration.sh

Added DB Migration bash script to make the process repeatable.  Tested it with ddev to local migration and it works well.

ARC-271 DB Migration

---

CONTRIBUTING.md
docker-compose.yml
env.ts
src/frontend/github-oauth.ts

After some feedback from @rachellerathbone, I've made some improvements to the docker-compose file and `env.ts` prestart script so that ngrok isn't as tied to the app and we can use a different tunnel more easily by running `docker-compose up app` instead of just `docker-compose up`.  Updated the CONTRIBUTORS readme to reflect these changes.  Also added some better OAuth error handling to help us debug errors when it happens.

Development Improvements

---

db/migrations/20210518233338-create-appsecrets.js
db/migrations/20210714204884-create-registration.js
lib/frontend/app.js
lib/frontend/post-ghae-complete.js
lib/frontend/post-ghae-register.js
lib/models/appsecrets.js
lib/models/index.js
lib/models/registration.js
lib/util/parse-host-from-url.js
static/js/ghae-register.js
test/unit/models/appsecrets.test.js
test/unit/models/registration.test.js
views/ghae_register.hbs
views/ghae_register_complete.hbs

Pr for registering jira app on GHAE. 
There will be text field to enter ghae instance url 
After hitting register jira app, it will create jira app on ghae instance using manifest flow.
We will get callback to update app secrets in our database
closes https://github.com/github/marketplace/issues/2085

Registration automation for jira ghae

---

github-for-jira.sd.yml

update the env vars for staging to point against the staging app we took over from GitHub.

Update staging env

---

db-migration.sh

Fixing some stuff around Mac, because apparently Apple can't be bothered to update their bash versions.

DB Migration Fix

---

github-for-jira.sd.yml

Staging migration test change proxy url

Staging migration test change proxy url

---

github-for-jira.sd.yml

Add rewrite for staging proxy

---

db-migration.sh

Fixing issue with script failing trying to migrate an DB extension that we don't use on micros.

ARC-429 Fixing DB migration script

---

lib/frontend/get-maintenance.js
views/maintenance.hbs

Fixing maintenance mode to show in connect by including the connect SDK

ARC-385 fixing maintenance mode to show in connect

---

.github/workflows/test.yml

Currently only runs when doing a push to the repository and not on PR from external repository.

fixing test to run on PR 

---

src/frontend/app.ts
static/css/github-configuration.css
static/css/global.css
views/github-configuration.hbs

No org with Jira installed + hover view:
Org installed:
Previous view:

ARC-422 Update UI for connecting a new org to Jira

---

github-for-jira.sd.yml

Updated scaling rules.
Tested CPU and Network Delay in staging env, it works 👍

ARC-358 Changed scaling rules

---

github-for-jira.sd.yml

It is time to bump production node sizes hence we are going to do the migration soon

Bumped production nodes sizes

---

src/config/metric-names.ts
src/frontend/list-github-installations.ts

Small update to the logs for list-github-installations so we can easily track if the server ever renders that page.

ARC-447 update logs

---

github-for-jira.sd.yml

moving proxy to point to micros stack instead of heroku

---

src/github/branch.ts
src/transforms/branch.ts

Fixing issue where branch transform was wrapping in `data` property, but destructed object could fail because it might be `undefined`.

fixing issue with object destructuring when returning undefined

---

src/github/branch.ts
src/github/middleware.ts
src/github/pull-request.ts
src/github/push.ts
src/transforms/branch.ts

Needed to use more optional chaining to make sure things don't break.

ARC-483 fixing type error

---

src/github/branch.ts
src/github/deployment.ts
src/github/issue-comment.ts
src/github/issue.ts
src/github/middleware.ts
src/github/pull-request.ts
src/github/push.ts
src/github/workflow.ts
src/main.ts
test/unit/github/middleware.test.ts

Adding a bit more logging to the webhooks path so hopefully it will help us to get some insights

Added more logs for webhooks processing

---

src/github/pull-request.ts
src/transforms/branch.ts
src/transforms/pull-request.ts

Reducing APi impact of push and branch webhook where possible.

trying to fix push webhook by limiting calls to github API

---

src/jira/client/axios.ts

Need more data about what's failing when calling external API (jira).

adding response and resquest to axios failure logs

---

github-for-jira.sd.yml
src/github/issue-comment.ts
src/github/issue.ts
src/github/pull-request.ts
src/jira/client/index.ts
src/jira/util/index.ts

Adding try/catch to any calls to unfurl.  This should fix issue with 404 preventing PRs syncing correctly.

ARC-600 Fixing issue.getAll call to jira API

---

src/config/logger.ts
src/interfaces/jira.ts
src/jira/client/index.ts
src/sync/branches.ts
src/sync/commits.ts
src/sync/queries.ts
src/sync/transforms/branch.ts
src/sync/transforms/pull-request.ts
src/transforms/branch.ts
src/transforms/commit.ts
src/transforms/pull-request.ts
src/transforms/push.ts
src/util/jira.ts

Using the same function throughout and use common sense defaults so that no required fields are missing.

ARC-612 Standardizing all author fields

---

src/github/code-scanning-alert.ts
src/interfaces/jira.ts
src/jira/client/index.ts
src/jira/connect.ts
src/transforms/code-scanning-alert.ts
test/unit/jira/__snapshots__/connect.test.ts.snap
test/unit/jira/client/__snapshots__/index.test.ts.snap
test/unit/maintenance/__snapshots__/maintenance.test.ts.snap

Was there anything else I was meant to do?

ARC-616: Extend app descriptor to include remotelinks

---

github-for-jira.sd.yml

Got an alert about too little RDS storage

HOTFIX: increase storage of DB

---

package-lock.json
src/config/feature-flags.ts
src/github/push.ts

Feature flagging the prioritization of push events, because we're seeing weird metrics in Redis (set commands vs. sorted set commands).

add feature flag for prioritization of pushes

---

src/config/feature-flags.ts
src/config/metric-names.ts
src/worker/main.ts

Exposes some queue stats every 60 seconds.

expose queue metrics via statsd every 60 seconds

---

src/config/feature-flags.ts
src/github/push.ts
src/sync/installation.ts
src/transforms/push.ts
src/worker/main.ts
test/safe/push.test.ts

But only if it has less than 20 commits, which is the amount we call on the github API side

HOT-96682 Processing push commits immediately

---

src/config/github-api.ts
src/worker/main.ts

Also logging throttling events from octokit.

HOT-96682 Adding queue timeout with exponential backoff

---

src/api/index.ts
src/config/enhance-octokit.ts
src/config/github-api.ts
src/sync/installation.ts
src/transforms/push.ts
src/worker/main.ts

replacing https://github.com/atlassian/github-for-jira/pull/752

Remove bottleneck

---

app.yml
src/github/index.ts
src/github/repository.ts

https://developer.atlassian.com/cloud/jira/software/rest/api-group-development-information/#api-devinfo-0-10-repository-repositoryid-delete

ARC-658: Delete dev info data when repo is deleted from GitHub.

---

github-for-jira.sd.yml

https://instances.vantage.sh/rds/?compare_on=true&selected=db.m5.large,db.r5.xlarge

HOT-96682: bump RDS instance class

---

src/sync/installation.ts
test/mocks/errorResponses.ts
test/unit/sync/helpers/sync-helpers.test.ts

This PR is to account for one of the causes behind failed syncs. See the `HttpError: Not Found` not entry in [this doc](https://hello.atlassian.net/wiki/spaces/PF/pages/1341394025/Investigating+causes+for+sync+failures) for further information on the 2 not found error responses.

ARC-648 Not Found Sync Failures

---

src/frontend/github-oauth.ts
src/util/getUrl.ts
test/unit/util/getUrl.test.ts

This should help debugging cases like JST-691980 and PCS-54514

ARC-646 [small] [quick karma]: fix jira hostname log for /github/callback

---

src/config/metric-names.ts
src/sqs/index.ts
src/worker.ts
src/worker/queues.ts

Added metrics for the sqs listener

ARC-278 Added SQS queue metrics

---

src/config/feature-flags.ts
src/jira/client/index.ts
src/jira/util/index.ts
src/transforms/push.ts
test/safe/pull-request.test.ts

Reverting https://github.com/atlassian/github-for-jira/pull/878 and https://github.com/atlassian/github-for-jira/pull/866 to get back to stable processing.

Revert commits

---

src/util/webhooks.ts
src/worker.ts
src/worker/startup.ts
test/safe/push.test.ts
test/utils/waitUntil.ts

Added integration tests for commit webhooks.
- Fixed existing tests which were missing assertions
- Added new end to end test which test the push path from receiving the webhook to sending event to Jira

ARC-744 add commits integration test

---

src/config/feature-flags.ts

Just adding a comment to help FF cleanup.

FD-26652: add cleanup comment

---

src/config/feature-flags.ts
src/models/installation.ts

Flag removal for sorting installation entries by id.

ARC-771 remove sorting installation flag

---

src/config/feature-flags.ts
src/sync/installation.ts

Cleaning up a feature flag. Please view the diff with "ignore whitespace" enabled, because the formatter formatted some whitespaces.

FD-26660: clean up feature flag

---

src/worker/startup.ts

Please view the diff with "ignore whitespaces" because the formatter formatted some whitespaces properly.

FD-26653: clean up feature flag

---

src/github/middleware.ts
src/sqs/index.ts
test/safe/push.test.ts
test/unit/sqs/index.test.ts
test/utils/waitUntil.ts

Fixed end to end test for push webhooks processing, which was skipped in the recent "fix all tests" PR.

Fixed end to end test

---

src/config/feature-flags.ts
src/github/client/app-token-holder.ts
src/github/client/github-client.ts
src/github/client/installation-token-cache.ts
src/github/client/types.ts
src/services/github/user.ts
src/sync/branches.ts
src/sync/commits.ts
src/sync/installation.ts
src/sync/pull-request.ts
src/sync/transforms/pull-request.ts
test/github/client/app-token-holder.test.ts
test/github/client/github-client.test.ts
test/unit/sync/transforms/pull-request.test.ts

Starts using the Github Client for processing PR backfill.

Use new github client under a feature flag for PRs

---

github-for-jira.sd.yml

Switching to single ALB and increasing latency alert evaluation period

Switched to single ALB

---

src/sqs/index.ts
src/transforms/push.ts
test/unit/sqs/index.test.ts

* Added `lastAttempt` parameter to the queue execution context
* Fixed receiveCount calcluation
* Added a test

ARC-788 Fix approximate receive counter

---

src/config/metric-names.ts
src/github/middleware.ts
src/util/webhooks.ts
test/unit/util/webhooks.test.ts

Reverts atlassian/github-for-jira#894
Reverting the latest change due to the latencies incident

Revert "Add webhook payload metric"

---

src/config/feature-flags.ts
src/config/tracer.ts
src/frontend/get-github-configuration.ts
src/frontend/github-oauth.ts

This PR adds some trace logs to investigate the 504 issues some users report when using SSO. I put the trace logs behind a feature flag so we can activate it during a Zoom session with a user and be sure that the logs come from that user.
The quality of the logs in general is still pretty bad, though, and this PR doesn't really change that :(.

ARC-829: add tracing 

---

views/error.hbs

Readding mistakenly deleted primer build.css line back into error page

---

src/api/index.ts
src/frontend/get-github-setup.ts
src/frontend/post-github-setup.ts
src/util/get-url.ts
src/util/getUrl.ts
test/unit/api/api.test.ts
test/unit/util/get-url.test.ts
test/unit/util/webhooks.test.ts

Bad URL being returned by function, adding additional https at the front.

Fixing up URL for github configuration url

---

github-for-jira.sd.yml

Added an alert for Redis connections

ARC-890 Added Redis Alert

---

github-for-jira.sd.yml

Restoring Global Edge for ddev,
Removed 5xx alerts from prod

ARC-896 restored globaledge for ddev, removed 5xx alert from prod

---

src/sqs/index.ts
src/sync/branches.ts
src/sync/commits.ts
src/sync/installation.ts
src/sync/pull-request.ts

Sometimes a sync message gets stuck and blocks the current installation from being sync till the next deployment. Here I"m trying to figure out what's going on by adding more logs.
Ignore whitespaces when reviewing: there was an indentation change
Sample splunk: 
```
`micros_github-for-jira` env=prod-west "61f91b43-f867-4360-b9da-956f53b59137"
```

[EASY KARMA] Issue/NONE propagate logger from process installation

---

src/config/feature-flags.ts
src/github/client/github-client.ts
src/sqs/push.ts
src/transforms/push.ts
test/safe/branch.test.ts
test/safe/push.test.ts

Reverting the PR because it made main branch flaky

Revert "Removed use-new-github-client-for-push feature flag, removed `bull` dependency from push processor"

---

src/config/feature-flags.ts
src/frontend/get-github-configuration.ts

To debug https://github.com/atlassian/github-for-jira/issues/1012

DISTURBED: add verbose logging for get-github-configuration

---

src/config/feature-flags.ts
src/github/client/github-client.ts
src/sqs/push.ts
src/transforms/push.ts
test/safe/branch.test.ts
test/safe/push.test.ts

Second attempt to merge this PR.
This one will include fix for the flaky test.
In progress currently

Removed use-new-github-client-for-push feature flag, removed `bull` dependency from push processor""

---

src/config/feature-flags.ts
src/github/workflow.ts
src/transforms/workflow.ts

Removal of SUPPORT_BRANCH_AND_MERGE_WORKFLOWS_FOR_BUILDS. Wasn't expecting any issues with the removal but did a sanity check to make sure everything still looks good on the builds dev panel front. Made multiple commits on a branch and all builds are showing up as expected.

Remove builds FF

---

src/sqs/backfill.ts

Added InstallationID and JiraHost to the context logger of the backfill job

Added installation and jiraHost to backfill logs

---

static/css/jira-configuration.css
views/jira-configuration.hbs

Tech debt from... someone... :coneofshame:
All styling remains the same.

ARC-796 remove !important from config css

---

static/css/github-setup.css

Last but not least. We really should sack this person who put all these here...
All looks good.

ARC-796 remove important from setup page

---

src/frontend/healthcheck.ts

Changed logging type for /healthcheck from info to debug to reduce log noise.

changed healthcheck log from info to debug

---

src/frontend/app.ts
src/util/handlebars/partials.ts

Make HBS files self discoverable when adding them to partials folder.  This is getting split up from https://github.com/atlassian/github-for-jira/pull/1057

Improving partials use and discovery

---

src/github/deployment.ts

Added blocklist for the deployment queue

Added blocklist for the deployment queue

---

package-lock.json
src/frontend/app.ts
src/frontend/get-github-setup.ts
src/frontend/post-github-configuration.ts
src/github/client/github-client.ts
static/css/github-configuration.css
static/css/github-setup.css
static/css/global.css
static/js/github-setup.js
static/js/jira-configuration.js
test/unit/frontend/github-setup.test.ts
views/github-setup.hbs
views/partials/githubSetupForm.hbs

**Current flow for Jira install** - in case you need a refresher (prod): https://www.loom.com/share/3d7a4caba70f4a32a7268b0ce372f4da
**Updated flow for Jira install** when user wants to install the app in a new org and uses the Jira host stored in a cookie: https://www.loom.com/share/f9fd0820ff91404c8521fea22b242eea
**Jira install flow but user wants to enter a different Jira site:** https://www.loom.com/share/59a2bd11a9e448be8fa2409da835f491
**GH install flow** - we have no data in the cookie: https://www.loom.com/share/e786f65b6b6b49068ed9a34dbea3c554

ARC-946 fix janky flow

---

github-for-jira.sd.yml

Autoscaling based on branch and deployment queue messages

ARC-1092 Autoscaling for branch and deployment queues

---

src/transforms/util/pullRequestLinkGenerator.ts
test/unit/transforms/pull-request.test.ts

Remove encoding on the base url for pr url generator, and update tests

ARC-778 - fix to remove encoding on base url

---

src/middleware/jirahost-middleware.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/github/github-router.ts
src/routes/github/setup/github-setup-get.ts
test/unit/frontend/github-configuration.test.ts
test/unit/frontend/github-setup.test.ts

Found other eventual consistency issues in github API for large enterprise clients.  Trying to mitigate them again.

[JST-736037] changing the github setup connect page for large enterprise

---

src/config/feature-flags.ts
src/github/client/github-client.ts
src/github/index.ts
src/github/middleware.ts
src/github/workflow.ts
src/jira/client/index.ts
src/transforms/deployment.ts
src/transforms/util/githubApiRequests.ts
src/transforms/workflow.ts
test/safe/workflow.test.ts
test/unit/transforms/deployments.test.ts
test/unit/transforms/util/githubApiRequests.test.ts

Using new github client instead.

ARC-1176 remove octokit workflow webhook

---

src/sync/installation.ts
test/unit/sync/installation.test.ts

In this PR I've done the following:
1. Refactored Backfill error handling code to make it testable
2. Added tests
3. Fixed a situation when we have 404 error and treat it like Rate Limiting (See ticket description for details)

Arc 1182 fix error handling for backfill

---

src/config/feature-flags.ts
src/github/client/errors.ts
src/github/client/github-app-client.ts
src/github/client/github-queries.ts
src/sync/branches.ts
src/sync/commits.ts
src/sync/installation.ts
test/unit/sync/branch.test.ts

Trying to fix sync for getBranch call for large enterprise customer.  Adding better logging to see what's going on.

JST-736037 trying to fix issue with getBranch sync graphql

---

package-lock.json
src/github/branch.test.ts
src/github/pull-request.test.ts
src/sync/branch.test.ts
src/sync/branches.ts
src/sync/transforms/branch.ts
src/transforms/branch.ts
src/transforms/pull-request.ts

Remove the feature flag use-new-github-pull-request-url-format

ARC-778 remove Feature flag for pr requests

---

github-for-jira.sd.yml
package-lock.json
src/routes/api/api-router.test.ts
src/routes/api/api-router.ts
src/routes/maintenance/maintenance-router.test.ts
test/snapshots/routes/api/api-router.test.ts.snap

Follow up on the previous PR.
Added a verification that SLAuth headers are set
Currently testing in staging

Arc 1282 add slauth headers verification

---

src/github/client/github-client-errors.ts
src/github/client/github-installation-client.ts

Testing out a potential solution for PCS-88578.  We might not be catching an error correctly because the graphql api is problematic.

ARC-1294 adding change to make any graphql error retry without 'changedFiles'

---

src/config/feature-flags.ts
src/routes/github/subscription/github-subscription-delete.ts
src/routes/jira/configuration/jira-configuration-get.test.ts
src/routes/jira/configuration/jira-configuration-get.ts

use github client for get installations call on jira-configuration-get
Updated tests to use gh client and octokit.

ARC-1286 gh client jira config get

---

src/config/feature-flags.ts
src/github/client/github-app-client.ts
src/routes/github/setup/github-setup-get.ts
src/routes/github/setup/github-setup-router.test.ts

Updated github detup get to use new github client instead of Octokit

Arc-1285 ghclient GitHub setup get

---

src/config/feature-flags.ts
src/github/client/github-user-client.ts
src/routes/github/configuration/github-configuration-get.ts
src/routes/github/configuration/github-configuration-router.test.ts
src/routes/github/setup/github-setup-router.test.ts

Replace Octokit for github configuration
Created new user endpoint to fetch all installations

Arc 1212 gh client get GitHub config

---

Dockerfile
Dockerfile.prod

Updated the base image from 14.8-alpine3.15 to 14.9-alpine3.15
Running SNYK locally before the change I was able to detect 5 vulnerabilities ( 1 critical, 3 high, 0 medium, 1 low)
After updating to 14.9 There are 0 vulnerabilities found.

Vuln - updated base image to 14.9-alpine3.15

---

.env.test
docker-compose.yml

Something updated in docker images and broke the build, hard setting it to previous version seems to fix it.

Fixing builds by setting docker image to past version

---

src/jira/client/axios.ts

ARC-1239: Get the right status from AxiosError

---

src/routes/github/setup/github-setup-post.ts
src/util/validations.ts
static/css/github-setup.css
static/js/github-setup.js
views/github-setup.hbs

A user found an edge case: https://github.com/atlassian/github-for-jira/issues/1195
This is to fix this edge case and also some padding.

Fix github setup

---

src/config/logger.ts
src/github/client/github-client-errors.ts
src/github/client/github-client-interceptors.ts
src/github/pull-request.ts
src/jira/client/jira-client.ts
src/sync/installation.ts

One of our customers is seeing a lot of failed requests with the pull task for some reason.  I've added better logging of the pull task and looking at a potential issue with reviews not coming back because of permissions.

fixing a few issues and logs to troubleshoot large customer

---

src/sync/deployment.ts

Checking for undefined values before adding them to object

ARC-1072 - Fixing syncing issues 

---

static/css/jira-configuration.css
views/jira-configuration.hbs

I've made org list scrollable to view large number of connected orgs.

ARC-1419 Make connected org list scrollable

---

README.md

**Whats in this PR**
Updated the link on the Readme to the faq docs.

updated faq link

---

src/middleware/github-server-app-middleware.test.ts
src/middleware/github-server-app-middleware.ts
src/routes/github/configuration/github-configuration-router.ts

Breaking https://github.com/atlassian/github-for-jira/pull/1277 into some smaller PRs. This one starts with the addition of the new middleware.

Arc-1408 model updates part 1

---

src/routes/github/configuration/github-configuration-get.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/github/subscription/github-subscription-delete.ts
src/routes/github/subscription/github-subscription-get.ts
src/util/get-github-client-config.ts

Updated createUserClient to call `getGitHubClientConfigFromAppId`

Arc-1408 part 3

---

src/routes/github/github-oauth-router.ts
src/util/get-github-client-config.ts

Updated `getGitHubApiUrl` and `getGitHubHostname` to use `getGitHubClientConfigFromAppId`

Arc-1408 part 4

---

deploy/lambda/auto-deployment.js
github-for-jira.sd.yml

**Rationale**
- This PR includes the automation of deploying to different environments after merging to main.
**Changes**
- A new lambda function was created which checks if the commit of the main branch is same to the commit of deployed version or not.
- If not, then it sends a request to run the pipelines in [Bitbucket](https://bitbucket.org/atlassian/github-for-jira-deployment)
**Whats remaining**
- The URL for running the pipelines still needs to be updated.
- The environment variables in Microscope needs to be confirmed and finalized.

Dev loop CI/CD

---

github-for-jira.sd.yml

**Changes**
The missing label for the lambda resource was added in the service descriptor

Dev Loop CI/CD Fixes - Missing label added

---

src/models/github-server-app.ts

Trying to shrink the size of #1312 so pulling the new method on the GH Server Apps model out into a separate PR.

ARC-1455 pull new method out into separate pr

---

src/routes/jira/jira-router.ts
src/routes/jira/server/jira-select-version-router.ts
src/routes/jira/server/jira-server-url-router.ts

Another small PR to shrink #1312. Needed to move a couple of files (put them in the wrong dir accidentally before).

ARC-1455 move files from events to server (correct location)

---

deploy/lambda/auto-deployment.js

Code Refacored to fix variable undefined issue
**Why**
Fix variable undefined issue
NA
NA
This is running only in Prod. By looking into lamda invocations timestamp and logs.
NA

Arc 1462 fix auto deployment issue

---

static/css/jira-server-url.css
static/js/jira-manual-app-creation.js
static/js/jira-server-url.js
views/jira-manual-app-creation.hbs
views/jira-server-url.hbs

- Updated the form elements in Jira Server URL screen
- Replaced own custom jQuery logic for form validation by AUI form and AUI form validation
- Used AUI form submit on Jira Manual App creation .
**How was this tested**
- Tested in Staging
**Why**
- For consistency in form handling.
- For better accessibility.

ARC-1482 - Use AUI Form validation in Jira Server URL and Jira Manual App creation 

---

src/routes/jira/server/jira-server-url-get.ts
views/jira-manual-app-creation.hbs

- Changed some texts
- Changed the position of some input fields in the manual app form

ARC-1508 - GHE UI: Update manual form page

---

src/config/feature-flags.ts
src/transforms/transform-code-scanning-alert.test.ts
src/transforms/transform-code-scanning-alert.ts

Removing ff use-new-github-client-for-pr-title
Soaking in stage

remove ff use-new-github-client-for-pr-title

---

views/jira-configuration-new.hbs
views/partials/jira-configuration-empty-connections.hbs

Fix for rename of version -> product
**Why**
Looks like these 2 got missed in between @krazziekay's updates to the config page and my changes to wording used.

Fix naming

---

package.json
yarn.lock

1. Remove unneeded hbs watching for local devloop
2. Upgrade ts-node-dev for local dev
**Why**
1. It is causing EMFILE Too many file open on mac.
N/A
N/A
With K on local machine.
N/A

Fix on local devloop for EMFILE too many open.

---

src/routes/jira/server/jira-server-url-post.ts

Fixing stuffs :badpokerface: Forgot to define in the catch block.

fix jiraHost

---

src/util/get-cloud-or-server.ts

Bugfix - we were setting the GH product incorrectly.
Locally

remove protocol from getCloudOrServerFromHost check

---

Dockerfile.prod

Added yarn list to the prod dockerfile so we can see if the analytics package is being installed.

add yarn list to dockerfile

---

src/interfaces/common.ts

Fix analytics

---

src/util/analytics-client.ts

Attempting to fix analytics yet again. Starting to feel like I'm chasing down some mythical creature.

update path to optional require... was working... now maybe isn't???

---

views/jira-configuration.hbs

Modal element was missing from the current jira-configuration hbs and only on the -new one.
Have added it to the current one to please pollinator!

added the modal to the old config route

---

src/routes/healthcheck/deep-check-cryptor.ts
src/routes/healthcheck/deepcheck-get.ts
src/routes/healthcheck/healthcheck-get.ts
src/routes/healthcheck/healthcheck-router.test.ts

1. Add an encrypt/decrypt check for Worker group in healthcheck. 
2. Add encrypt/decrypt check for WebServer in deepcheck.
**Why**
It is complicated, please refer to the ticket ARC-1571 itself to see a more detail doc page.
N/A
https://softwareteams.atlassian.net/browse/ARC-1571
Stage (WIP)
N/A

ARC-1571: Add encrypt and decrypt on cryptor check

---

src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts

Update error mapping when trying to make a request to a GHE server.
**Why**
Because we found a new error that we haven't yet accounted for.
Al behind GHE_SERVER
None, just following up on a slack thread.
Locally.
Nap time? I'm tiiiiiiiired.

update error mapping

---

docs/ip-allowlist.md

Updated the docs around the IP allowlist to make them more succinct and to narrow down the list of IP addresses.
Preview for better readability: https://github.com/atlassian/github-for-jira/blob/update-allowlist-docs/docs/ip-allowlist.md

Update IP allowlist docs

---

src/routes/github/manifest/github-manifest-get.test.ts
src/routes/github/manifest/github-manifest-get.ts

Added a callback url to the manifest.
**Why**
So we can redirect back to the app from the auto app flow. 
n/a
in progress
Testing the flow.

add callback url

---

src/github/branch.ts
src/github/deployment.ts
src/github/pull-request.ts
src/jira/client/jira-client.ts
src/middleware/github-webhook-middleware.ts
src/routes/jira/jira-delete.ts
src/sqs/branch.ts
src/sqs/deployment.ts
src/sync/installation.ts
src/transforms/push.ts

Reverted some changes to jira client endpoints and passing gitHubAppId to getJiraClient.
**Why**
So we don't have to modify individual calls to endpoints.
ARC-1561
Locally and in staging.
n/a

Arc 1561 more updates jira client

---

static/js/github-configuration.js
views/github-subscriptions.hbs

A bugfix for deleting a subscription.
**Why**
Coz it's broken in prod 😬 
n/a
n/a
Locally
https://user-images.githubusercontent.com/37155488/185306793-6f359047-ec3b-4f4d-aeb9-587647616b65.mov
Tech debt issue: arc 1614 to add error message to the GH subscriptions page. Right now when a request fails the user gets no feedback.

remove jirahost to unbreak stuffs :smile:

---

src/models/subscription.test.ts
src/models/subscription.ts

Add `gitHubAppId` to the `where` clause in the `Subscripton.install()`
**Why**
Current value is not unique enough.
N/A
ARC-1480
Unit test.
N/A

Add gitHubAppId to subscription intallation

---

src/models/github-server-app.test.ts
src/models/github-server-app.ts

Add base url to gitHubServer
**Why**
current clientKey may not be enough.
N/A
ARC-1480
Unit test
N/A

ARC-1480 add base url to githubserverapp

---

src/routes/jira/connect/enterprise/server_app/jira-connect-enterprise-server-app-get.ts
static/css/jira-configuration-new.css
static/css/jira-select-app-creation.css
static/js/jira-select-card-option.js
views/jira-configuration-new.hbs
views/jira-select-app-creation.hbs
views/partials/jira-configuration-empty-connections.hbs
views/partials/jira-configuration-table.hbs
views/partials/select-app-creation-card.hbs

- Small CSS and text changes, listed [HERE](https://hello.atlassian.net/wiki/spaces/PF/pages/1781209083/GHE+prod+-+Nits+and+frogs)
**Why**
- To remove Nits and frogs
- Locally in Safari, Firefox and Chrome

ARC-1615 - Nits and frogs

---

src/middleware/github-webhook-middleware.ts

Passing gitHubProduct to another webhook metric.
**Why**
Because I missed it.

ARC-1543 missed one

---

static/js/jira-select-card-option.js
views/jira-select-app-creation.hbs

In Github App selection page
- Change version 2.19.18 to 3.1.x
- Hide messaging at bottom of screen when manual is selected (see screenshot)
**Why**
- UI tweaks
- Locally
**Video**
https://user-images.githubusercontent.com/13076255/186061809-1925b96d-3cde-469b-82f1-77ee42bd2f85.mov

ARC-1631 - Nits: app creation page

---

src/routes/jira/connect/enterprise/jira-connect-enterprise-post.test.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts
src/util/is-valid-url.test.ts
src/util/is-valid-url.ts
static/js/jira-server-url.js
views/jira-manual-app-creation.hbs
views/jira-server-url.hbs

- Time out added for `JiraConnectEnterprisePost`
- Error code passed for default error messages.
- Button click spamming blocked.
- Error validation check done on `keyUp` event
- Question icon removed from manual-app-creation page.
**Why**
- Test fixes 
- Local environment

ARC 1640 - Server URL screen updates

---

src/routes/api/installation/api-installation-delete.test.ts
src/routes/api/installation/api-installation-delete.ts
src/routes/api/installation/api-installation-get.test.ts
src/routes/api/installation/api-installation-get.ts
src/routes/api/installation/api-installation-router.test.ts
src/routes/api/installation/api-installation-router.ts
src/routes/api/installation/api-installation-sync-post.test.ts
src/routes/api/installation/api-installation-sync-post.ts
src/routes/api/installation/api-installation-syncstate-get.test.ts
src/routes/api/installation/api-installation-syncstate-get.ts

Add gitHubAppId to the route and each handler.
**Why**
Just installationId is not enough.
N/A
ARC-1622
Unit test.
N/A

Arc 1622 api installtion

---

views/partials/navigation.hbs

A link fix.
**Why**
Coz I'm stupid.
Peace out.

wtf rachelle?

---

static/js/github-create-branch.js

Close functionality for close button on create branch page.
ARC-1610

ARC-1610 close on cancel

---

src/github/client/github-client-cloud.test.ts
src/github/client/github-client.test.ts
src/transforms/transform-deployment.test.ts
src/util/github-utils.test.ts
test/setup/setup.ts

Moving GITHUB_CLOUD_CONFIG to test/setup
**Why**
To remove duplication of code
N/a (tests)
ARC-1643
yarn test
Removing FF

[INSTANT KARMA] ARC-1643: gitHubCloudConfig in test/setup

---

.env.development.local-example

Added just a few commented config lines for convenient testing with outbound proxy
**Why**
Because currently there's no instruction how to test with outbound proxy 
N/A
N/A
Locally

ARC-1643: [2-line PR] add ability to use outbound proxy for local testing

---

src/config/logger.ts

Removing UGC from error, request and response serializers
**Why**
Because logging UGC is bad, m'kay?
:cowboy:
NONE
locally
Look for more UGC

NONE: remove UGC from logs

---

src/github/deployment.ts
src/jira/client/jira-client.ts

Killing more UGC
**Why**
:killitwithfire:

NONE: more UGC to kill

---

src/config/logger.test.ts
src/config/logger.ts

NONE: sanitise branch name from URL

---

src/middleware/github-webhook-middleware.ts
src/routes/error-router.ts
src/sync/installation.ts
src/sync/pull-request.ts

*What's in this PR?  *
Removing prefixed " " from tags
*Why *
Because it is not trimmed :facepalm:

 [ :facepalm: ] [ Free karma, instant release ] NONE: fix metrics

---

src/transforms/transform-branch.ts

Debug logging
**Why**
Because our branches webhooks are broken
With an existing FF

NONE: add debug logging

---

src/transforms/transform-branch.ts

Removing retry logic
**Why**
In case of 404 the retries will take up to 30 seconds.. Current queue size is 200K and we are at 15 nodes; we must process faster. 
Also, we have SQS retrying, therefore this is kinda not necessary: if it is not in API, SQS will be retried later
Revering to the state when it was working alright

NONE: revert retry logic for branches

---

src/routes/github/create-branch/github-create-branch-get.ts
src/routes/github/create-branch/github-create-branch-post.ts
src/routes/github/manifest/github-manifest-get.test.ts
src/routes/github/manifest/github-manifest-get.ts
static/js/github-create-branch.js
views/github-create-branch.hbs

Updated backed APIs to support GHE server.
[ARC-1722]
Local
https://user-images.githubusercontent.com/14277763/194009266-e67e7c1b-9d1e-4a22-9593-4273017b0032.mov
[ARC-1722]: https://softwareteams.atlassian.net/browse/ARC-1722

ARC-1722 Backend support to create branch on GHE server

---

src/sync/deployment.test.ts
test/utils/database-state-creator.ts

Simplifying test.
**Why**
Because it is cool.

NONE: simplify a test

---

src/sync/branch.test.ts
src/sync/commits.test.ts
src/sync/deployment.test.ts
src/sync/pull-requests.test.ts
src/transforms/util/github-api-requests.test.ts
src/transforms/util/github-api-requests.ts

Improving test coverage a bit:
- for deployments a test was missing
- some more tests were not turning on the FF
Please review with whitespaces turned OFF
**Why**
Because tests are good

[EASY KARMA] ARC-1661: improve test coverage

---

static/js/github-create-branch-options.js
static/js/github-create-branch.js

- Removed the caching of the searched repositories.
- Loading for GitHub Enterprise updated
**Why**
- Not supposed to be this way ¯\_(ツ)_/¯ 
- Local

ARC-1753 - Closing then re-opening repo search after a search contains inital list plus additional searched results

---

src/routes/github/create-branch/github-create-branch-get.ts
static/css/github-create-branch.css
static/css/global.css
views/github-create-branch.hbs

Since we have the jirahost we can go back to the original design of the issue key being a link to the issue
**Why**
another to check its where you want to create the branch for
Tested on stage

ARC-1741 open link in new tab

---

static/js/github-create-branch.js
views/github-create-branch.hbs

- Removed the cancel button
**Why**
- Doesn't work in iframes
- Local

ARC-1757 - Cancel button does not work when on Iframe version

---

src/routes/jira/atlassian-connect/jira-atlassian-connect-get.ts

Debug isn't written to splunk for prod!

log out more details

---

src/routes/jira/atlassian-connect/jira-atlassian-connect-get.ts
src/routes/jira/atlassian-connect/jira-atlassian-connect.test.ts

Undo the ff changes on the atlassian-connect json because the behaviour is not as expected in production :(

revert ff changes on atlassian-connect

---

src/routes/github/manifest/github-manifest-complete-get.test.ts
src/routes/github/subscription/github-subscription-delete.test.ts
src/routes/github/subscription/github-subscription-get.test.ts
src/util/get-github-client-config.ts

More logs
**Why**
Cause it is unclear why the calls might be failing to internal GHE

NONE: add logs about the usage of outbound proxy

---

src/middleware/github-webhook-middleware.ts
src/routes/github/webhook/webhook-receiver-post.ts

Improving  webhook receive logs a little bit.
**Why**
One Beta customer is complaining that webhooks are not coming through. We should be able to easily troubleshoot such things.
Nah

EZY KARMA NONE: more logs to webhook receiver

---

src/github/client/key-locator.ts
src/middleware/github-server-app-middleware.test.ts
src/middleware/github-server-app-middleware.ts
src/models/github-server-app.test.ts
src/models/github-server-app.ts
src/routes/github/webhook/webhook-receiver-post.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.test.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.ts
src/util/get-github-client-config.ts
static/js/jira-manual-app-creation.js
views/jira-manual-app-creation.hbs

Fixing manual creation page
**Why**
Because it is broken; to unblock our customer
GHE

NONE: manual creation page fixes

---

src/routes/github/webhook/webhook-receiver-post.ts
src/routes/router.ts

We use json.stringify() before calculating the signature, and looks like we are rejecting at least some of the webhooks. I want to check if that's true and should we compare rawBody instead.

[NONE] [EASY KARMA]: extract raw body and add debug logs

---

src/routes/github/create-branch/github-create-branch-get.ts
src/routes/github/create-branch/github-create-branch-options-get.ts
src/routes/jira/jira-get.ts

Small addition to the GH config page analytics.
**Why**
Planning to use this true/false value so we can break our analytics charts out into empty/non-empty page views.
ARC-1795
Update the charts, of coure

ARC-1795 small addition to analytics

---

src/routes/github/create-branch/github-create-branch-get.ts
src/routes/github/create-branch/github-create-branch-options-get.ts
static/css/github-create-branch.css
static/js/github-create-branch-options.js
static/js/github-create-branch.js
views/github-create-branch.hbs
views/partials/select-github-product-card.hbs

Fixed the link when going from optinos page to cloud/server
merged in the change instance branch to this PR as well.
**Why**
So it doesn't pass uuid to cloud option

Cb server token

---

src/routes/api/client-key/client-key-regex.test.ts
src/routes/api/client-key/client-key-regex.ts
src/routes/api/client-key/recover-client-key.ts

1. Fix regex bug to support `jira:xxx`
2. Add orderBy when selecting installations to migrate.

fix some bugs on regex

---

src/routes/api/client-key/recover-client-key.ts

Make it parallel and faster coz we have a lot of installations.
tested on stage.

add parallel support

---

github-for-jira.sd.yml

doubled the allowed time before alarming on backfill - it has been ov…erly sensitive - so this will give it more of a chance to resolve itself

Backfill alarm easing

---

.github/workflows/on-push.yml
.gitignore
jest.config.js

Enabling jest unit test coverage
**Why**
Because we don't have it, so we don't know what's our coverage

Adding unit test coverage report

---

src/routes/api/installation/api-installation-delete.test.ts
src/routes/api/installation/api-installation-delete.ts

Fix one api bug
**Why**
Pollinator GHE test will need it.
ARC-936
Unit test.
N/A

ARC-936 fix api installation bug

---

src/routes/api/installation/api-installation-delete.test.ts
src/routes/api/installation/api-installation-delete.ts

Reverts atlassian/github-for-jira#1770

Revert "ARC-936 fix api installation bug"

---

etc/poco/bundle/extras-prod-test.json
etc/poco/bundle/extras-prod.json
etc/poco/bundle/extras-stg-test.json
etc/poco/bundle/extras-stg.json

Update poco policy to support GHE test (Basic)
ARC-936

Arc 936 update poco for ghe pollinator

---

etc/poco/bundle/extras-prod-test.json
etc/poco/bundle/extras-prod.json
etc/poco/bundle/extras-stg-test.json
etc/poco/bundle/extras-stg.json

Add pollinator tests ids to current poco policy
**Why**
Allow new GHE tests.
ARC-936

Add policy for pollinator ghe test

---

src/interfaces/common.ts
src/routes/github/create-branch/github-create-branch-post.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts

Pass a source value for the TRACK event for analytics
**Why**
Analytics event is dismissed without this value!

ARC-1855 - pass source for track analytucs event

---

src/interfaces/common.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-delete.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-delete.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-get.ts
src/routes/jira/connect/enterprise/server_app/jira-connect-enterprise-server-app-get.ts
src/routes/jira/jira-delete.ts
src/routes/jira/sync/jira-sync-post.ts

Add couple analytics for GHE (and some normal flow as well)
**Why**
Need to have a proper amplitude dashboard for those events.
N/A
ARC-1857
N/A
N/A

ARC-1857 add analytics for GHE

---

src/interfaces/common.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-delete.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-delete.ts
src/routes/jira/jira-delete.ts
src/routes/jira/sync/jira-sync-post.ts
src/util/analytics-client.ts

Add missing source for the trackEvent.
**Why**
Otherwise it will error in prod env saying `Cannot sendAnalytics event: Error: Value trackEvent.source cannot be undefined`
N/A
ARC-1857
N/A
N/A

Add missing track event source and type it properly

---

src/interfaces/common.ts
src/routes/github/manifest/github-manifest-complete-get.ts

Add auto app creation event
**Why**
Need to track auto app creation
N/A
ARC-936

Setup analytics events

---

src/middleware/jira-symmetric-jwt-middleware.ts

Updating new JWT validation middleware to look for JWT token in request body besides query and cookies
NEW_JWT_VALIDATION

New JWT middleware - Read Jwt from request body

---

src/routes/github/create-branch/github-create-branch-post.ts
static/js/github-create-branch.js

Adding url encoding where appropriate for create-branch feature 
**Why**
To fix issue with branch names that includes `/` in their name
None
https://github.com/atlassian/github-for-jira/issues/1798
manual, unit tests to be added later
@joshkay10 to add unit tests

fixing branchname url encoding and a few extra things

---

src/routes/github/create-branch/github-create-branch-get.ts
src/routes/github/repository/github-repository-get.ts

Improving log messages, adding an error obj, and checking for jiraHost
**Why**
Trying to debug a DoS issue.
PCS-145694

updating logging messaging for clarity;

---

src/routes/github/create-branch/github-create-branch-get.ts
src/routes/github/repository/github-repository-get.ts

Pcs 145694 cant see repos

---

src/github/client/github-client-interceptors.ts
src/sync/discovery.ts
src/sync/installation.ts

Remove logs that were there for temp tests
**Why**
Because they are no longer needed

drop temp loggings

---

src/routes/github/configuration/github-configuration-post.ts

Fix an incorrect logic in analytics
**Why**
_Jira Issues_

analytics fix

---

github-for-jira.sd.yml

Updated the description for DLQ alerts
**Why**
To add a runbook because we didn't have one 😑 
ARC-1898

ARC-1898 add runbook to DLQ alerts

---

src/config/feature-flags.ts
src/github/client/github-client-server.test.ts
src/github/pull-request.test.ts
src/github/repository.test.ts
src/routes/api/installation/api-installation-router.test.ts
src/routes/github/create-branch/github-create-branch-options-get.test.ts
src/routes/github/github-oauth-router.test.ts
src/routes/github/github-router.test.ts
src/routes/jira/jira-get.test.ts
src/routes/jira/jira-get.ts
src/sqs/push.test.ts
src/sync/branch.test.ts
src/sync/commits.test.ts
src/sync/deployment.test.ts
src/sync/pull-requests.test.ts
src/transforms/transform-code-scanning-alert.test.ts
src/transforms/transform-deployment.test.ts
src/util/get-github-client-config.ts

Remove GHE_SERVER ff
**Why**
It is already GA and 100% rolled out 
N/A
ARC-981
Unit test
N/A

ARC-981 Remove GHE FF

---

src/routes/github/repository/github-repository-get.ts

We have a few instances of people getting 401s on the search branch for create branch, this will help determine if its one more than the other, not going to solve the problem but will help understand it better hopefully!!

ARC-1950 - create branch search logs

---

src/routes/github/configuration/github-configuration-get.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/github/subscription/github-subscription-delete.ts
src/routes/github/subscription/github-subscription-get.ts
src/util/github-utils.test.ts
src/util/github-utils.ts

Occasionally isAdmin check fails with GitHub returning either 401 or 403; trying to narrow down the problem
**Why**
Cause customers suffer
🤠 
🤠 
🤠 
🤠

[EAZY KARMA INSTANT RELEASE] NONE: more logs for isAdmin check

---

src/routes/github/repository/github-repository-get.ts

Debug output for search result (counters) for create-branch.
**Why**
https://github.com/atlassian/github-for-jira/issues/1845

NONE: add some debug info for create-branch search

---

src/github/client/github-client-interceptors.ts
src/routes/github/repository/github-repository-get.ts

See title
**Why**
Cause cannot investigate customer's complains

NONE: improve logging around create-branch search

---

src/routes/github/github-router.ts
src/routes/github/repository/github-repository-get.test.ts
static/js/github-create-branch.js

Applying correct set of middleware to routes for repo search and branch validation. Jirahost is passed as query parameter so standard set of middleware didn't work.

ARC-1967 Fixing create branch bug

---

src/config/logger.test.ts
src/config/logger.ts

Adding error message to logs (because it wasn't there :wat:)
Removing some UGC from logs
**Why**
Error messages - we need them  for debugging
UGC - it is bad to log them, m'kay?

None add error message to logs and remove some ugc

---

src/config/logger.test.ts
src/config/logger.ts

Removing Auth header from logs
**Why**
Dislike

NONE: remove more data from logs

---

src/config/logger.test.ts
src/config/logger.ts
src/github/client/github-client-errors.test.ts
src/github/client/github-client-errors.ts
src/github/client/github-client-interceptors.ts
src/github/client/github-client.ts
src/sqs/error-handlers.test.ts
src/sync/installation.test.ts

- sanitise relative URLs
- move URL from message to error property
**Why**
- cause we don't want to log UGC too much

None improve logging more

---

src/config/logger.test.ts
src/config/logger.ts
src/sync/installation.ts

Killing UGC
**Why**
Because I can

[EZY KARMA] NONE: removing more UGC

---

src/config/feature-flags.ts
src/transforms/transform-pull-request.ts

Making code clearer
Add debugging of payloads without reviewers
**Why**
Because we have started seeing this error
Yes

NONE: debug reviews without reviewers

---

test/e2e/constants.ts
test/e2e/create-branch.e2e.ts
test/e2e/utils/jira.ts

Remove the project that is created after create branch tests

remove project after create branch test

---

src/sync/installation.ts

See title
**Why**
Logs are useful. Good logs are even more useful

[EZY KARMA] NONE: improve sync logs

---

src/sync/installation.ts

... and by downshift I meant to add more logs to sync
**Why**

[KARMA INSTANT RELEASE FREE DOWNLOAD] NONE: add more logs to sync

---

src/config/feature-flags.ts
src/transforms/transform-pull-request.test.ts
src/transforms/transform-pull-request.ts
test/fixtures/api/pull-request-reviewers-has-user.json
test/fixtures/api/pull-request-reviewers-no-user.json

Handle gracefully deleted reviewers
**Why**
Because otherwise it will throw an exception and will block the sync

NONE: handle deleted reviewers gracefully

---

.github/ISSUE_TEMPLATE/config.yml

Change copies and links in the template for better UX
**Why**
Mike's feedback
_Jira Issues_

Change copies and links in the template for better UX

---

src/routes/github/github-encrypt-header-post.test.ts
src/routes/github/github-encrypt-header-post.ts

Adding jiraHost to endpoint
**Why**
The customer will need to trigger this for 2 Jiras. That would help them to notice a mistake.
Already under one
ARC-1976
🤠

ARC-1976: add jiraHost to output

---

src/config/logger.test.ts
src/config/logger.ts

Stop logging cookies
**Why**
because logging cookies is bad

NONE: stop logging cookies

---

src/sqs/push.ts

Fixing logging
**Why**
Because we can do better

[EASY KARMA] NONE: fix logging for push queue

---

README.md
github-for-jira.sd.yml
src/sync/transforms/branch.ts
src/sync/transforms/pull-request.test.ts
src/sync/transforms/pull-request.ts

Added a section to give details about backfilling process. 
**Why**
Square customer is curious to know about which historical data will be backfilled

Updating readme to include about backfill

---

src/sync/installation.test.ts
src/sync/installation.ts

Replying sequelize errors because we don't have DLQ just yet
**Why**
There are more customers complaining their syncs were "stuck", and splunk shows there was a sequelize error.

NONE: retry sequelize errors until we don't have DLQ

---

src/config/feature-flags.ts
src/routes/jira/jira-get.ts
static/css/jira-configuration-new.css
static/js/github-configuration.js
views/jira-configuration-new.hbs
views/partials/jira-configuration-table.hbs

Promote the restart backfill button to main table.
Also goes hand in hand with this PR.
https://bitbucket.org/atlassian/fusion-monitoring/pull-requests/726
**Why**
N/A
ARC-1975
Unit test
Local
Continue on the ticket to show more info.

ARC-1975 promot restart backfill button

---

src/config/logger.test.ts
src/config/logger.ts
src/github/client/github-client-errors.ts

Improve error logging
**Why**
Cause logging is important to debug customer issues

NONE: improve error logging

---

src/sqs/sqs.ts

Adding jiraHost to SQS logger
**Why**
For better logging

[ONE-LINER] NONE: add jiraHost to SQS logger

---

src/models/subscription.ts
src/routes/api/api-resync-post.ts
src/routes/api/installation/api-installation-sync-post.test.ts
src/routes/api/installation/api-installation-sync-post.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/jira/sync/jira-sync-post.ts
src/sqs/sqs.types.ts
src/sync/backfill-since-date-calc.test.ts
src/sync/backfill-since-date-calc.ts
src/sync/installation.ts
src/sync/sync-utils.test.ts
src/sync/sync-utils.ts
src/sync/sync.types.ts

Update the backfillSince data column.
**Why**
So that user can have visibility of when the backfill is up to. 
N/A <-- column is not being used. 
ARC-1957
Unit Test
Manual Test: [WIP]
Display the backfill date on UI.

Arc 1957 udpate backfill since date

---

src/sync/pull-request.ts

Do not fetch PR data if no issue keys
**Why**
Cause it is stupid
_Jira Issues_

NONE: do not fetch PR if no issue keys

---

src/middleware/jira-symmetric-jwt-middleware.test.ts
src/middleware/jira-symmetric-jwt-middleware.ts

Adding jiraHost to frontend logging
**Why**
Because it is useful for debugging

[2 lines of code] NONE: add jiraHost to logs :facepalm:

---

src/config/feature-flags.ts
src/sync/build.test.ts
src/sync/build.ts
src/sync/pull-request.ts
src/sync/pull-requests.test.ts
test/utils/database-state-creator.ts

Same as for builds https://github.com/atlassian/github-for-jira/pull/1942
**Why**
Cuz it is slow

HOT-102548 increase page size for prs

---

src/sync/pull-request.ts

Adding info about how many PRs were sent to Jira.
**Why**
Trying to understand the patterns of our customers and if maybe we could skip some syncing.

[ONE-LINER] NONE: show how many PRs should be sent to Jira

---

src/sync/installation.ts
src/sync/pull-request.ts
src/sync/transforms/pull-request.ts
src/transforms/transform-pull-request.ts

Just removing some code duplication that I introduced on the weekend. Also adding some comments about pagination (tribal knowledge before)
**Why**
Cleaning up my own mess

NONE: remove some code duplication

---

src/sync/pull-request.ts
src/sync/pull-requests.test.ts

Parallel fetching of PRs (2 pages) for a customer
**Why**
Cause it is still slow.
Existing one.

None pr parallel fetching

---

src/sync/build.ts
src/sync/pull-requests.test.ts

Adding some more logging around builds
**Why**
To understand better a customer who has zillions of build

[EAZY KARMA] NONE: add some more logging around builds

---

src/util/preemptive-rate-limit.ts

Just log plain rate limit values occasionally. 
**Why**
That would help us understand the situation for a particular customer better.

[EASY KARMA] NONE: log sampled rate limit

---

src/sync/pull-request.ts
src/sync/pull-requests.test.ts

Filter the return PR on the from date.
**Why**
We also want to limit the amount of PRs we pulled.
backfill-algorithm-incremental
ARC-2033
Unit test
1. Add new col to save the fromDate for pull request in reposync state

Arc 2033 apply backfill from date on pr

---

src/config/logger.ts
src/github/client/github-client-errors.ts
src/jira/client/jira-client.ts
src/models/subscription.ts
src/sync/installation.test.ts
src/sync/installation.ts

Fixing some typing prior to implementing the new event handler for backfilling
**Why**
Otherwise the error handling PR will be huge and with multiple purposes
All glory to TypeScript and tests

Arc 1997 some typescript hardening around error handling

---

src/sync/commits.ts
src/sync/installation.ts

In case of 120 a GraphQL error is thrown

NONE: limit commits page size to 100

---

src/sync/commits.ts

Log last commit date
**Why**
Better visibility in logs how fast a sync is going

NONE: log commits last date

---

src/routes/jira/connect/enterprise/jira-connect-enterprise-post.test.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts
src/util/http-headers.test.ts
src/util/http-headers.ts

Better checking if URL belongs to GHE or not
**Why**
Because we might have API gateways in between

NONE: better validation if GHE server or not

---

db/migrations/20230320085600-add-commit-from-all-entities.js

Add db cols for recording success time for each entities. 
**Why**
Even though it is not being used right now, we don't want to lose the information.
N/A
ARC-2033
N/A
Impl code to save the time.

ARC-2033 add col to record success time

---

src/config/metric-helpers.test.ts
src/config/metric-helpers.ts
src/routes/api/api-resync-post.ts
src/routes/api/installation/api-installation-sync-post.test.ts
src/routes/api/installation/api-installation-sync-post.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/jira/sync/jira-sync-post.ts
src/sqs/sqs.types.ts
src/sync/installation.ts
src/sync/sync-utils.ts

Add tags to current full sync duration metrics.
**Why**
We want to track and group different sync time for different scenarios
N/A
ARC-2041
Unit test
Try on each tasks?

ARC-2041 add tags to current metrics

---

src/models/reposyncstate.ts
src/sync/installation.test.ts
src/sync/installation.ts

repository
Record success backfill date for all entities except branch
**Why**
We don't want to lose information.
n/a
ARC-2033
[WIP]
N/A

ARC-2033 update logic to save dates for all tasks except branch and

---

src/github/client/github-client-interceptors.test.ts
src/models/reposyncstate.test.ts
src/models/reposyncstate.ts
src/routes/jira/jira-get.ts
src/sqs/backfill-error-handler.test.ts
src/sqs/backfill-error-handler.ts
src/sync/branch.test.ts
src/sync/commits.ts
src/sync/discovery.ts
src/sync/installation.test.ts
src/sync/installation.ts
src/sync/parallel-page-fetcher.ts
src/sync/sync.types.ts
test/utils/database-state-creator.ts

- Removing retry-with-small-page thing
- as a consequence, Permission check was moved to SQS error handler
-  Some minor renamings/refactorings
**Why**
- Cause it is broken for several task types and there's no evidence it helps. No comments, no explanation, nothing. Starting from zero ground and we will go from there.

ARC-1997: remove small page retries

---

views/jira-configuration-new.hbs

Update description for continue backfill window
USE_BACKFILL_ALGORITHM_INCREMENTAL
[ARC-2038]
[ARC-2038]: https://softwareteams.atlassian.net/browse/ARC-2038

ARC-2038 Update the description of continue backfill window

---

static/js/jira-configuration.js
views/partials/jira-configuration-table.hbs

Default to 6 months from the last. backfilled date. If it is not backfilled at all, it would be 6 months from the current date.
backfill-algorithm-incremental
[ARC-2053]
[ARC-2053]: https://softwareteams.atlassian.net/browse/ARC-2053

ARC-2053 Update default backfill date to 6 months from the last backfilled date

---

src/config/feature-flags.ts
src/config/logger.test.ts
src/github/client/github-installation-client.ts
src/sync/branches.ts
src/sync/build.test.ts
src/sync/build.ts
src/sync/commits.test.ts
src/sync/commits.ts
src/sync/deployment.ts
src/sync/discovery.test.ts
src/sync/discovery.ts
src/sync/installation.test.ts
src/sync/installation.ts
src/sync/page-counter-cursor.test.ts
src/sync/page-counter-cursor.ts
src/sync/parallel-page-fetcher.test.ts
src/sync/pull-request.ts
src/sync/pull-requests.test.ts
src/sync/sync.types.ts
test/mocks/error-responses.ts

- Control page size with a FF
- Control parallel fetching of PRs and builds by their own FFs
**Why**
Because it is cool.

ARC-1997: control page size with a FF

---

src/interfaces/github.ts
src/sync/build.test.ts
src/transforms/transform-workflow.ts

- fixing some build tasks
**Why**
- we have ~2 occasions per 24 hours. Spotted while was monitoring my changes

[EASY KARMA] [HAPPY CUSTOMERS] NONE: fix some build tasks

---

src/github/client/github-client-errors.ts
src/github/client/github-installation-client.test.ts
src/github/client/github-installation-client.ts
src/routes/github/subscription/github-subscription-delete.ts
src/routes/jira/jira-delete.ts
src/sync/deduplicator.ts
src/sync/installation.test.ts
yarn.lock

Improve error handling of isChangedFiles error
**Why**
Currently "isChangedFiles" function doesn't make sense returns false-positives for quite a broad range of errors
Error handling, no need.

NONE: improve error handling of changedFiles error

---

src/config/feature-flags.ts
src/routes/jira/jira-get.ts
static/js/jira-configuration.js
views/partials/jira-configuration-table.hbs

Fix some missing bugs in error retry screen
**Why**
ARC-2067
Local
Fix another mix partial/full sync bug

ARC-2067 fix bugs on missing github app id and mix ff

---

src/sync/installation.test.ts
src/sync/installation.ts
src/sync/scheduler.test.ts
src/sync/scheduler.ts

- optimized scheduler
- added tests
**Why**
- reduce load on db
- tests are good
- existing one

NONE: optimize scheduler, add more tests

---

src/github/client/github-installation-client.test.ts
src/github/client/github-installation-client.ts

Retry 502 for branches and commits
**Why**
They keep failing with changedFiles even when retried with a delay (SQS)

NONE: retry 502

---

src/sync/scheduler.test.ts
src/sync/scheduler.ts

Handle end state properly
**Why**
Cause otherwise bad times
_Jira Issues_

NONE: fix end state

---

README.md

Updated readme with incremental backfilling process

ARC-2098 Updated readme with incremental backfilling process

---

.gitignore
sonar-project.properties

- Adding integration for Sonarqube.
**Why**
- Doesn't look good in techops report
- Staging

ARC 2092 - Sonarqube integration for GH4J

---

static/css/jira-configuration-new.css
static/js/jira-configuration.js
views/partials/jira-configuration-table.hbs

Corrected the date format for Backfilled date label and default date for continue backfill date picker to 6 months after the `backfilled from` date
Backfill incremental algo
[ARC-2019]
[ARC-2019]: https://softwareteams.atlassian.net/browse/ARC-2019

ARC-2019 Consistent date format 

---

src/github/pull-request.ts

Fixing loggin
**Why**
because 1. we already have jiraHost in logger; 2. it is not baseUrl, but baseURL :rage:

NONE: fix logging for PR webhook handler

---

.github/workflows/on-push.yml
package.json
yarn.lock

Noissue bump aws sdk  bump node mem

---

src/sync/installation.ts
src/sync/sync.types.ts

Add duration time metrics for backfill tasks
**Why**
Want to see how much time does each task take.
N/A
N/A
N/A

add metrics for backfill tasks

---

src/sync/installation.ts

Address previous comments. Remove the NaN, make the metrics optional though but with warning msg.
Compare to previous attempt (https://github.com/atlassian/github-for-jira/pull/2062), maybe this is better?

Remove NaN from task metrics

---

src/routes/jira/atlassian-connect/jira-atlassian-connect-get.ts
src/routes/session/session-get.test.ts
src/routes/session/session-get.ts
static/js/jira-configuration.js
static/js/jira-select-card-option.js
static/js/jira-server-url.js
test/snapshots/routes/jira/atlassian-connect/jira-atlassian-connect.test.ts.snap
test/snapshots/routes/maintenance/maintenance-router.test.ts.snap

Unblocking SSO customers
**Why**
Cause they are in pain

NONE: reset cookies when session is initalised

---

src/github/client/github-client-interceptors.ts
src/github/client/github-client.ts
src/github/client/github-installation-client.ts
src/github/client/github-user-client.ts

Add metrics for graphql
**Why**
Because the current metrics only tell it is a graphql query, but didn't further dive into which exactly the graph query is.
N/A
N/A
Local
N/A

Add metrics for the real graphQuery

---

src/middleware/github-webhook-middleware.ts

Adding check for installation id in webhook payload. In one of the error, it has been observed that it is missing in payload and causing some DB error.

Adding check for Installation id

---

src/github/client/github-installation-client.ts
src/middleware/frontend-log-middleware.ts
src/middleware/jira-symmetric-jwt-middleware.test.ts
src/routes/api/api-router.test.ts
src/routes/github/github-oauth-router.test.ts
src/routes/github/manifest/github-manifest-complete-get.test.ts
src/routes/github/manifest/github-manifest-complete-get.ts
src/routes/github/manifest/github-manifest-get.test.ts
src/routes/github/manifest/github-manifest-get.ts
src/routes/github/manifest/github-manifest-router.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.test.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-apps-get.test.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-apps-get.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-get.test.ts
src/routes/jira/jira-get.test.ts
src/routes/jira/sync/jira-sync-post.test.ts
src/routes/router.ts
static/js/jira-select-card-option.js
views/github-manifest.hbs
views/jira-select-app-creation.hbs

Switching GHE manifest flow to use temp storage
**Why**
1. fixing existing vuln
2. preparation to BTF work (passing config object around instead of server URL)
nah, improved tests a lot + lots of testing
manually
Manual flow

ARC-2122: automatic flow

---

src/config/errors.ts
src/github/client/github-installation-client.ts
src/github/client/github-user-client.ts
src/middleware/jira-symmetric-jwt-middleware.ts
src/routes/github/branch/github-branch-get.test.ts
src/routes/github/branch/github-branch-get.ts
src/routes/github/create-branch/github-branches-get.test.ts
src/routes/github/create-branch/github-branches-get.ts
src/routes/github/create-branch/github-create-branch-get.test.ts
src/routes/github/create-branch/github-create-branch-get.ts
src/routes/github/create-branch/github-create-branch-options-get.test.ts
src/routes/github/create-branch/github-create-branch-options-get.ts
src/routes/github/create-branch/github-create-branch-post.test.ts
src/routes/github/create-branch/github-create-branch-post.ts
src/routes/github/github-router.ts
src/routes/github/repository/github-repository-get.test.ts
src/routes/github/repository/github-repository-get.ts
static/js/github-create-branch-options.js
views/github-create-branch-options.hbs
views/github-create-branch.hbs

Reverts atlassian/github-for-jira#2047
401 error on prod

Revert "Create branch jwt fix"

---

deploy/lambda/auto-deployment.js

- Removing the console that was added for testing for [this PR](https://github.com/atlassian/github-for-jira/pull/2075)
**Why**
- Testing is done, things look good, so no need for this console.

REVERT -  Changes for testing updating keys in lambda script

---

src/sync/installation.ts

Logging out the error type for a failed backfill task
**Why**
so we can collect whats breaking easier

ARC-2123 added error type log for backfill task

---

src/models/github-server-app.test.ts
src/models/github-server-app.ts
src/routes/github/manifest/github-manifest-complete-get.test.ts
src/routes/github/manifest/github-manifest-complete-get.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.test.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.ts

- Delete connect config from temp storage
**Why**
To keep redis clean.
tests

ARC-2122 delete temp config on create

---

src/jira/client/axios.ts

Add logs to see
1. Why I couldn't find status calls failured at 302 on 405 request
2. Help decide future should we just wrap 405 as 200 or make it to 404 and delete message?
**Why**
ARC-2112
Just logs
Fix for all jira api endpoints on 405 (and potential other status)

ARC-2112 add logs for 405

---

src/models/subscription.ts
src/routes/github/create-branch/github-branches-get.test.ts
src/routes/github/create-branch/github-branches-get.ts
src/routes/github/create-branch/github-create-branch-post.test.ts
src/routes/github/create-branch/github-create-branch-post.ts

Search by repo owner instead of owner and reponame since we they will all have a unique subid
Same fix for the creation as for the fetching of the branches

Get sub by owner

---

README.md
src/routes/github/configuration/github-configuration-router.test.ts
src/routes/github/create-branch/github-create-branch-get.test.ts
src/routes/github/create-branch/github-create-branch-options-get.test.ts
src/routes/github/github-encrypt-header-post.test.ts
src/routes/github/github-oauth-router.ts
src/routes/github/github-router.test.ts
src/routes/github/repository/github-repository-get.test.ts
src/routes/github/setup/github-setup-router.test.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-router.test.ts
test/utils/cookies.ts

Add workaround for SSO problem
**Why**
To unfuck SSO customers
Nah
ARC-2068
unit tests, manually

ARC-2068 add reset GitHub token query param

---

docs/FAQs.md

Removing misleading FAQ item.
**Why**
Because GHE support SSO.
_Jira Issues_

ARC-2068: remove misleading FAQ item

---

src/github/client/github-installation-client.test.ts
src/github/client/github-installation-client.ts
src/github/client/github-queries.ts

Retrying branches without commits on 502
**Why**
Because it is already broken, and we cannot make it worse.
unit tests, manually

NONE: retry branches without commits

---

db/migrations/20230503000639-github-server-app-add-api-key-columns.js

[EZY KARMA] ARC-2154: add 2 columns for API key header/value

---

src/sqs/branch.ts
src/sqs/deployment.ts
src/sqs/push.ts

rename some metrics tags
**Why**
so that in the dashboard, when sum (group by trigger and subTrigger), those metrics will appear. (Currently they disappear because the subTrigger is not present)

fix metrics

---

src/config/feature-flags.ts

- Removing the usage of unused FF.
**Why**
- Not needed anymore

CLEANUP - Remove unused FF

---

src/routes/github/configuration/github-configuration-app-installs-get.test.ts
src/routes/github/configuration/github-configuration-app-installs-get.ts

Fixing server URL 
**Why**
Cause the host name might be different for BTF customers
Nah
_Jira Issues_

NONE: fix server URL

---

playwright.config.js
test/e2e/teardown.ts
test/e2e/utils/jira.ts

Changing E2E selector because jira keeps changing it's testids

Fixing more things because jira just changed

---

docs/e2e-tests.md

Farewell and thanks for all the fish :)

Adding e2e test documentation

---

src/transforms/transform-deployment.test.ts
src/transforms/transform-deployment.ts

Reverts atlassian/github-for-jira#2098

Revert "ARC-2144 try to compare to future deployments only"

---

Dockerfile
Dockerfile.prod
src/config/feature-flags.ts
src/github/client/github-installation-client.ts
src/routes/api/curl/curl-utils.ts
src/util/curl/curl-utils.test.ts
src/util/curl/curl-utils.ts

Add a `curl -v` to some of the endpoints to help debugging.
**Why**
github ask for the curl -v output.
log-curlv-output
ARC-2135
Unit test
stg: wip

Arc 2135 add curl v

---

github-for-jira.sd.yml

Making queue size alert less sensitive
**Why**
Alerts and autocloses in a few mins

None fix scaling on queue size

---

github-for-jira.sd.yml

Add UGC tags.
**Why**
It is required in prod deployment.
_Jira Issues_

add ugc tags

---

github-for-jira.sd.yml

Temp bump to 300 to calm down on the alert
**Why**
Been seeing over 200 msg in backfill queue. Need more time to investigate why
_Jira Issues_

Temp bump to 300 to calm down on the alert

---

src/config/logger.ts
src/routes/api/api-btf-migrate-post.ts
src/routes/api/api-router.test.ts
src/routes/api/api-router.ts
src/sqs/error-handlers.ts
src/sqs/sqs.ts
src/util/logger-utils.test.ts
src/util/logger-utils.ts

- script to migrate Beta BTF customers from FF to Db
- remove unsafe logs
**Why**
- because we are moving away from FF API keys
- because we haven't checked unsafe logs for the past 6 months

ARC-2192 migrate btf beta customers

---

src/github/client/github-client.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/github/manifest/github-manifest-complete-get.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.ts

- adding withApiKey tag here and there
**Why**
- we'd like to have visibility around how it's been used

ARC-2191: add withApiKey flag to analytics

---

src/config/feature-flags.ts
src/util/get-github-client-config.test.ts
src/util/get-github-client-config.ts

Removing FF
**Why**
Not used anymore: for the internal testing instance we should use API gateway

[EZY KARMA]: remove outbound proxy skiplist FF

---

static/js/jira-api-key-validation.js
views/jira-manual-app-creation.hbs
views/jira-server-url.hbs

Update copies
**Why**
Time to release this.
Existing one

ARC-2184: update copies

---

github-for-jira.sd.yml

Disabling insecure http connections by forcing http requests to be redirected to https. 
**Why**
Improved security by preventing insecure http connections.
N/A
ARC-2188
N/A
N/A

ARC-2188: Disable insecure http connections

---

static/css/jira-configuration.css
static/js/jira-configuration.js
views/jira-configuration.hbs

Fix some ambiguous copy
**Why**
It causes confusions
ARC-3198
Local
N/A

ARC-2198 fix restart backfil text

---

src/routes/github/webhook/webhook-receiver-post.ts

Need to listen to the new event
**Why**
Because

[ONE-LINER] ARC-2206: listen to requested_review event

---

etc/poco/bundle/extras-prod.json
etc/poco/bundle/main-test.json
etc/poco/bundle/main.json

- Adding the missing test cases in POCO to get 100% coverage.
**Why**
- So that we don't see the POCO health check in our tech reports
- Locally

ARC 2095 - Poco health coverage for GH4J

---

src/config/feature-flags.ts
src/routes/api/installation/api-installation-delete.ts
src/routes/jira/jira-get.ts
src/routes/jira/sync/jira-sync-post.test.ts
src/routes/jira/sync/jira-sync-post.ts
src/sync/build.test.ts
src/sync/build.ts
src/sync/deployment.test.ts
src/sync/deployment.ts
src/sync/pull-request.ts
src/sync/pull-requests.test.ts
static/js/jira-configuration.js
views/jira-configuration.hbs
views/partials/jira-configuration-table.hbs

Remove the incremental backfill ff
**Why**
1. It is rollout 100% for at least 30 days. No customer support on disable the ff.
2. I can't refactor the backfill algorithm with this ff on. Too many branches.
_Jira Issues_

ARC-2033 remove ff incremental backfill

---

src/github/client/github-queries.ts
src/sync/deployment.test.ts
src/sync/deployment.ts
src/transforms/transform-deployment.test.ts
src/transforms/transform-deployment.ts
test/fixtures/api/graphql/deployment-nodes.json

1. Fix the `url is null` error
2. Fix the `unknown state` error.
**Why**
same use-dyanmo-db-for-backfill
ARC-2119
Unit test.

Arc 2119 fix url null pipeline

---

src/routes/github/subscription-deferred-install/github-subscription-deferred-install-get.test.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-get.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-post.test.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-post.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-router.ts
views/subscription-deferred-install-approval-form.hbs

**Why**
Cause it is better
Under existing one
lazy
locally
chill

NONE: fancy UI for deferred install flow

---

src/middleware/jira-symmetric-jwt-middleware.ts

None update auth header

---

src/config/feature-flags.ts
src/sync/deployment.test.ts
src/sync/deployment.ts

Pull more pages during deployment backfill
**Why**
Try to see if we can improve deployment accuracy rate
backfill-deployment-extra-pages
N/A
Local
Verify it with metrics

Pull more pages during deployment backfill

---

src/github/client/github-queries.ts
src/transforms/transform-pull-request.ts

Add optional operator
**Why**
From doc here https://docs.github.com/en/graphql/reference/objects#pullrequest
the `headRef` is optional, it cause null pointer exception and make the task retry and failed.
N/A
N/A
N/A
N/A

fix some null pointer exception

---

src/routes/jira/workspaces/repositories/jira-workspaces-repositories-associate.test.ts
src/routes/jira/workspaces/repositories/jira-workspaces-repositories-associate.ts
src/routes/jira/workspaces/repositories/jira-workspaces-repositories-get.test.ts
src/routes/jira/workspaces/repositories/jira-workspaces-repositories-get.ts

Updates to searchRepository + minor adjustment to associateRepository
**Why**
Change in spec https://hello.atlassian.net/wiki/spaces/OTFS/pages/2581193453/Extending+GitHub+for+Jira+for+generic+containers#searchRepositories
Locally + unit tests

None update search repos updated spec

---

src/routes/jira/workspaces/repositories/jira-workspaces-repositories-associate.test.ts
src/routes/jira/workspaces/repositories/jira-workspaces-repositories-associate.ts

Mod to associate repo
**Why**
So it can be consumed by provider bridge
unit tests
🤞 the request works

update associatedRepo response so it can be consumed by provider bridge

---

.env.development
src/github/deployment.ts
src/github/push.ts
src/jira/client/jira-client.ts
src/services/user-config-service.test.ts
src/services/user-config-service.ts
src/sync/discovery.ts
src/transforms/transform-deployment.test.ts
src/transforms/transform-deployment.ts

Add more logs to help debugging for a customer support ticket
**Why**
Current log is not enough
N/A
N/A
Local
N/A

Add more logs for user config updates

---

src/sync/installation.test.ts
src/sync/installation.ts

Reverts atlassian/github-for-jira#2055
Deployment should be much better now.

Revert "ARC-2119: force deployments status to go to complete on error during backfill"

---

github-for-jira.sd.yml
src/sqs/backfill-error-handler.test.ts
src/sqs/backfill-error-handler.ts
src/sqs/queues.ts
src/sync/installation.ts

Reverts atlassian/github-for-jira#2184

Revert "[EAZY kARMA] NONE: add more retries for discovery"

---

src/routes/github/repository/github-repository-get.ts

ARC-2237 add more logs to create branch repo search
**Why**
ARC-2237 add more logs to create branch repo search
ARC-2237 add more logs to create branch repo search
ARC-2237 add more logs to create branch repo search
N/A

ARC-2237 add more logs to create branch repo search

---

src/github/client/github-installation-client.ts
src/util/curl/curl-utils.test.ts
src/util/curl/curl-utils.ts

- Getting CURL output for discovery task failure
**Why**
Because GitHub support will ask for it
Existing ones

NONE: add curl output

---

src/config/errors.ts
src/routes/error-router.ts
src/routes/github/github-oauth.ts
src/routes/router.test.ts
src/routes/router.ts
views/error.hbs

Fix the error routing and fix oauth callback xss injection.
**Why**
Prevent vulns on XSS
N/A
ARC-2238
Unit test
N/A

Arc 2238 fix vuln xss callback

---

src/util/curl/curl-utils.test.ts
src/util/curl/curl-utils.ts
src/util/http-headers.ts

Adding cmd to curl output
**Why**
GitHub support asked for it
Existing ones
unit tests

NONE: include cmd into curl meta output

---

src/jira/client/jira-client.ts
src/sync/branches.ts
src/sync/commits.ts
src/sync/pull-request.ts
src/transforms/transform-pull-request.ts

Add more UGC logs (with hashed)
**Why**
Help debugging our code.
N/A
_Jira Issues_

Inno add logs for backfill

---

etc/scripts/generate-github-test-data.py

Went a bit harder on SRP
added better error handling, 
saving state for failure incase of error…
creates for org instead of user

Updates to mock data script

---

github-for-jira.sd.yml

make backfill much more sensitive since its always too slow to catch up

NONE - make backfill much more sensitive since its always too slow to catch up

---

src/sync/sync-utils.ts

Add more logs for sync utils
**Why**
Need especially the commitDate for investigation
None
None
None

Add more logs for sync utils

---

src/github/client/github-installation-client.ts

Add a curlv to the command if return on repo for a particular jiraHost
**Why**
Help investigate a customer issue
log-curlv-output
ARC-2255
N/A

JST-881487 ARC-2255 Add-culr-on-fail-search-repo

---

spa/src/pages/StartConnection/index.tsx

-  Added the URL for manage organizations (used the GitHub cloud URL)
**Why**
- Missing piece from the previous PR

ARC-2276 - Add link for the Tooltip in the entry page

---

package.json

- Added `postInstall` script.
**Why**
- To avoid `yarn` issues.

Minor fixes

---

src/middleware/jira-symmetric-jwt-middleware.ts
src/routes/github/create-branch/github-create-branch-options-get.test.ts
src/routes/github/create-branch/github-create-branch-options-get.ts
src/routes/router.ts
static/js/github-create-branch-options.js
test/snapshots/app.test.ts.snap
views/github-create-branch-options.hbs

Removing some remnants of jiraHost/jwt query params
**Why**
Cause they are not secure
Nah
Locally

NONE: get rid of maybe jwt something something

---

src/config/feature-flags.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.frontend.test.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.test.ts
src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-get.frontend.test.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-get.test.ts
src/routes/jira/connect/enterprise/jira-connect-enterprise-get.ts
views/jira-manual-app-creation.hbs
views/jira-server-url.hbs

Removing a FF
**Why**
Don't want to see my name on TechOps again
No, removing it, stupid!
tests

NONE: remove FF

---

.github/workflows/on-push.yml
CONTRIBUTING.md
Dockerfile
docker-compose.yml
package.json

Remove app from docker compose to speedup development
**Why**
Remove app from docker compose to speedup development

Remove app from docker compose to speedup development

---

etc/poco/bundle/main-test.json
etc/poco/bundle/main.json

Add poco for spa resources. 
**Why**
Otherwise it won't work on stg/prod.
ARC-2271

ARC-2271 add poco for spa resources

---

db/migrations/20230711040027-add-avatar-to-subscription.js
src/models/subscription.ts

Adding optional entity to subscriptions. 
**Why**
Unblock [https://github.com/atlassian/github-for-jira/pull/2250](https://github.com/atlassian/github-for-jira/pull/2250)
_Jira Issues_

ISOC-3717 - added avatarUrl to subscription entity

---

spa/src/pages/ConfigSteps/index.tsx

- Fixes: Action for GitHub Enterprise Flow is not working

Arc enterprise flow fix

---

etc/spa-build/spa-build.sh

fix on spa build for failed command

fix on spa build for failed command

---

spa/src/common/Wrapper.tsx
spa/src/components/CollapsibleStep/index.tsx
spa/src/components/Error/index.tsx
spa/src/components/Error/test.tsx
spa/src/components/SelectDropdown/index.tsx
spa/src/components/SelectDropdown/test.tsx
spa/src/pages/ConfigSteps/index.tsx
spa/src/pages/Connected/index.tsx
src/rest-interfaces/oauth-types.ts
src/rest/routes/github-orgs/service.ts

- Added a loader for org selection dropdown.
- Error component created(still need to hook it up to errors from backend)
- CSS changes
**Why**
- To improve UX

ARC 2273 - Frontend tweaks

---

src/rest/routes/github-callback/index.test.ts
src/rest/routes/github-callback/index.ts
src/rest/routes/oauth/service.test.ts
src/rest/routes/oauth/service.ts

1. Fix xss on oauth callback
2. Remove redis state on callback exchange token.
**Why**
ARC-2271
Unit test / local
N/A

ARC-2271 fix some xss on callback

---

src/util/curl/curl-utils.test.ts

fix curl test
**Why**
atlassian.com change the response code on POST
N/A
N/A
Unit test
N/A

fix curl test

---

spa/src/common/Wrapper.tsx
spa/src/components/CollapsibleStep/index.tsx
spa/src/components/SyncHeader/index.tsx
spa/src/pages/ConfigSteps/index.tsx
spa/src/pages/StartConnection/index.tsx

- UI polishing for the first and second screen.
**Why**
- To make it pretty
**Screenshots**
- ![Screenshot 2023-07-24 at 4 04 46 pm](https://github.com/atlassian/github-for-jira/assets/13076255/bd0b9525-945b-4885-8ca4-b3e2b41b893b)
- ![Screenshot 2023-07-24 at 4 05 08 pm](https://github.com/atlassian/github-for-jira/assets/13076255/7cc4dc5a-30d9-4a7f-9356-7c836e190670)
- ![Screenshot 2023-07-24 at 4 05 01 pm](https://github.com/atlassian/github-for-jira/assets/13076255/c8ac723c-0916-438a-92f4-6ddd668ee980)
- ![Screenshot 2023-07-24 at 4 05 17 pm](https://github.com/atlassian/github-for-jira/assets/13076255/d91d4646-6fcc-4fd0-aa3c-4668c5832dc1)
- Changes to the last success screen

ARC-2305 - Polish the UI so that it is beautiful

---

spa/src/pages/ConfigSteps/index.tsx
spa/src/services/app-manager/index.ts
src/rest/routes/github-callback/index.test.ts
src/rest/routes/github-callback/index.ts
src/routes/github/setup/github-setup-get.ts

Auto connect once app is installed
https://github.com/atlassian/github-for-jira/assets/105693507/f3943291-4bdd-43bb-ae2f-d22af1d4e1fc
**Why**
It is one less step for user
ARC-2324
Local

ARC-2324 auto connect

---

src/routes/api/api-utils.ts

add logs for param uuid in request

---

spa/package.json
spa/public/index.html
spa/src/app.tsx
spa/src/global.d.ts
spa/src/sentry.ts
spa/yarn.lock
src/config/env.ts
src/routes/spa/spa-router.ts

Add sentry
**Why**
For capturing frontend error
ARC-2327
on sentry
N/A

ARC-2327 add sentry to spa

---

spa/src/pages/ConfigSteps/index.tsx
spa/src/utils/modifyError.tsx

- Mapping the IPBLock and SSO errors in the frontend
**Screenshots** 
- ![Screenshot 2023-07-28 at 11 40 02 am](https://github.com/atlassian/github-for-jira/assets/13076255/44574c66-6983-4a2a-9c9d-f97a80beb4c1)
- ![Screenshot 2023-07-28 at 11 40 11 am](https://github.com/atlassian/github-for-jira/assets/13076255/5dc2ab22-cdaa-4d16-b04d-5ac8737cfc1a)
- ![Screenshot 2023-07-28 at 11 40 07 am](https://github.com/atlassian/github-for-jira/assets/13076255/21c72324-1726-438c-986c-3a10d239a7a1)

ARC-2323 - Map IP block and SSO errors when users select in the dropdown

---

spa/src/api/axiosInstance.ts

increase the request timout
**Why**
3 seconds is too short
local

add timeout to spa request

---

spa/src/utils/modifyError.tsx

- Fixed typo
- Updated error message for SSO Login
**Screenshot**

Minor text fixes

---

src/github/client/github-installation-client.ts
src/github/client/github-queries.ts
src/jira/client/jira-client.ts
src/sync/pull-request.ts
src/sync/pull-requests-new.test.ts
src/transforms/transform-pull-request.test.ts
src/transforms/transform-pull-request.ts

Unskipping graphql PR tests
Adding coverage for the pull transform

Transform pull tests

---

github-for-jira.sd.yml

adding slauth gw
**Why**
to call admin endpoints
_Jira Issues_

NONE: add slauth gw

---

src/sqs/push.test.ts

1. Fix the failing test if run on its own
**Why**
1. I think the whole tesing/nocking is not in an ideal shape. Those nocks are shared, hence tests interfere with each others. That why test pass as whole but fail individual in this case.
Itself haha.
1. Improve nocking to be separate isolated into each tests.

Fix some test failing on its own

---

src/github/push.test.ts
src/github/push.ts
src/sqs/push.test.ts

None fix test jenkins  gary

---

spa/src/analytics/index.ts
spa/src/pages/StartConnection/index.tsx
src/routes/jira/jira-get.ts

1. fix some of the events
2. Added attribute to distinguish original vs spa experience
**Why**
So that not the mess existing funnel dashboard
N/A
ARC-2274
Local
N/A

Arc 2274 add attribute to empty screen

---

src/rest/middleware/error/index.test.ts
src/rest/routes/github-orgs/index.test.ts
src/rest/routes/jira/index.test.ts

ARC-2330 - Adding missing test cases

---

src/github/client/github-installation-client.ts
src/github/push.test.ts
src/github/push.ts
src/sqs/push.test.ts

Reverts atlassian/github-for-jira#2296

Revert "ARC-2328 Add check for Jenkinsfile"

---

spa/src/pages/ConfigSteps/index.tsx
spa/src/pages/ConfigSteps/test.tsx
spa/src/utils/modifyError.tsx

1. Restore the UI connect button after error.
2. "temporary" set an error message for lack of admin permission.
**Why**
Local

Fix connect button still loading after error

---

spa/src/pages/ConfigSteps/index.tsx
spa/src/services/app-manager/index.ts
spa/src/services/oauth-manager/index.ts
spa/src/utils/index.ts

Open new tab instead of popup
**Why**
The pop is missing in another screen very often.
_Jira Issues_

NONE open new tab instead of popup

---

src/github/client/github-user-client.ts
src/middleware/frontend-log-middleware.test.ts
src/middleware/frontend-log-middleware.ts
src/rest/routes/github-orgs/index.test.ts
src/routes/github/configuration/github-configuration-get.test.ts
src/routes/github/configuration/github-configuration-router.test.ts

Increasing page size for installations from default 30 to 100
**Why**
A customer complained
_Jira Issues_

None increase per page for user installations

---

src/github/code-scanning-alert.ts

Fix the wrong receive time and missing of metrics.

fix metrics received time bug

---

spa/src/common/Wrapper.tsx
spa/src/components/Step/index.tsx
spa/src/pages/ConfigSteps/index.tsx
spa/src/pages/ConfigSteps/test.tsx

- UI changes as per [the design](https://hello.atlassian.net/wiki/spaces/OTFS/pages/2757412054/5KU+Phase+I+--+UI+uplift)(Except for the UI for the Request Permissions screen)
- UI for the Request Permissions screen

5ku UI fixes

---

spa/src/pages/ConfigSteps/index.tsx

- Added view for Installation Requested.
- Confirm with the team and merge

ARC-2396 - What shall we show for the requested permission screen?

---

spa/src/pages/ConfigSteps/OrgsContainer/index.tsx
spa/src/pages/ConfigSteps/index.tsx

- Automating the SSO Login token exchange step.
**Why**
- Improved UX
- Locally
**Video**
- Since we can't simulate a SSO login, I'm changing Github logins as an equivalent to SSO login step. (Both cases involve changing tokens)
https://github.com/atlassian/github-for-jira/assets/13076255/57605721-503a-47f6-aad6-dbf18b7c09e5

SSO Login fixes - Manual clicking replaced by automation

---

spa/src/pages/ConfigSteps/OrgsContainer/index.tsx

- Changing the words for the SSO error fix message.

SSO Login - Re-wording

---

spa/src/pages/ConfigSteps/index.tsx
spa/src/utils/modifyError.tsx

- Error counter added
- Added the Contact Support link after 3 consecutive errors.
**Video**
https://github.com/atlassian/github-for-jira/assets/13076255/98a2a175-98b1-48b0-a0ff-7ee76b10439d

5KU error  with the contact support link

---

spa/src/common/Wrapper.tsx
spa/src/pages/ConfigSteps/OrgsContainer/index.tsx
spa/src/pages/ConfigSteps/index.tsx
spa/src/utils/modifyError.tsx
src/routes/jira/jira-get.test.ts
src/routes/jira/jira-get.ts

5KU - UI changes

---

src/config/feature-flags.ts
src/routes/github/configuration/github-configuration-get.test.ts
src/routes/github/configuration/github-configuration-router.test.ts
src/routes/github/github-oauth.test.ts
src/routes/github/github-oauth.ts
src/routes/github/github-router.test.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-get.test.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-post.test.ts

- Cleaning up the FF `github-scopes`

FF Cleanup - `github-scopes`

---

src/config/feature-flags.ts

remove unused flag

---

src/config/feature-flags.ts
src/github/repository.test.ts
src/github/repository.ts

Remove repo-created-event feat flag 
**Why**
Removing it since it’s been active in prod for over 2 months and no issues.
NA
NA
Unit tested locally using TDD approach
Test it in the upper env

None remove feature flag

---

.npmrc
package.json
src/config/feature-flags.ts
src/util/analytics-client.test.ts
src/util/analytics-client.ts
yarn.lock

Cleaning FF and killing the unused analytics client.

ARC-2316: delete FF

---

spa/src/pages/ConfigSteps/index.tsx

NONE quick att add

---

src/sqs/sqs.ts

Add logs to tell is it approaching the last retry before sending to DLQ

None add logs

---

src/jira/client/jira-client.ts

Data depot’s submit vulnerability api returns the rejectedEntities field in the response object that contains the information about the failed vulnerability key and reason. Use this information to do proper logging.
[ISOC-3944]
Unit test
[ISOC-3944]: https://softwareteams.atlassian.net/browse/ISOC-3944

ISOC-3944 Error Handling

---

src/routes/jira/jira-get.ts

Fix a bug that viewing spa page doesn't send analytics

Fix analytics bug on spa page view

---

db/migrations/20230823013417-add-code-scanning-alert-cols.js

Security Code Scanning Alerts backfill DB migration in preparation for https://github.com/atlassian/github-for-jira/pull/2361.
**Why**
Integrate GitHub with Security in Jira
https://hello.atlassian.net/wiki/spaces/CDX/pages/2673460294/RFC+GitHub+for+Jira+Security
**Affected issues**
[ISOC-3692](https://softwareteams.atlassian.net/browse/ISOC-3692)
Locally
[ISOC-3692]: https://softwareteams.atlassian.net/browse/ISOC-3692

ISOC-3692 code scanning backfill db migration

---

spa/src/pages/ConfigSteps/index.tsx

Fix some bugs on analytics events sending.

Fix some analytics events

---

src/routes/jira/jira-get.test.ts
src/routes/jira/jira-get.ts

Reverts atlassian/github-for-jira#2370

Revert "[ENHANCEMENT] - Clearing the configured app property when there are no connections"

---

spa/src/services/app-manager/index.ts
spa/src/services/oauth-manager/index.ts

1. Report more errors for frontend
**Why**
1. So that we know what's going on
N/A
N/A
N/A
N/A

Report frontend errors

---

src/routes/api/api-ping-post.ts
src/util/curl/curl-utils.ts

1. Add more ping in the ping route
**Why**
1. Need investigate more about the cert issue
N/A
ARC-2449
Tested locally
Run the curl in server and check output

ARC-2449 add debug logging for pinging a site for cert issue

---

Dockerfile
Dockerfile.prod

ARC-2449 comment out the ca bundle
**Why**
ARC-2449 comment out the ca bundle

ARC-2449 comment out the ca bundle

---

spa/src/api/axiosInstance.ts

1. Increase the timeout to 30 seconds for SPA frontend.
**Why**
2. Lots of our backend routing from time to tome exceed 15 seconds 
N/A
ARC-2456
N/A
Investigate the backend route

ARC-2456 increase timeout for frontend spa

---

src/github/pull-request.ts
src/transforms/transform-pull-request.test.ts
src/transforms/transform-pull-request.ts

NONE: make jiraHost mandatory

---

github-for-jira.sd.yml

Adjusing *UnhealthyHostCount alerts
**Why**
Because I want to sleep at night

NONE: adjust unhealthyhostcount threshold

---

spa/src/pages/ConfigSteps/index.tsx
spa/src/pages/StartConnection/index.tsx
spa/src/services/app-manager/index.ts
spa/src/services/oauth-manager/index.ts
spa/tsconfig.json

1. Enhance the error reporting
**Why**
1. So Sentry can better group those errors.

None enhance sentry error info

---

spa/src/api/axiosInstance.ts
src/rest/middleware/error/index.ts

Add more log details (req url etc) into the error handler
**Why**
Need more info to investigate
N/A
N/A
N/A
N/A

None add more error log to rest

---

.eslintrc.json
src/models/subscription.test.ts
src/routes/api/api-router.test.ts
src/routes/github/setup/github-setup-router.test.ts
src/util/jira-utils.test.ts

Removes skipped tests
**Why**
Enabling eslint rules
None
NONE
Nothing should change

NONE remove skipped tests

---

github-for-jira.sd.yml

Overprovision web nodes for the night
**Why**
Just curious if it helps or not

NONE: increase nubmer of nodes for the night

---

package.json
src/config/metric-names.ts
src/main.ts
src/worker/startup.ts
yarn.lock

Emitting metrics about evenloop lag
**Why**
Trying to understand wtf is going on with web nodes and why the latency became a problem
Tested in stg
🤠

NONE: add eventloop-lag

---

src/services/subscription-installation-service.ts

This PR checks the security permissions for GitHub installation.
**Why**
It may be possible that new security permissions have been published but not accepted for installation.

Check security permissions for GitHub app installation

---

src/config/feature-flags.test.ts
src/config/feature-flags.ts

We have had about 350k error logs in the last 7 days in prod since the flag is returning false and treating that like an array.
Have checked its an array before trying to use .includes on it

'Cannot define if should send all' - fix bug throwing this error

---

Dockerfile.prod

Fixing build
**Why**
Cuz it is broken
_Jira Issues_

NONE: fix build

---

src/util/workers-health-monitor.ts

Remove unnecessary logging
**Why**
Because it is unnecessary
That's logging

NONE: logging

---

src/util/workers-health-monitor.ts

Log the content of /tmp
**Why**
For some reason, heapsnapshots are not picked up

NONE: log /tmp files

---

src/github/deployment.test.ts
src/github/deployment.ts
src/github/repository.ts
src/models/reposyncstate.test.ts
src/models/reposyncstate.ts
src/routes/api/api-reset-subscription-failed-tasks.ts
src/routes/api/api-router.test.ts
src/routes/api/installation/api-installation-delete-pollinator.test.ts
src/routes/api/installation/api-installation-syncstate-get.test.ts
src/routes/api/installation/api-installation-syncstate-get.ts
src/routes/jira/jira-connected-repos-get.ts
src/services/github/user.ts
src/sqs/backfill-discovery.test.ts
src/sync/scheduler.test.ts
src/sync/scheduler.ts
src/transforms/push.test.ts
src/transforms/push.ts
src/transforms/transform-pull-request.ts

Fixing OOM
**Why**
Cause OOMs are bad, m'kay.
Relying on tests and typescript
tests and typescript
Celerbrate! 🍾

NONE: fix OOM

---

src/sync/code-scanning-alerts.ts
src/sync/secret-scanning-alerts.ts

GitHub APIs throws error if code scanning or secret scanning are not configured. This PR handles those errors
**Why**
Don't wanna to pollute logs with unnecessary errors
GitHub security
[ISOC-4022]
[ISOC-4022]: https://softwareteams.atlassian.net/browse/ISOC-4022

ISOC-4022 Error handling in case code scanning or secret scanning are not configured

---

src/sync/dependabot-alerts.ts
src/transforms/transform-dependabot-alert.ts

Set identifier Url to alert url if it match from reference url
**Why**
Rejected by DD due to invalid URL

Fixing identifier url

---

src/sync/code-scanning-alerts.ts
src/sync/dependabot-alerts.ts
src/transforms/transform-code-scanning-alert.ts
src/transforms/transform-dependabot-alert.ts

Some vuls don't have display name so adding default display name foe those vulns.
**Why**
DD rejecting vuls without display name

Fixing display name issue

---

src/sync/code-scanning-alerts.ts
src/sync/dependabot-alerts.ts
src/transforms/transform-code-scanning-alert.ts
src/transforms/transform-dependabot-alert.ts

Truncating  additional.context to 255
**Why**
DD rejects vuln if additional.context is more than 255

Fixing long additional.context property

---

src/sync/code-scanning-alerts.ts
src/sync/dependabot-alerts.ts
src/sync/secret-scanning-alerts.ts

Adding logging for dependabot backfill

Adding more logging for dependabot backfill

---

src/routes/api/api-router.test.ts
src/routes/api/api-router.ts
test/snapshots/app.test.ts.snap

Adding two endpoints:
1. to drop pullCursor because it is broken
2. to trigger abort to debug throng

NONE: api to drop cursor

---

.eslintrc.json
src/github/client/installation-token-cache.ts
src/main.ts
src/middleware/frontend-log-middleware.ts
src/models/installation.ts
src/routes/api/installation/api-installation-router.test.ts
src/sync/deduplicator.test.ts
src/sync/deduplicator.ts
src/sync/installation.ts
src/util/get-github-client-config.ts
src/util/logger-utils.ts
src/util/workers-health-monitor.ts
src/worker.ts

Eslint for promise handling.  This excludes the routes directory and tests to control the scope of the change.
**Why**
lint
None
NONE
tests
more lint

NONE eslint for Promise handling

---

src/jira/client/jira-client.ts

NONE: add more logs

---

spa/src/app.tsx
spa/src/common/LoggedinInfo.tsx
spa/src/components/Error/KnownErrors/index.tsx
spa/src/pages/ConfigSteps/OrgsContainer/index.tsx
spa/src/pages/ConfigSteps/index.tsx
spa/src/pages/InstallationRequested/index.tsx
spa/src/services/app-manager/index.ts
spa/src/services/oauth-manager/index.ts
spa/src/utils/index.ts
spa/src/utils/modifyError.tsx

1. Remove localStorage usage for popup detection.
2. Add a "dismiss" link ( so that we can rest the error )
**Why**
1. Some device has permission problem accessing the local storage, we don't want that permission stop the whole app.
N/A
N/A
Local, Unit
N/A

Fix localstorage permission problem by remove it.

---

src/transforms/push.ts

more trash data coming through, putting in some optional chaining to let it process when data is missing!

NONE - catch any other cannot access x of 'undefined' during push transform for bad data

---

spa/src/pages/ConfigSteps/index.tsx

Error: persistent  alert on 5ku config page 
https://atlassian.slack.com/archives/C05473FS8Q5/p1697414058336529
Fix:
https://www.loom.com/share/8d2b544a10834b44a8964f22594727d7
**Why**
To fix the bug raised on slack.
NA
NA
locally

fix: persistance alert msg in 5ku

---

spa/src/pages/ConfigSteps/index.tsx

I found this glitch in the flow while doing some other work.
when ur trying to switch to different Github account,
our config pages shows the old Github account's org list for few sec.
Glitch: 
https://www.loom.com/share/a5d21e2bfb5f4c45b7929ad4a9c0d482

Fix persistance alert msg 5ku

---

src/transforms/push.ts

simplfying the code so we can handle trash better.
The little tweaks werent working so have done a more proper clean... hopefully!

None splice bug

---

src/sync/code-scanning-alerts.test.ts
src/sync/code-scanning-alerts.ts
src/sync/dependabot-alerts.test.ts
src/sync/dependabot-alerts.ts
src/sync/secret-scanning-alerts.test.ts
src/sync/secret-scanning-alerts.ts

Handled errors from secret scanning, code scanning and dependabot alert APIs
**Why**
Status set to failed in DB

Fixing errors from secret scanning API

---

src/config/feature-flags.ts
src/rest/routes/github-orgs/index.ts
src/routes/github/configuration/github-configuration-post.test.ts
src/routes/github/configuration/github-configuration-post.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-post.test.ts
src/routes/github/subscription-deferred-install/github-subscription-deferred-install-post.ts
src/routes/jira/jira-get.test.ts
src/routes/jira/jira-get.ts
src/services/subscription-installation-service.test.ts
src/services/subscription-installation-service.ts
static/js/jira-configuration.js
views/jira-configuration.hbs

- Removing the FF for 5KU.
- Updating test cases.
**Why**
- 5KU is the new choice, so no need to FF it.
- Test cases
- Locally

ARC 2552 - Remove 5KU FF

---

spa/src/analytics/analytics-proxy-client.ts
spa/src/analytics/types.ts
spa/src/components/Error/KnownErrors/index.tsx
spa/src/pages/Connected/index.tsx
spa/src/pages/DeferredInstallation/index.tsx
src/rest-interfaces/index.ts
src/rest/routes/deferred/deferred-analytics-proxy.ts
src/rest/routes/deferred/index.ts
test/snapshots/app.test.ts.snap

- Added new endpoint for sending analytics for DeferredInstallation page.
- Adding events for all clicks and views.
**Why**
- Analytics and stuffs...
- Local

ARC 2554 - Add analytics for the deferred installation flow

---

src/config/feature-flags.ts
src/transforms/util/github-get-pull-request-reviews.test.ts
src/transforms/util/github-get-pull-request-reviews.ts

- Removing FF skip-requested-reviewers
**Why**
- Cause its not being used anywhere and the FF is turned off.

Removing FF skip-requested-reviewers

---

spa/src/pages/ConfigSteps/index.tsx

- Adding number of organizations and type attributes for `OrganisationConnectionScreen` event.

Adding attributes for `OrganisationConnectionScreen`

---

test/e2e/utils/jira.ts

- Updating `data-test-id` to `data-testid`.
**Why**
- Case Jira has no consistency with these things. 
- Just merge

Fixing E2E tests

---

github-for-jira.sd.yml

- Updating the organization name in the sd file.
**Why**
- Admin work

Updating the organization in sd file

---

spa/src/analytics/types.ts
spa/src/pages/InstallationRequested/index.tsx

- Added event for the installation requested screen.
**Why**
- It was missing
- Locally

Added missing event

---

src/config/feature-flags.ts
src/routes/api/api-utils.ts
src/routes/github/setup/github-setup-router.test.ts

- Removing FF"early-exit-on-validation-failed"
**Why**
- Its true for everyone.

Removing FF "early-exit-on-validation-failed"

---

src/config/feature-flags.ts
src/sqs/sqs.test.ts
src/sqs/sqs.ts

- Removing FF `remove-stale-messages`
- Test cases

Removing FF `remove-stale-messages`

---

.eslintrc.json
src/github/client/github-anonymous-client.ts
src/routes/jira/security/workspaces/containers/jira-security-workspaces-containers-post.ts
src/routes/jira/sync/jira-sync-post.ts
src/routes/jira/workspaces/repositories/jira-workspaces-repositories-associate.ts
src/util/encryption-client.ts

Enable eslint rules
**Why**
lint
None
NONE
tests
More lint

NONE: Re-enable some eslint rules

---

.eslintrc.json
src/middleware/github-webhook-middleware.ts
src/middleware/jira-admin-permission-middleware.ts
src/models/axios-error-event-decorator.test.ts
src/models/axios-error-event-decorator.ts
src/models/jira-client.ts
src/models/sentry-scope-proxy.ts
src/models/sentry-scrope-proxy.test.ts
src/rest/routes/github-orgs/service.ts
src/routes/api/api-reset-subscription-failed-tasks.ts
src/routes/api/data-cleanup/cleanup-reposyncstates.ts
src/sqs/backfill.ts
src/util/create-url-with-query-string.ts
src/util/handlebars/handlebar-helpers.ts
src/util/webhook-utils.ts

Re-enable eslint rules
**Why**
More lint
None
NONE
Tests
More lint

NONE: eslint re-enable rules

---

.eslintrc.json
src/models/reposyncstate.ts
src/models/sentry-scope-proxy.ts
src/models/subscription.ts
src/routes/api/ghes-app-encryption-ctx/re-encrypt-ghes-app-keys.ts
src/routes/github/webhook/webhook-receiver-post.ts
src/routes/jira/jira-delete.ts
src/routes/jira/workspaces/jira-workspaces-get.ts
src/sqs/queues.ts
src/sync/installation.ts

Enable eslint rules
**Why**
lint
None
NONE
Tests
More lint

NONE: re-enable eslint rules

---

.eslintrc.json
src/github/client/github-installation-client.ts
src/jira/verify-installation.test.ts
src/models/github-server-app.test.ts
src/rest/helper/index.ts
src/routes/api/db-migrations/db-migration-down.test.ts
src/routes/api/db-migrations/db-migration-up.test.ts
src/routes/github/create-branch/github-create-branch-post.frontend.test.ts
src/routes/github/github-oauth.test.ts
src/routes/jira/jira-connected-repos-get.test.ts
src/sqs/backfill.test.ts
src/sync/deduplicator.test.ts
src/sync/installation.test.ts
src/transforms/transform-pull-request.test.ts
src/transforms/util/github-get-pull-request-reviews.test.ts
src/util/analytics-client.test.ts
test/e2e/constants.ts

More lint
**Why**
lint
None
NONE
tests
More lint

NONE: Re-enable more eslint

---

spa/src/global.d.ts
spa/src/pages/StartConnection/test.tsx
spa/src/utils/index.ts
src/config/errors.ts
src/middleware/frontend-log-middleware.test.ts
src/middleware/frontend-log-middleware.ts
src/rest-interfaces/index.ts
src/rest/middleware/error/index.ts

Add more entry detail error
**Why**
For investigation
N/A
N/A
Local
N/A

Add more detail in analytics error

---

src/github/client/github-client.ts
src/routes/api/api-router.ts
src/routes/api/ghes-app-verification/ghes-app-verification-router.ts
src/routes/api/ghes-app-verification/ghes-app-verify-get-apps.test.ts
src/routes/api/ghes-app-verification/ghes-app-verify-get-apps.ts
test/snapshots/app.test.ts.snap

Add api to call ghes app api with curl
**Why**
Help investigate customer ticket
N/A
[ARC-2641]
Stg
N/A
[ARC-2641]: https://softwareteams.atlassian.net/browse/ARC-2641

Arc 2641 ces 23417 customer cannot generate apps new installation url in ghes flow

---

etc/poco/bundle/extras-stg-test.json
etc/poco/bundle/extras-stg.json

Add poco settings for GHE polli test for crit test (DD only)

Add poco settings for stage ghe critical checks

---

src/services/audit-log-service.test.ts
src/services/audit-log-service.ts
test/setup/setup.ts

Update to return multi entries by date desc in get audit log
**Why**
The pollinator will need this.
[ARC-2643]
Unit test

ARC-2643 return  multi entries in api get audit log

---

src/github/workflow.test.ts
src/github/workflow.ts

Add context.action to workflow run audit log
**Why**
Need it in pollinator
[ARC-2643]
Unit test.

ARC-2643 preserve workflow action

---

.eslintrc.json
src/github/installation.test.ts
src/rest/routes/deferred/deferred-installation-url.ts
src/routes/api/data-cleanup/cleanup-reposyncstates.ts
src/routes/github/create-branch/github-branches-get.test.ts
src/routes/github/create-branch/github-create-branch-post.test.ts
src/routes/github/create-branch/github-remove-session.test.ts
src/routes/github/github-oauth.ts
src/routes/github/manifest/github-manifest-complete-get.ts
src/routes/github/subscription/github-subscription-delete.test.ts
src/routes/jira/jira-connected-repos-get.test.ts
src/sync/installation.test.ts
src/sync/scheduler.test.ts
src/util/workers-health-monitor.ts
test/e2e/utils/jira.ts
test/setup/env-test.ts

Enable lint rules
**Why**
Lint
Nope
NONE
tests
Lint

NONE: Reenable more lint rules

---

src/github/branch.ts
src/github/pull-request.ts
src/github/workflow.ts
src/interfaces/jira.ts
src/jira/client/jira-client-audit-log-helper.test.ts
src/jira/client/jira-client-audit-log-helper.ts
src/jira/client/jira-client.test.ts
src/jira/client/jira-client.ts

Allow multi builds in audit log during backfill
Some typings.
**Why**
Polli test needs it
[arc-2643]
Unit test

ARC-2643 allow multi workflow entries in audit log during backfill

---

.eslintrc.json
src/github/client/github-installation-client.ts
src/models/axios-error-event-decorator.ts
src/models/octokit-error.ts
src/routes/api/client-key/recover-client-key.ts
src/routes/api/db-migrations/db-migration-down.ts
src/routes/api/db-migrations/db-migration-up.ts
src/routes/api/db-migrations/db-migration-utils.ts
src/routes/github/github-oauth.ts
src/sync/code-scanning-alerts.ts
src/sync/dependabot-alerts.ts
src/sync/secret-scanning-alerts.ts
test/e2e/setup.ts
test/e2e/utils/github.ts

Lint
**Why**
Lint
Nope
NONE
tests
lint

NONE: Reenable lint rule

---

etc/poco/bundle/extras-prod-test.json
etc/poco/bundle/extras-prod.json

ARC-2688 set poco for new backfill prod test
**Why**
token header
ARC-2688
local

ARC-2688 set poco for new backfill prod test

---

.eslintrc.json
src/config/env.ts
src/config/statsd.ts
src/rest/middleware/error/index.ts
src/services/micros/lifecycle.ts
src/services/user-config-service.ts
test/setup/matchers/to-be-called-with-delay.ts

Lint
**Why**
Lint
Nope
NONE
tests
lint

NONE: Re-enable lint rules

---

etc/poco/bundle/extras-prod-test.json
etc/poco/bundle/extras-prod.json

Update poco policy fr GHE basic critical pollinator test

chore: update poco policy fr ghe basic critical polli test

---

.eslintrc.json
src/middleware/frontend-log-middleware.test.ts
src/middleware/frontend-log-middleware.ts
src/middleware/github-webhook-middleware.ts
src/middleware/jira-symmetric-jwt-middleware.test.ts
src/middleware/jira-symmetric-jwt-middleware.ts
src/routes/jira/atlassian-connect/jira-atlassian-connect-get.ts
src/sqs/backfill-discovery.test.ts
src/sqs/backfill-error-handler.test.ts
src/sqs/branch.ts
src/sqs/deployment.ts
src/sqs/error-handlers.ts
src/sqs/push.ts
src/sqs/sqs.test.ts
src/sqs/sqs.ts

lint
**Why**
lint
Nope
NONE
tests
lint

NONE: Re-enable more lint rules

---

spa/src/services/oauth-manager/test.ts

- Fixing lint for one of the test cases under spa
**Why**
- This comes up in everyone one of my other PRs in progress.

Lint fixing

---

etc/poco/bundle/extras-prod-test.json
etc/poco/bundle/extras-prod.json

add missing poco policy for audit log

Arc 2643 poco policy update

---

.github/workflows/on-push.yml
Dockerfile
package.json
spa/yarn.lock
yarn.lock

Convert atlassian.com package source to yarnpk
**Why**
It is returning 401 lately.
N/A
N/A
N/A
N/A

NONE convert atlassian.com package source to yarnpk

---

src/github/client/app-token-holder.ts
src/github/client/auth-token.ts
src/github/client/installation-token-cache.test.ts
src/github/client/token-cache.test.ts

Decrease token TTL to 1 minute
**Why**
Customers are complaining

ARC-2745: decrease TTL of the token
