- lib/frontend/get-jira-configuration.js
- static/js/jira-configuration.js
- views/jira-configuration.hbs
This allows the iframe to remain a heroku URL while ensuring that when we send users to a GitHub specific page, it will show the official GitHub URL.
> Open public url from within iframe

- package-lock.json
- package.json
This is a temporary fix to avoid the memory leak issues we're seeing with 2.10.0. See https://github.com/SGrondin/bottleneck/issues/95#issuecomment-442488867 for more details
> Pin bottleneck to 2.9.0

- lib/sync/installation.js
- lib/transforms/smart-commit.js
- test/unit/smart-commit.test.js
The regex we were using to parse Issue Keys is getting false positives against commit messages and PR titles that have an underscore in them.
**Example:**
`JSP_JIR-123` currently matches, but `JSP_JIR` is not a valid identifier according to the devinfo API. I looked through the logs from sync jobs that were getting this error and none of them looked like valid Jira issue keys.
To verify, I tried creating an issue key with underscores, but Jira will not allow this:
This PR prevents the integration from matching on those keys. In addition, it will no longer throw when it encounters a bad request. Instead, it will just log an error and continue on to the next page of results. This will allow the sync to continue while allowing for further diagnostics.
> Updates to address sync getting stuck due to invalid issue keys

- lib/sync/transforms/pull-request.js
- lib/worker/index.js
- test/unit/sync/transforms/pull-request.test.js
In the REST API, we return the [Ghost User](https://github.com/ghost) when a user that's an author of a PR deletes their account. In GraphQL we handle this by returning `null`, which is causing syncs of Pull Requests to fail since we expect properties to be returned on the `avatar` object. The Devinfo API [requires at least an author name](https://github.com/integrations/jira/blob/053cc76af05ea045d964b7fd1634473534aa9bb1/docs/jira-dev-info-0.10-swagger.yaml#L395-L398) to be sent over with the PR object, so this will just return the ghost user info when GraphQL returns `null` for author.
> Handle deleted users that were authors of a PR

- lib/jira/util/index.js
- package-lock.json
- package.json
- test/fixtures/text/existing-reference-link.rendered.md
- test/fixtures/text/existing-reference-link.source.md
- test/fixtures/text/multiple-links.rendered.md
- test/fixtures/text/multiple-links.source.md
- test/fixtures/text/previously-referenced.rendered.md
- test/fixtures/text/previously-referenced.source.md
- test/fixtures/text/valid-and-invalid-issues.rendered.md
- test/fixtures/text/valid-and-invalid-issues.source.md
- test/safe/issue-comment.test.js
- test/safe/issue.test.js
- test/safe/pull-request.test.js
- test/unit/jira/util.test.js
Leveraging [reference links] instead of inline - `[text](link)` - syntax to prevent the issues reported in #159 & #141.
Closes #161 
Closes #159 
Closes #141
| 🎩 | @tcbyrd |
| :--- | :--- |
| 📎 | @returnlytom |
[reference links]: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links
> De-duping issue links w/ reference syntax

- README.md
- SUPPORT.md
This pull request updates the `SUPPORT.md` file with troubleshooting steps for the most commonly seen problems so far.
This change should help in a few ways:
1. Quick self-service for people to help themselves
2. Documentation that the support team at GitHub can reference
The `README.md` file has been updated to link people to the `SUPPORT.md` file instead of linking directly to the GitHub Support contact form.
> Update the SUPPORT file with troubleshooting steps

- lib/transforms/pull-request.js
- test/fixtures/pull-request-basic.json
- test/safe/pull-request.test.js
Have into account also the branch name since GitHub sometimes humanizes the PR title based on the branch name by default and the issue key is lost that way. So, using the branch name should keep that issue key reference.
cc https://github.com/github/ecosystem-primitives/issues/145
> Find issue keys in branch names when opening PRs

- lib/worker/index.js
The jobs in these queues were migrated and processed in the `installation` queue and no new jobs are stored in there. So we don't need to keep them in the code.
> Delete old queues

- db/config.json
- lib/models/index.js
cc https://github.com/github/ecosystem-primitives/issues/139
In order to reduce the volume of logs this PR disables logging SQL queries in production.
We've done the same in the Slack integration https://github.com/integrations/slack/pull/803
> Reduce production logging

- lib/jira/client/axios.js
Specify a timeout for the requests to JIRA to prevent us timing out and not even being able to show a custom error page to the user.
Axios by default doesn't have a timeout https://github.com/axios/axios
> Jira timeout

- lib/github/pull-request.js
- lib/jira/client/index.js
- lib/sync/transforms/pull-request.js
- test/fixtures/pull-request-remove-keys.json
- test/fixtures/pull-request-test-changes-with-branch.json
- test/safe/pull-request.test.js
On Pull Requests, a user can freely edit the title to contain issue keys ore remove them. Right now if you update the Issue Key, the Jira API will automatically move the PR from one issue to another. But if you remove all issue keys, we stop processing the payload since it doesn't contain smart commit data. This PR adds a feature that will delete the Pull Request from Jira if you remove the issue key from the title by parsing the `payload.changes` hash, which contains the title that the PR was changed _from_. We don't need to know the issue keys to delete it from Jira. We just tell the Jira API to delete the reference to the Pull Request.
> Feature: Handle payloads where issue keys are removed

- lib/jira/connect.js
First step listed in https://developer.atlassian.com/blog/2019/02/app-opt-in-api-migration/ is to signal we'll be testing our app for GDPR compliant API migration by setting `gdpr: false`. This adds that descriptor.
> Add GDPR flag to connect descriptor

- SUPPORT.md
- lib/api/index.js
- lib/frontend/retry-sync.js
- lib/models/subscription.js
- static/css/styles.css
- static/js/jira-configuration.js
- test/unit/api/__snapshots__/api.test.js.snap
- test/unit/api/api.test.js
- views/jira-configuration.hbs
This adds an option through the UI and the staff API to allow a full resync. The way the sync works today, it will not rescan your entire installation if for example you add or removed repositories while the sync is in progress. This works fine if you add or remove a repository from the installation after the sync is complete, but a few users have realized they installed very large repositories and then removed them while the sync was in progress. This left the `repoSyncState` in a state where it is trying to sync repositories that it can no longer access. If this happens, the user needs a way to restart the sync from the beginning so we can clear out the state of any repositories that the sync can no longer access.
This also changes the API call to `repoSyncState` to require you to pass …
> Add Full resync option

- CONTRIBUTING.md
While going through the `CONTRIBUTING.md` file for [Configuring the Jira instace](https://github.com/integrations/jira/blob/master/CONTRIBUTING.md#configuring-the-jira-instance), I noticed there is a slight change of wording from `Add-ons` to `Apps`. Additionally the UI for enabling developer mode has changed very slightly.
This PR updates this wording. 👍 
/cc @tcbyrd I don't think this is anything that needs an immediate ship, but would be useful as others begin to look at contributing to the repo.
> Update `CONTRIBUTING` steps to reflect current Jira Cloud UI

- README.md
This PR updates the README.md file implementing a grammatical correction in the documentation for Smart Commits:
```diff
- Smart commits are documented on the Atlassian site and allow **to you** comment on Jira issue in commit messages, branches, and pull requests. For example: `[JRA-123] fix typo` will be sent through to Jira and appear in the Development Information section of the Jira issue with the key `JRA-123`
+ Smart commits are documented on the Atlassian site and allow **you to** comment on Jira issue in commit messages, branches, and pull requests. For example: `[JRA-123] fix typo` will be sent through to Jira and appear in the Development Information section of the Jira issue with the key `JRA-123`
```
> README.md: implement grammatical correction

- lib/sync/commits.js
- lib/sync/queries.js
- lib/sync/transforms/branch.js
- test/fixtures/api/graphql/branch-associated-pr-has-keys.json
- test/fixtures/api/graphql/branch-commits-have-keys.json
- test/fixtures/api/graphql/branch-empty-nodes.json
- test/fixtures/api/graphql/branch-no-issue-keys.json
- test/fixtures/api/graphql/branch-queries.js
- test/fixtures/api/graphql/branch-ref-nodes.json
- test/fixtures/api/graphql/commit-queries.js
- test/fixtures/api/graphql/default-branch.json
- test/unit/sync/branch.test.js
- test/unit/sync/commits.test.js
- test/unit/sync/pull-requests.test.js
It looks like there's a lot going on in this PR, but a lot of it is just beefing up our tests to make sure we're catching edge cases like this. The core of what I'm proposing here is in the `mapBranch` function:
https://github.com/integrations/jira/blob/5dd752f5dd270887bb084b70ab0c7438333c211e/lib/sync/transforms/branch.js#L4-L39
The goal of this PR is to map more data to the DevInfo API in Jira during the initial sync. Currently, if the branch doesn't have an issue key in it, we stop processing that branch. What users expect is for any commit with an issue key to also make that branch show up in the DevInfo panel. This is how it works for new data, but during the initial sync we were filtering out branches if the name of the branch didn't look like it needed to sync.
The function above …
> Sync more data from branches

- README.md
The previous link pointed at the Fish Eye article, which included some irrelevant information and omitted a few valuable bits.
Fixes #207
> Update Smart Commits link to point to JIRA doc

- package-lock.json
- package.json
After shipping #222 it looks like a number of errors are related to trying to send data to NewRelic. This bumps to latest newrelic dependency in an attempt to quiet those alerts.
> Update newrelic to latest minor release

- .gitignore
`.DS_Store` files are created by Finder in macOS and aren't useful when committed. I've started to pipe output to `logs/*` for reference later and so I'm ignoring it as well.
> Ignore .DS_Store and logs/*

- db/migrations/20190807230019-add-indexes.js
This adds two indexes for the Subscriptions table. One for `githubInstallationId` and `jiraHost`, and another for just `gitHubInstallationId`.
> Add indexes for subscriptions transactions

- db/migrations/20190807234327-add-indexes-on-projects.js
**tl;dr** Execution time dropped from 85ms to ~0.1ms.
This index should dramatically improve a query that takes 21% of the total database time.
```
total_exec_time | prop_exec_time |  ncalls   |  sync_io_time   |                                                                                                                                         query
-----------------+----------------+-----------+-----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
03:39:55.74488  | 52.7%          | 2,710,622 | 00:00:00.085608 | SELECT "id", …
```
> Add index on Projects

- lib/api/index.js
- lib/jira/enable.js
- lib/jira/verify-installation.js
- lib/models/installation.js
This aims to fix [`Cannot destructure property jiraHost of 'undefined' or 'null'.`](https://sentry.io/organizations/github-integrations/issues/1143967447)
The [installation flow](https://developer.atlassian.com/cloud/jira/platform/authentication-for-apps/) for an [Jira Cloud app](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/) (like this codebase) has two steps:
1. **Install**. Atlassian makes an unauthenticated request to us, providing a shared secret. We store the secret in the database. The secret can't be used until step two.
2. **Enable**. Atlassian makes an authenticated request using the shared secret. We then make an authenticated request to their API. If we are successful, we mark the installation as enabled.
We have more than [30 …
> Improve installation verification

- lib/jira/disable.js
- lib/jira/uninstall.js
- lib/jira/verify-installation.js
We received an uninstall request from Jira and it appears to have disabled an installation that was still working.
Unfortunately, we can’t be certain of this because the logs don’t include the installation ID. This updates `uninstall.js` to ensure that, should we see this again, we will have confirmation of the problem. As a precautionary measure, I’ve also added installation ID to other log messages.
> Add installation ID to log message

- .env.example
- Brewfile
- CONTRIBUTING.md
- Procfile.dev
- lib/jira/disable.js
- lib/jira/uninstall.js
- lib/jira/verify-installation.js
- lib/run.js
- package.json
- script/server
- script/tunnel
- script/utils.sh
Mirroring the monolith, you can now start the app with a single command:
```
script/server
```
This sets up a tunnel using ngrok or localtunnel, starts a web server, and starts a worker. Both the web and worker will restart upon file changes.
In order to handle the tunnel, I’ve added `TUNNEL_PORT` and `TUNNEL_SUBDOMAIN` to `.env.example`. Once set, these values will be used to open a tunnel using a consistent subdomain.
While ngrok provides the best experience, I have included support for localtunnel because it is free. Even if you can’t buy an ngrok license, you can setup the app locally.
> Add script/server

- lib/error-handler.js
This will allow us to send production and staging to a single project on Sentry.
> Set Sentry environment to NODE_ENV

- bin/worker
- lib/run.js
If set, `SENTRY_ENV` will be used as the environment when errors are sent to Sentry over `NODE_ENV`. This change is necessary because `NODE_ENV=production` in our staging environment. This is to make it as production-like as possible. However, in this one way, we want staging to be different.
Prior to this, we got aroudn this by using separate Sentry projects for production and staging. This worked but required developers to know about and look at two projects. Sentry has good support for multiple environments per project and so this change aligns us better with how Sentry is designed to be used.
> Allow Sentry environment to be set

- lib/frontend/get-github-configuration.js
This is a small tweak to improve the exceptions sent to Sentry.
The first case gives a better idea to the investigating developer. The second case ensures the original exception is sent on to Sentry, including any specifics returned by the GitHub API.
These are minor changes but every bit helps.
> Throw more specific exceptions

- SUPPORT.md
- lib/frontend/get-jira-configuration.js
- lib/models/subscription.js
- package-lock.json
- package.json
- views/jira-configuration.hbs
When an active sync has not been updated in the last fifteen minutes, assume something went wrong and mark it as staled. We make a best effort to mark syncs that have failed due to an error as “FAILED” but there are cases where the error handler doesn’t run.
While we work to resolve these issues, the customer shouldn’t need to wait 48 hours before knowing something isn’t working as it should. This helps avoid that.
> Add STALLED sync status

- lib/sync/installation.js
- lib/worker/index.js
- test/setup/create-job.js
- test/unit/sync/branch.test.js
- test/unit/sync/commits.test.js
- test/unit/sync/pull-requests.test.js
Even though we see errors as they happen, we don't always have the context we need to diagnose and correct the issues. For example, we often don't know **what** was being done to trigger the error or **who** did it.
We have some information for the installation queue but nothing for pull requests. Further, because Sentry doesn't support Bull out-of-the-box, our existing strategy for capturing metadata may cause data to leak between jobs.
This improves on the existing code in a few ways:
1. Errors from all queues will now included job metadata, including job ID to tie it back the logs.
2. Errors from all queues will be searchable by `jiraHost` or `queue`.
3. Errors while updating Jira will included additional request and response data.
4. Error state will be isolated to each job.
5. …
> Add additional context to exceptions during jobs

- lib/configure-robot.js
- lib/github/middleware.js
- lib/sync/installation.js
- lib/worker/index.js
- test/setup/create-job.js
- test/unit/sync/branch.test.js
- test/unit/sync/commits.test.js
- test/unit/sync/pull-requests.test.js
**Note:** This branches from https://github.com/integrations/jira/pull/242. For review, start at https://github.com/integrations/jira/pull/244/commits/31caab858499422a5134c95b63f175cf9f4a1391.
Prior to this change, the error reporting for webhooks delivered by GitHub and handled by Probot had some shortcomings.
- **The user was identified by IP**, which pointed back to whatever server delivered the webhook. This isn’t meaningful information and made it difficult to tell who was impacted by the error.
- **Errors weren’t searchable.** Related to the first point, the errors had no meaningful tags to search against. I couldn’t filter errors by the type of webhook, the related Jira host, or the GitHub installation. Instead, errors were mixed together so long as the exception message looked the …
>  Improve error handling for webhooks

- lib/jira/client/index.js
- lib/sync/installation.js
- test/unit/sync/branch.test.js
- test/unit/sync/commits.test.js
- test/unit/sync/pull-requests.test.js
Closes https://github.com/integrations/jira/issues/192
This will ensure transitions are not called during initial sync. I've done this by changing the Jira client to allow a second parameter, which defaults to `false` (the original value), while passing `true` into the one call site where we send all payloads to a Jira instance during the initial sync jobs.
> Prevent transitions during initial sync

- .vscode/launch.json
- package.json
Prior to this commit, I used these steps to debug in VS Code:
1. Add breakpoint
2. Stop server
3. Remove the “web” line from `Procfile.dev`
4. Run `script/server`
5. In VS Code Debugger sidebar, click “Start debugging” (the play icon)
Once I finished debugging, I needed to revert `Procfile.dev` and restart the server. This worked but was a pain. I found myself wishing for something as easy as a browser.
This commit reduces those steps to one: click “Start Debugging” in VS Code.
This is enabled by two changes: the web server is always started with `--inspect` and `.vs_code/launch.json` tells VS Code to look for a running debugger and attach instead of trying to start a server itself. If you want to debug the worker instead of the web process, select “Attach to worker” from the debugger …
> Make debugging in VS Code easy

- bin/stafftools
- lib/api/index.js
- lib/models/installation.js
- lib/models/jira-client.js
- test/models/jira-client.test.js
**This builds on https://github.com/integrations/jira/pull/253.**
This allows a staff member to check the authorization status of a specific Jira installation.
```bash
$ bin/stafftools jira 682b4a8f798a480a99e51b04936332a2
{
"clientKey": "682b4a8f798a480a99e51b04936332a2",
"host": "https://example.atlassian.net",
"enabled": true,
"authorized": true, # <-- Important bit
"gitHubInstallations": [
{
"gitHubInstallationId": 1234,
"createdAt": "2019-08-26T19:49:41.023Z",
"updatedAt": "2019-08-26T20:02:33.515Z",
"syncStatus": “ACTIVE”
}
]
}
```
This is being added to help diagnose exceptions. We see a number of 403s but aren't able to test the customer's Jira credentials to determine if they are always invalid or only in certain contexts.
As part of this, I’ve introduced a new class, called …
> Add stafftools to test Jira authorization

- bin/stafftools
This endpoint allows us to manually mark a Jira installation as migrated with a successful sync. This is useful when a customer’s sync has sent all data to Jira but failed to tell Jira the migration was complete.
> Add “migrate” to stafftools

- lib/github/middleware.js
- test/unit/github/middleware.test.js
A customer can connect multiple Jira instances to a GitHub organization. When they do so, GitHub delivers the event as a webhook that we process and fan out to each Jira instance.
If something goes wrong while processing the event for one of the Jira instances, like an HTTP error, we stop processing and throw an error. This can result in events being lost.
To avoid this, we process each event within a `try … catch`. If something goes wrong, we send it to Sentry and continue processing.
> Continue processing webhooks when error occurs

- lib/jira/client/axios.js
- lib/jira/client/index.js
- lib/jira/client/jira-client-error.js
- lib/sync/installation.js
- package-lock.json
It’s usually not possible to trace an error back to it’s cause using Sentry. **If we don’t know how something happened, it’s difficult to fix it.**
Right now, the majority of our errors occur while making requests to Jira. When reported, the errors are grouped by stacktrace. Unfortunately, the stacktraces aren't helpful. For example:
```
Error: Request failed with status code 400
File "/app/node_modules/axios/lib/core/createError.js", line 16, col 15, in createError
var error = new Error(message);
File "/app/node_modules/axios/lib/core/settle.js", line 18, col 12, in settle
reject(createError(
File "/app/node_modules/axios/lib/adapters/http.js", line 201, col 11, in IncomingMessage.handleStreamEnd
settle(resolve, reject, response);
File "events.js", line 214, col 15, in …
```
> Make the source of Jira errors more obvious

- bin/stafftools
- lib/api/index.js
- lib/jira/uninstall.js
- lib/models/installation.js
We recently discovered a number of Jira installations that had lost the ability to authenticate to the Jira API. This renders them quite useless. Each time we process a webhook for one of these installations, an error is thrown.
A investigation found more than 150 such instances. While it’s not clear how they ended up in that state, it is likely prudent to clean them up. This commit adds the ability to do so using `bin/stafftools`.
```
$ bin/stafftools help jira-uninstall
Usage:
stafftools jira-uninstall <client_key>
Options:
[--force]                # Force uninstall for an authorized Jira installation
[--token=TOKEN]          # Personal access token (defaults to GITHUB_TOKEN)
[--host=HOST]            # Jira integration host (useful to test against staging or development)
[--debug], …
```
> Add ability to uninstall Jira installation via stafftools

- bin/stafftools
This simplifies setup for new developers and support agents and keeps secrets out of local environment variables.
This is a follow-up to comments on https://github.com/integrations/jira/pull/253.
> Add setup wizard to bin/stafftools

- db/migrations/20190828145758-add-sync-warning-column-on-subscriptions.js
- lib/frontend/get-jira-configuration.js
- lib/jira/client/index.js
- lib/models/subscription.js
- static/css/styles.css
- views/jira-configuration.hbs
This PR limits the issue keys referenced from a commit or branch to the first 100. In #250 we started deduplicating the issue keys and throwing an error if there were more than 100. Instead of throwing an error, now we truncate the list of issue keys and display a warning to the user after the sync is complete.
> Truncate issue keys and show warning to user

- lib/api/index.js
- lib/frontend/app.js
- lib/frontend/delete-github-subscription.js
- lib/frontend/delete-jira-configuration.js
- lib/frontend/get-github-configuration.js
- lib/frontend/retry-sync.js
- lib/frontend/verify-jira-middleware.js
- lib/github/middleware.js
- lib/jira/client/axios.js
- lib/jira/client/index.js
- lib/jira/index.js
- lib/jira/verify-installation.js
- lib/middleware/log-middleware.js
- lib/models/jira-client.js
- lib/models/subscription.js
- lib/sync/installation.js
- lib/transforms/push.js
- test/models/jira-client.test.js
- test/unit/api/api.test.js
- test/unit/frontend/verify-jira-middleware.test.js
- test/unit/github/middleware.test.js
This commit aims to improve the quality of log messages sent to Loggly in a few ways:
1. Adds `jiraHost` and `jiraClientKey` to logs on _most_ web requests (background jobs coming next)
2. Adds `req.addLogFields`, which allows additiona fields to be added
3. Converts some `console.log` calls to `req.log`
This is a first step towards addressing https://github.com/integrations/jira/issues/247. As an example of how this can help increase visibility, here's a log of someone requesting a sync retry before:
```
14:57:29.368Z  INFO http: POST /jira/sync 202 - 99.35 ms (id=4a0c79e0-079b-4b2f-831d-947c9b450352)
-- becomes -- (scroll) -->
14:55:30.741Z  INFO http: POST /jira/sync 202 - 52.39 ms (id=17b390bc-1a70-433c-9218-9ac5142ae003, jiraHost=https://jnraine.atlassian.net …
```
> Improve logging

- lib/api/index.js
There is a safety in place to avoid accidentally uninstalling an authorized Jira installation.
```javascript
// $ bin/stafftools jira-uninstall 347a4493812968d2c7e674f4d220837b26a9b9b5c0eae709ea5a378ce179938f
{
"status": "HTTP/1.1 400 Bad Request\r\n",
"body": "{\"message\":\"Refusing to uninstall authorized Jira installation\"}"
}
```
However, a bug causes this warning to **always** occur.
When making the request to test the Jira API shared secret, we don’t `await` the promise. This causes `jiraClient.isAuthorized()` to return a promise, which evaluates as a truthy value.
To avoid this, let’s `await` the promise. This ensures the authorization request is run before we proceed with the if statement.
> Wait for authorization check

- lib/github/middleware.js
There is a Jira installation with a repository that sees 100 push events per hour. Each push event contains 1,000 commits. Right now, this causes an enormous number of GitHub API requests, quickly resulting in rate limit errors.
To stop these errors and keep the Jira integration from wasting time processing these requests, I’ve hard coded the repo ID and ignored it.
**This is a temporary measure.** We’ll reach out to the customer and resolve it ASAP.
> Ignore webhooks from known baddie

- SUPPORT.md
Add a small section about the warning message we show when we process a commit or branch that has more than 100 issue keys. This describes the behavior implemented in https://github.com/integrations/jira/pull/258#issuecomment-526606109
@ACyphus Not sure if we want to a picture or GIF of the actual warning message that is shown since there aren't any other images in the docs
> Add support section for referencing too many issue keys

- lib/frontend/github-client-middleware.js
- lib/github/middleware.js
- lib/models/octokit-error.js
- lib/models/sentry-scope-proxy.js
- lib/sync/discovery.js
- lib/sync/installation.js
- lib/transforms/push.js
- lib/worker/index.js
- test/models/octokit-error.test.js
- test/models/sentry-scrope-proxy.test.js
- test/unit/github/middleware.test.js
When a request from Octokit to the GitHub API fails, this wraps the error, adding additional context and ensuring the grouping is more meaningful.
```
HttpError: {“message":"API rate limit exceeded for installation ID 1339471.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```
becomes
```
OctokitError: PATCH /repos/:owner/:repo/issues/:number responded with 403
```
The response from GitHub—`API rate limit exceeded…`—is available in full under the `response.body` metadata. The GitHub request ID can be found under `response.headers` metadata.
Errors are also now grouped by method, path, and response code. This should ensure better grouping in Sentry.
> Supercharge Octokit request errors

- lib/sync/installation.js
- lib/sync/queries.js
- test/fixtures/api/graphql/commit-queries.js
- test/fixtures/api/graphql/pull-queries.js
Reduces the initial page size for the branch query to 20. We have a hunch that the subsequent page sizes do not actually get tried when the request times out since the page limit of 50 does not exceed the node limit ("MAX_NODE_LIMIT_EXCEEDED").
I'll follow up on this PR with more info about the error handling for smaller page sizes after I get a chance to debug later today / tomorrow.
https://github.com/integrations/jira/blob/3a6a26dd2c89d73a028cab7b710e88687ea5a020/lib/sync/installation.js#L114
> Reduce page limit on branch query

- lib/config/enhance-octokit.js
- lib/config/statsd.js
- lib/github/middleware.js
- lib/sync/discovery.js
- lib/sync/installation.js
- lib/transforms/push.js
- package-lock.json
- package.json
- script/datadog-spy
- test/setup/index.js
- test/setup/matchers/to-have-sent-metrics.js
- test/unit/config/enhance-octokit.test.js
When a request is made to the GitHub API using Octokit, a timing histogram is sent to localhost:8125 over UDP. The value of the metric is the elapsed time of the request. Because we’re using a histogram, Datadog will turn this into six different metrics: `count`, `avg`, `median`, `95percentile`, `max`, `min`. For more information on Datadog histograms, see https://docs.datadoghq.com/developers/metrics/histograms/.
This metric will help us measure our interactions with the GitHub API to address timeout issues, monitor usage, and optimize GraphQL queries.
To test this out locally:
1. Start the server
2. In a new tab run `script/datadog-spy`
3. Trigger a sync
You should see metrics printed in the second tab.
Note: Because we don’t have a Datadog agent running on production, _these won't go …
> Add Datadog histogram for GitHub requests

- lib/config/enhance-octokit.js
- lib/config/statsd.js
- test/setup/log-double.js
- test/unit/config/enhance-octokit.test.js
Four small things:
- Send `method` and `status` tags to Datadog (e.g., `method:GET` and  `status:200`)
- Add `method`, `path`, and `status` to log message (plus add tests)
- Remove unnecessary `dyno` global tag.
Some sample metrics:
```
github-request:647|h|#path:/installation/repositories,method:GET,status:200
github-request:704|h|#path:/graphql,method:POST,status:200
github-request:528|h|#path:/repos/_owner/_repo/issues/_number,method:PATCH,status:200
```
See commit messages for specifics.
> Grab bag of small GitHub API metric improvements

- lib/config/enhance-octokit.js
- lib/jira/client/axios.js
- lib/jira/client/index.js
- test/setup/matchers/to-have-sent-metrics.js
- test/unit/jira/client/axios.test.js
Yesterday, we connected production to Datadog and started seeing metrics! 🎉 Unfortunately, we quickly realized that there were far too many values being sent for the `path` tag. 😞 
To avoid this, I've modified the Jira Axios client to always use Express.js-like route parameters to interpolate user data into paths and to remove URL query parameters. This should reduce the total number of `path` values we send to Datadog and save us 💰.
✨ Props to @jules2689 for [warning of this problem](https://github.com/integrations/jira/pull/269#pullrequestreview-286245560) before it happened!
> Reduce cardinality of path tag

- lib/sync/installation.js
**Problem:** If a user deletes a repo after starting a long-running sync the entire sync will fail.
**Context:** The repo sync state column is populated at the beginning of the sync in the discovery queue. If the sync runs over multiple days, a user can delete a repo that was initially in the sync state column. This causes the entire sync to fail since the sync job hits a `NOT_FOUND` error from GitHub when it tries to process that repo's sync state.
**Fix:** If the repo no longer exists, we should just be able to swallow the error and not fail the sync.
> Swallow repo NOT_FOUND error during Initial Sync

- lib/sync/commits.js
- lib/sync/installation.js
Follow up fix for #274 
After triggering the sync for the customer that was experiencing this error I realized that `updateJobStatus` isn't called in the `catch` block so the next jobs weren't getting queued after swallowing the error.
This fix also led me to find that we were swallowing all errors for the `commit` sync task leading to the `NOT_FOUND` GraphQL error not being raised. This PR removes the `try` block that was added allowing us to catch the error when running the job in `installation.js`.
Ultimately, I think both of these errors could have been caught with stronger test coverage around the initial sync process as @jnraine and I have discussed. Will work on getting that in over the next few PRs.
> Follow up fix for NOT_FOUND during sync

- lib/worker/index.js
- test/unit/jira/client/axios.test.js
The background job library we use doesn’t consistently remove completed jobs from Redis. On production, this led to unbounded memory growth.
While the [Bull reference guide] doesn’t specifically mention the need to manual clean old data, the library prov ides [`Queue#clean`]. Prior to this commit, we manually cleaned the queues by running `bin/clean-old-jobs`. ~To ensure we clean on a regular basis and to minimze chores, **old jobs are now cleaned on start up.**~ To decouple clean up from restarting the workers, old jobs will be cleaned up using the [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler). (Hat tip: @jules2689)
Cleaning has also been limited to 50,000 jobs at a time. Doing too many at once can overload Redis. The specific number is a guess based on past …
> Clean up failed and completed jobs on start

- bin/send-sync-status-metrics
- lib/models/subscription.js
- test/unit/config/enhance-octokit.test.js
- test/unit/jira/client/axios.test.js
Every n minutes<sup>1</sup>, send over the count of sync statuses to Datdog. In other words, we want this query available as a Datadog metric:
```
psql> SELECT "syncStatus", COUNT(*) FROM "Subscriptions" GROUP BY "syncStatus";
syncStatus | count
------------+-------
| 5
PENDING    | 1
COMPLETE   | 100
ACTIVE     | 10
FAILED     | 5
(5 rows)
```
This adds `bin/send-sync-status-metrics` that runs the above query and sends it along to Datadog under the `jira_integration.syncs` metric.
```
jira_integration.syncs:5|g|#status:
jira_integration.syncs:1|g|#status:PENDING
jira_integration.syncs:100|g|#status:COMPLETE
jira_integration.syncs:10|g|#status:ACTIVE
jira_integration.syncs:5|g|#status:FAILED
```
This will allow us to track syncs over time and proactively track the health of syncs. My hope …
> Send sync status metrics to Datadog

- lib/sync/installation.js
- lib/worker/index.js
Customers were reporting syncs switching from `COMPLETE` to `FAILED` without triggering a sync themselves. The underlying problem was with how and when we marked syncs as failed.
Syncs occur in the background on the `installation` queue.  When a sync background job throws an error, a global failure handler is called that updates `subscription.syncStatus` to `FAILED`. However, this global failure handler runs when _other_ jobs fail too.
This led to a sync being marked as `FAILED` when any job for that customer failed.
This commit avoids that by moving the `subscription.syncStatus` update out of the global failure handler and into the sync job.
> Only mark sync as failed during sync

- bin/send-sync-status-metrics
- bin/worker
- lib/config/sentry.js
- lib/run.js
[Suggested by @zmoazeni], this ensures the know-how for initializing Sentry lives in one place. This makes it easy to modify how we initialize Sentry and will come in handy when it comes to add some global event handlers.
[Suggested by @zmoazeni]: https://github.com/integrations/jira/pull/279#discussion_r327363717
> Extract `Sentry.init` into method and call that

- lib/jira/client/axios.js
When an error is thrown while making a request with to the Jira API, there’s a good chance the error has a response attached to it. However, that’s not always the case.
Because the instrumentation relies on the response property, we now only call `instrumentRequest` when it is present.
This issue was raised because we saw a number of `Cannot read property 'config' of undefined` errors.
It’s not immediately obvious to me how to add an automated test to trigger this case. If you can think of one, please let me know.
> Instrument response only when present

- bin/stafftools
- lib/api/index.js
- lib/api/serializers.js
- lib/models/subscription.js
This makes two improvements to the stafftools:
- Allow Jira installation lookups by host (https://github.com/integrations/jira/commit/608f62126b196c28efff51da2036e72b3870a795)
- Add ability to resume last `n` failed syncs (https://github.com/integrations/jira/commit/e3396027b1ef20893627f5d42ca884c35c95b10a)
See commits for full details.
> Improve stafftools

- bin/send-sync-status-metrics
- lib/worker/index.js
- lib/worker/metrics-job.js
Added in #279, sync status metrics were intended to give greater insight into the overall health of the app. However, due to the way `bin/send-sync-status-metrics` was run using Heroku Scheduler, the metrics never made it to Datadog. [1]
This should remedy the problem by moving the metric sending into a background job. Because we already send metrics from background jobs to Datadog, I’m confident that the metrics will arrive. Heroku Scheduler still plays an important part but is now only repsonsible to enqueue the job.
Note: Bull (the background job library) supports what it calls [“repeated jobs”](https://github.com/OptimalBits/bull#repeated-jobs). However, I had difficulty getting these to work locally.
1: While I haven’t uncovered the cause, my hunch is that the Heroku kills the dyno …
> Fix sync status metrics bug

- bin/stafftools
This opens the browser to Sentry’s discover tab with errors for a given Jira host. Useful when investigating a customer problem.
In order to use, you must have access to the production Sentry instance.
(This codifies a practice I've been using and turns a multiple step process into single command. Since you're probably using `bin/stafftools` to diagnose a customer problem, this makes the hop to Sentry more smooth.)
> Add `bin/stafftools errors`

- lib/sync/installation.js
There are certain GraphQL errors that we want to swallow, like `MAX_NODE_LIMIT_EXCEEDED`. However, sometimes the error object doesn’t contain a list of errors with types. In that case, we want to always throw the error.
> Always throw when error types missing

- lib/smart-commit-tokenizer.js
- test/unit/smart-commit-tokenizer.test.js
A string ending with a [line separator], a whitespace unicode character (everyone’s favourite kind), would result in a syntax error.
This fixes that by matching tokenizing the `workLogComment` using a “not whitespace” regex pattern. This pattern matches any character that isn’t a carriage return, newline, tab, or space. You know, the normal whitespace stuff.
This results in the line separator being included as a work log comment but because we’re currently only extracting the issue keys from the tokenized smart commit, it will have no ill effect.
[line separator]: https://www.fileformat.info/info/unicode/char/2028/index.htm
> Add support for unicode line separator to SmartCommitTokenizer

- package.json
We lost some nodejs metrics graphs, update the build packs and see if that re-enables them.
Fixes https://github.com/github/ecosystem-primitives/issues/485
> Enable Node.js Language Metrics

- db/config.json
- lib/run.js
- package-lock.json
- package.json
We sometimes have huge spikes in request queuing, we only have 5 workers, that may be part of the cause, let's use throng [like we did in slack](https://github.com/integrations/slack-private/pull/29) to add more workers on the same nodes to better utilize our resources.
Heroku will calculate `WEB_CONCURRENCY` for us based on Dyno Ram Size / `WEB_MEMORY` == `WEB_CONCURRENCY`. We can also set it manually (which we will do at first to ensure a no-change rollout at first, see below).
> Use Throng for Probot Concurrency

- .eslintrc.json
- lib/github/middleware.js
- lib/jira/client/index.js
- package.json
- test/unit/jira/client/__snapshots__/index.test.js.snap
- test/unit/jira/client/index.test.js
Exceptions are expensive in nodejs (recovering, capturing the callback, submitting it to sentry, etc). We've seen this exception 55k times, and generally see it 1.1-1.3k times per day: https://sentry.io/organizations/github-integrations/issues/1201310569/events/013891d2c99b4797b1ba91139276cae8/
> Cannot read property 'jiraHost' of null
This is because if a user disables the integration, the `Installation.getForHost` function returns `null`, and then we try to use it anyways.
The simple solution is: If there isn't an installation, exit, we can't process it anyways, so no reason to raise an exception about it.
Since this is a configuration option (the user has configured the system to disable the plugin but also it still receives webhooks), I don't think that sending a metric is warranted, …
> Don't raise an exception if there's no jira client

- bin/worker
- lib/worker/index.js
This PR uses throng to spin up multiple bull workers per dyno. I'll try to explain the reasoning behind why this is a good idea in my opinion!
Previously (before Today) we were using the 1x dyno. The standard-1x has 512MB of ram, 1x cpu "Share", meaning other services from other companies can be running on our host, and cause resource contention. The sharing isn't perfect, and a really "noisy neighbor" can negatively impact the scheduler's ability to give us our fair share of resources.
Additionally, we've seen our CPU load jump to 30 today, along with large amounts of SWAP being used. All this points to us needing faster/dedicated hardware for our app.
The performance m is dedicated (it's all ours) and has 2.5GB of memory and we get all 11x of the compute. When I switched our workers to …
> Use throng for multiple instances per dyno

- bin/worker
Due to a poor variable naming choice, throng was set to the default for `workers`, which is based on the # of CPUs on the host, instead of our choice `WEB_CONCURRENCY`. This is fine in prod because we have a dedicated host, so the # of CPUs is limited to 5 (so we're not going crazy), but in staging we're using a 1x which is on a shared performance-L which has 46 CPUs which is a much different problem!
> Specify # of workers instead of letting throng guess based on CPUs

- package.json
Remove the deprecation warnings like in Slack. It doesn't bring us any value to have these as searchable logs (and logs are very expensive).
/cc https://github.com/integrations/slack-private/pull/46
> Remove deprecation warnings from prod

- .github/CODEOWNERS
- db/migrations/20200206225834-update-views.js
The last time we added fields to the `Subscriptions` table we didn't update the view.
Great question! I'd been wondering this too! Presto.githubapp.com, data.githubapp.com, looker.githubapp.com all use a mysql(ish?) syntax to query all the databases. When you query the Jira database from any of these sources, it connects to the jira read replica and issues a live query!
Now you're asking, why did you mention a "mysql(ish) syntax":
So, postgres is case sensitive, and that query language is decidedly *not*. To get around this, every postgres database that wants to be able to be queried by presto and its friends must create a `VIEW` that maps all the uppercase table names and columns to lower-snake-case.
Another great question (wow you're full of great questions today, dear reader)! In order …
> Update the subscriptions view

- bin/worker
- lib/github/middleware.js
- lib/jira/client/index.js
- lib/run.js
- newrelic.js
@tebriel I'm curious what you think about this approach. This is just adding more segments in newrelic so that our traces like https://rpm.newrelic.com/accounts/205/applications/154434972/transactions#id=5b225765625472616e73616374696f6e2f457870726573736a732f504f53542f2f222c22225d&app_trace_id=821171b1-6cf9-11ea-a8d9-0242ac110009_2716_4351 will have a lot more specific timing detail.
I ran this locally and verified the webhook handlers are working. I'm not using newrelic locally though so I'll test this in staging first.
> Add more new relic tracing

- lib/frontend/index.js
- views/jira-configuration.hbs
Per the [Atlassian Announcement](https://blog.developer.atlassian.com/announcement-reminder-about-deprecation-of-xdm_e-usage-and-needing-to-load-all-js-from-the-cdn/) we can no longer load all.js from the old location (`host/atlassian-connect/all.js`) (host is the integration base for your jira project i.e. https://github-integration.atlassian.net. And instead we must load it from https://connect-cdn.atl-paas.net/all.js. This PR changes this. I have verified that it fails to load in jira right now (https://github-integration.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page) and can re-validate after it's deployed.
Fixes https://github.com/github/ce-extensibility/issues/584
> Change where we source all.js

- lib/github/middleware.js
Some webhook events are printing like `push.undefined` which we don't need.
Others make sense like `pull_request.closed` so lets keep that
> Stop logging undefined actions

- lib/models/octokit-error.js
- test/models/octokit-error.test.js
The hope here is that Sentry lists out both stack traces. I believe I've seen that before
The current issue is that sentry stack traces point to where we wrap the new OctokitError rather than where the error originated:
More information on Sentry hints: https://docs.sentry.io/platforms/node/
> originalException
>
>    The original exception that created the event. This is useful for changing how events are grouped, or to extract additional information.
I believe I've seen this before in Go-land. I think sentry will list both stack traces and this allows us to avoid munging any error's stack trace.
---
I should probably try this out locally and see it happen in Sentry but I feel comfortable enough yolo'ing this and checking the results in production.
> Sets originalException

- lib/github/index.js
- lib/github/middleware.js
- lib/middleware/webhook-timeout.js
- test/middleware/webhook-timeout.test.js
As far as I can tell, we can't kill the request from the outside, but instead we have to cooperatively kill from within the logic. Meaning we need to find and add checks like this wherever we have long running code.
This doesn't currently have any tests. I only tested it locally by adding:
```
function sleep (ms) {
return new Promise((resolve) => {
setTimeout(resolve, ms)
})
}
await sleep(5000)
```
And tweaking the `REQUEST_TIMEOUT_MS` in my .env
> Adds ability for us to timeout webhook handlers

- lib/worker/index.js
We have lots of keys regarding Metrics jobs, this should start purging them.
I'm still planning following up to use `removeOnComplete` separately https://github.com/OptimalBits/bull/issues/840 so this happens automatically
> Also clean metrics queue

- lib/worker/index.js
We no longer need to manually clean these jobs from redis.
I tested this out locally by verifying the keys were trimmed appropriately.
Before I deploy this I will drop the scheduled job in Heroku.
fixes: #280
> Remove jobs from redis by default

- lib/api/index.js
- lib/config/github-api.js
- lib/frontend/github-client-middleware.js
- lib/models/axios-error-event-decorator.js
- lib/sync/commits.js
- package.json
- test/unit/api/__snapshots__/api.test.js.snap
- test/unit/api/api.test.js
- test/unit/config/enhance-octokit.test.js
- test/unit/frontend/github-client-middleware.test.js
- test/unit/github/middleware.test.js
- test/unit/jira/client/axios.test.js
- test/unit/models/index.test.js
We instantiate the `@octokit/rest` `Oktokit` object a **lot**. In addition to that, we aren't using `probot`'s one, which has some nice rate-limiting, retry, and other features built in. This starts the foundation for letting us have a unified feature/config set for those octokit APIs by fetching them from one place. It special cases some configuration for the `test` node environment, but I'm expecting that we'll soon add some profiling to the `throttle` options which will go in here too.
Also fun that was had: the probot octokit auto-retries if a non-200 response was returned. Which made nock very sad because it was like "you told me there'd only be 1 request, but there were 3" and then stuff was failing. This should make the test more consistent.
> Unify GitHub API Invocations

- lib/api/index.js
- lib/jira/connect.js
- test/unit/api/__snapshots__/api.test.js.snap
The repo that we use to check permissions for the private apis changed names. This is a quick-fix but a bigger fix is needed.
(bigger fix needed)
> Quick-Fix permissions

- lib/sync/pull-request.js
- lib/sync/transforms/pull-request.js
- test/unit/sync/pull-requests.test.js
- test/unit/sync/transforms/pull-request.test.js
The graphql endpoint is timing out and it's breaking some customers with very large repos (> 100k pull requests). The rest api is a bit more performant (in local testing) and doesn't error out on large repos like graphql does. This PR rewrites the logic to use the Rest API for listing Pull Requests as a workaround.
> Switch pull request sync flow to rest api

- bin/stafftools
Frequently I find it's not enough to know if a sync is in progress while
debugging, I also often want to know where we are in the process
and how long we have left to go. Also being able to see that things are
changing is helpful to know that a sync is progressing. The new "current"
command shows the cursor for the fetch (if it changes, fetching is
progressing) and the total count of repositories left.
> Add a current command to stafftools

- test/setup/app.js
- test/unit/sync/branch.test.js
- test/unit/sync/commits.test.js
- test/unit/sync/pull-requests.test.js
The old endpoint `/installations/:installation_id/access_tokens` is going away, and will have a brownout soon. Our tests were coded against this old endpoint, but it looks like Octokit saved us and was using the updated endpoint. Because of hte way test/setup/app.js was matching the installations endpoint (using a regex) the tests were still succeeding. We had a lot of tests that included a nock call to the old endpoint, these were never hit. We don't check to make sure all nock calls were fulfilled, so these were just taking up memory.
> Remove unused nock calls and ensure we use proper access_tokens endpoint

- db/config.json
We are bumping our connection pool to 15 due to an incident. 15 seems like the right number because we maxed out at 106 connections in the last 7 days, and our db plan allows us a max of 400.
Our theory is that all of the db connections are being used by background jobs so there might be too much waiting happening.
> Bump connection pool to 15

- lib/config/cidr-validator.js
- lib/configure-robot.js
- lib/run.js
- package-lock.json
- package.json
- test/setup/app.js
- test/unit/config/cidr-validator.test.js
Recently we've been having issues with malicious users scanning looking for random files on the jira application, this causes us to exceed our SLOs and to fail to process a lot of valid requests. This PR adds [express-rate-limiter](https://github.com/nfriedly/express-rate-limit) to try to alleviate those problems.
To avoid rate limiting incoming requests from webhooks, we query the [GitHub Meta Endpoint](https://docs.github.com/en/free-pro-team@latest/rest/reference/meta#get-github-meta-information) to get a list of the current webhook CIDRs. These should not change frequently, so fetching them on startup seems reasonable. Based on our incoming query volume from things other than github webhooks, we do not see anything greater than 5 requests per minute as an average, I've set the max to …
> Use express-rate-limiter for rate limiting

- lib/jira/index.js
Starting yesterday (2020-10-08T13:59:14.144355+00:00) a new error started occuring related to lifecycle events. Specifically the `addLogFields` middleware wasn't included, so these routes started failing. 
Somehow the rate limiting PR seems to have introduced this issue.
Related Sentry Error: 
https://sentry.io/organizations/github-integrations/issues/1944394118/?project=1240711&query=is%3Aunresolved&statsPeriod=24h
> Include logMiddleware to avoid lifecycle event failures

- lib/jira/client/jira-client-error.js
Because Sentry aggregates based on the message field of an error, we shouldn't
have this have a very high cardinality. The details are available in the
"request" and "response" fields in the Sentry Metadata
Example sentry event with request/response data in it https://sentry.io/organizations/github-integrations/issues/1946869803/?project=1240711&query=is%3Aunresolved&statsPeriod=1h
> Use a unified JiraClientError message

- lib/sync/transforms/pull-request.js
- lib/transforms/pull-request.js
- test/unit/sync/pull-requests.test.js
A user noticed that when re-running a full sync, some PRs weren't updated. I believe this is due to a difference between how Webhooks and Full Syncs are handled. Webhooks would concatenate the head ref with the title to find Jira Issue Keys, but the full sync was only using the PR title. This updates them to have the same functionality, note that each is a copy of the other in a comment, and add a test to catch this to try to prevent a regression.
> Check the HEAD ref for Jira IDs when syncing

- .adr-dir
- docs/architecture/decisions/0001-record-architecture-decisions.md
- docs/architecture/decisions/0002-implement-hydro-events-for-activity-tracking.md
Understanding when/why users install/uninstall (or if they didn't initiate but they were uninstalled anyways) their integrations or subscriptions will help us have insight into what is going on with some of the user issues that have come in lately, this ADR (0002) proposes a method for understanding this issue.
> Introduce ADRs and create one for Hydro Events

- lib/config/statsd.js
- lib/proto/v0/action.js
- lib/tracking/index.js
- test/setup/env.js
- test/unit/tracking.test.js
This framework exists to send events to the Hydro HTTP Gateway, using the hmac signed payloads. This does not send the events yet, just builds out the initial framework, protobuf, and tests. A future PR will send the events.
The `TRACKING_DISABLED` env var is set to `true` in staging and prod vault configurations.
> Build out framework for sending hydro events

- package-lock.json
- package.json
- test/unit/frontend/__snapshots__/delete-github-subscription.test.js.snap
**Issue:**
The jest package has a transitive dependency on node-notifier - this could not be resolved directly by Dependabot
Vulnerable versions for node-notifier are `< 8.0.1` and the latest possible version that Dependabot could install is `6.0.0`
More details here: https://github.com/integrations/jira/security/dependabot/package-lock.json/node-notifier/open
**Solution**:
Manually update the jest version version from `^25.4.0` to `^26.6.3`
**Changes in this PR:**
1. Manual update in `package.json` file
2. Auto update in `package-lock.json` file
3. Manual update in the snapshot file `test/unit/frontend/__snapshots__/delete-github-subscription.test.js.snap` after updating the jest version `jest --updateSnapshot`. This update was needed because the snapshot test was failing. 
(Relevant …
> Bump jest version from ^25.4.0 to ^26.6.3

- static/js/jira-configuration.js
Those functions are being called after the organisation is removed, therefore there is no retryBtn, statusBtn, retrySpan or statusSpan to be clicked. This PR simply adds validation to check if those buttons exist before actioning them.
> ARC-40: Fix null errors when removing organisation from app.

- CONTRIBUTING.md
As per the engine specifications in package.json, the app needs to be running on a version of Node 12. Previously we had stated that the app needed to run on `v10.13.0` to work with Postgres but this is now no longer needed. Running on 10.13.0 results in sync failures. Updating to a version of Node 12 resolves the sync status of failed.
> Update CONTRIBUTING.md to specify app is running on Node 12 version

- lib/jira/util/index.js
- package-lock.json
- package.json
- test/fixtures/text/find-existing-references.rendered.md
- test/fixtures/text/find-existing-references.source.md
- test/unit/jira/util.test.js
Resolved markdown vulnerability by removing markdown.js library and adding a block of code to handle pulling issue keys from reference text.
> [ARC-35] security vulnerability in markdown

- test/unit/models/index.test.js
Currently, when you follow CONTRIBUTING.md in Github for Jira and get to the npm test step, one of the tests fail.
Failing test: updates all Subscriptions for a given jira clientKey when a site is renamed in test/unit/models/index.test.js
Fails with:
Expected: "https://renamed-user.atlassian.net"
Received: "https://existing-instance.atlassian.net"
This was happening because we were calling Jest's beforeEach function which executes before every test in the scope. This meant that the renamed url of https://renamed-user.atlassian.net was being reset:
Screen Shot 2021-04-27 at 4 48 55 pm
Changes made so all tests pass:
- only making `truncate` calls from `beforeEach` (to make sure the db is clean before each test is run).
- running the remaining logic from `beforeAll` so it is only executed …
> ARC-36 fix failing test

- .editorconfig
- .eslintrc.json
I was getting annoyed when I was formatting with my IDE, which is defaulted to use tabs instead of spaces, and was breaking eslint rules.  Easiest way to do this is by having a .editorconfig file that specifies indent and space/tabs.  This one is based on the [airbnb javascript .editorconfig](https://github.com/airbnb/javascript/blob/master/.editorconfig) since we're already using their eslint config as well :)
> adding .editorconfig

- lib/models/installation.js
- test/unit/models/index.test.js
This is a secondary (and hopefully final) PR to fix the flaky test in the app. Turns out, we weren't awaiting update in the install method so our super speedy tests were receiving the returned valued for the existing subscription instead of the renamed one.
> ARC-36 add await to installation update

- lib/sync/installation.js
When a user removes an org during an active sync an unhandled error is thrown in the console.
I've added a conditional block to simply log a message to the console when a subscription is `null` and return. All other active syncs continue.
https://user-images.githubusercontent.com/37155488/116833288-cd091e80-abfb-11eb-9daf-326cef6067eb.mov
> ARC-105: add block to handle rejected promise

- lib/frontend/app.js
This change stems from https://github.com/integrations/jira/issues/151.
**Context**
Currently, if a customer clicks ‘Submit’ from the GitHub configuration page (jira-configuration.hbs) in Safari to retry a normal or full sync, nothing appears to happen. There is no feedback in the UI and the customer has no idea what’s happened. The error logged to the console in production is Failed to load resource: the server responded with a status of 400 (Bad Request). In development it’s Failed to load resource: the server responded with a status of 403 (Forbidden) with an additional error thrown in the terminal by our web worker: ForbiddenError: invalid csrf token.
In March of 2020 apple updated Safari to block all 3rd party cookies. This means, when we make a request from a Jira site to a GitHub …
> ARC-136 remove csrfProtection middleware from jira/sync to resolve retry issue in Safari 

- lib/github/middleware.js
- test/fixtures/pull-request-triggered-by-bot.json
- test/safe/pull-request.test.js
- test/unit/models/index.test.js
This PR adds tests to https://github.com/integrations/jira/pull/413.
Points to help us understand why having an exception to allow bots events only on PR state changes sound reasonable:
- We don't see how we can end up in a bot feedback loop situation if we allow bot events processing only for those, given the fact that this integration does not update PR states by itself.
- The act of merging - which is inherently a one-time action - won’t cause a loop so the bot-filter can be dropped for merge hooks, but left in place for other types of hooks so that the status could be properly posted in JIRA.
- The infinite loop issue may only happen on comment/description edition because it is the only case where this Jira integration actually writes data in GitHub and can trigger events. For that …
> ARC-114: Allow bots to trigger changes

- lib/github/middleware.js
- lib/github/pull-request.js
- test/safe/pull-request.test.js
We're still not sure how the pull request number would be missing from the payload. Adding the payload to Sentry so we can try to have more information. Also adding try/catch when listing reviewers and logging the exception.
> HOTFIX-ARC-116: Add payload to sentry. Add try/catch when listing reviewers

- lib/github/pull-request.js
Need to better understand why the `listReviews` call is failing, adding payload information to the log, changing the log level to `warn` to make it more visible.  We need to understand who's it affecting and why.
> HOTFIX ARC-116: adding logging of payload 

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Change to github actions to allow deploying to a temporary heroku app for testing purposes until ownership transfer is done.  Deployment is done on any push on master after the `Test` workflow passes.
> ARC-190 Changing github actions and adding deploying to temporary heroku app

- src/config/metric-names.ts
- src/github/index.ts
Bad copy and paste when setting up the metric names and bungled the naming of the webhook metric.
> ARC-254 fix metric name

- github-for-jira.sd.yml
Fixed an issue with Global Edge proxy to rewrite the host parameter as heroku doesn't allow any other domain except the one specified in the app.
> ARC-329 domain proxy to github app

- package-lock.json
- package.json
- src/config/env.ts
- src/config/proxy.ts
- src/main.ts
- src/worker/main.ts
Finally, a working solution. Tested in `ddev`, and the sync is going through with enabled IP allowlist.
This proxies ALL outbound calls now, not only the ones towards GitHub. This is not a problem when we're working with production Jira instance. When we're working with Jira dev instances, we have to disable the proxy, because the proxy doesn't allow calls to protected Atlassian resources.
> ARC-10: configuring proxy for outbound calls

- CONTRIBUTING.md
- app.yml
After testing in staging, we actually need Read & Write for displaying Builds and Deployments.
> ARC-8: Update permissions on docs

- .env.example
- .env.test
- .eslintrc.json
- CONTRIBUTING.md
- package-lock.json
- package.json
- src/api/index.ts
- src/config/enhance-octokit.ts
- src/config/github-api.ts
- src/config/logger.ts
- src/config/statsd.ts
- src/configure-robot.ts
- src/deepcheck.ts
- src/frontend/github-client-middleware.ts
- src/frontend/github-oauth.ts
- src/github/index.ts
- src/jira/client/axios.ts
- src/jira/index.ts
- src/main.ts
- src/middleware/log-middleware.ts
- src/models/axios-error-event-decorator.ts
- src/models/sequelize.ts
- src/models/subscription.ts
- src/send-sync-status-metrics.ts
- src/sync/discovery.ts
- src/sync/installation.ts
- src/sync/pull-request.ts
- src/tracking/index.ts
- src/util/filteringStream.ts
- src/worker/app.ts
In this pull request I did the following:
1. Created a logger.ts file with shared logger for the application (Same changes as @rachellerathbone  made before)
2. Used this logger everywhere where we could. (Some Probot logs are still use its custom logger, hence we can't override it)
3. Added a filtering stream to the logger, to remove HTTP access logs which hardcoded in Probot
4. Added overrides for console.log (and its other logging functions) to use our common logging and ES Lint rule to prohibit console.log usage
I am currently testing this in ddev. In the next PR I'll get through all our logs and make sure that they comply our logging standard.
> Arc 290 arc 334 centralise logging and cleanup logs

- lib/github/deployment.js
- lib/github/workflow.js
We need to send only `builds` or `deployments` because they contain `issueKeys` and not the whole `jiraPayload`. Same as it's done for [branch](https://github.com/integrations/jira/blob/master/lib/github/branch.js#L17), for example.
> HOTFIX-ARC-8: Send right object to reduceProjectKeys function.

- README.md
This README may create a confusion for customers. GitHub Enterprise can refer to either GitHub Enterprise Server or GitHub Enterprise Cloud. This integration supports GitHub Enterprise Cloud, but not GitHub Enterprise Server.
I've added clarification about what might be considered in the future, i.e. either GitHub Server or ghithub.com with Jira Server/Data Center
> Update README.md to be clear about GHES support

- src/frontend/get-github-configuration.ts
- src/frontend/get-github-setup.ts
- src/frontend/post-github-setup.ts
- src/util/getUrl.ts
This is first of many steps to improve the painful installation flow we have in place. These changes focus on improving the experience for users who are installing the GitHub for Jira app from the Jira marketplace and do not have their Jira instance installed in their GitHub org. As seen in the screenshot below, after a user clicks the green install button from the 'Install Jira' page, they are then redirected to the Jira marketplace. As the app would've already been installed, the steps in the purple box are redundant (another redundant path is to go marketplace > apps in navbar > manage apps > get started).
With the updated url redirect, users will skip these steps and land back on the github/configuration page with their org now displayed in the list with the option to 'Install' (see …
> ARC-387 redirect to github/configuration

- README.md
Just adding a link to the table of contents, so users can go straight to the GitHub Actions for Jira info if they want.
> ARC-403: Add GitHub Actions link to table of contents.

- lib/transforms/workflow.js
Send `workflow.id` instead of `workflow_run.id` as the pipeline id to Jira.
Solves:
https://customerfeedback.atlassian.net/browse/JSF-2097
https://customerfeedback.atlassian.net/browse/JSF-2094
and https://github.com/integrations/jira/issues/545
> ARC-407: Fix workflow mapping before sending it to Jira.

- src/config/logger.ts
Minor update to the logger so that logs are human-readable when locally but still print in JSON format for all Micros envs.
> ARC-413 readable logs

- SUPPORT.md
- src/config/metric-names.ts
- src/frontend/get-jira-configuration.ts
- src/models/subscription.ts
- static/css/jira-configuration.css
- test/frontend/get-jira-configuration.test.ts
- views/jira-configuration.hbs
According to Chris from GitHub, if a STALLED sync is the result of a 'temporary technical issue' our app will try and kick the sync off again from where it got stuck. Otherwise, the user needs to resubmit the sync. It's not clear to users whether their issue is temporary or not so, to minimise confusion, we have decided to remove the STALLED state and bucket it in with the FAILED state. 
If our app does pick up a STALLED sync and is able to continue the statuses will now go FAILED > IN PROGRESS > COMPLETE. If not, it will remain in the FAILED state. Right now, a user will need to manually retry the sync but, as we gather metrics, we will work on automating this process.
> ARC-418 Collapse STALLED sync state into FAILED

- static/css/github-configuration.css
- static/css/global.css
- views/github-configuration.hbs
Updated the connect an org page to match the new design spec. Initially, we wanted to render all orgs where the user was an admin, regardless of whether Jira was installed or not. This would have allowed us to completely remove the need to have a link to `/installations/new`. Unfortunately, as we can't access the full list of orgs with user to server tokens, we need to keep the current implementation. Tidying up the UI so it at least looks a little nicer.
> ARC-430 update new org link

- lib/frontend/app.js
- test/unit/maintenance/__snapshots__/maintenance.test.js.snap
- test/unit/maintenance/maintenance.test.js
Maintenance mode was obscuring the ability for people to install the app using `/jira/atlassian-connect.json`.  This has now been fixed and the tests reflected as such.
> ARC-385 Maintenance mode atlassian-connect.json

- github-for-jira.sd.yml
- test/middleware/webhook-timeout.test.ts
Moving proxy back to github's heroku on staging to test out migration properly.
> ARC-429 Change back proxy

- lib/frontend/get-maintenance.js
- lib/jira/connect.js
`atlassian-connect.json` needs to return the `APP_URL` for the `baseUrl` key or else it will make the marketplace app migration useless because it'll still point to the old heroku app url.
Also needed to fix maintenance mode to return a 200 status for `/jira/configure` when being called from Marketplace because it tries to intercept the status and doesn't show the page if not a 200.
> ARC-429 Fixing connect.json to use APP_URL

- lib/github/middleware.js
We need to do this to be able to get `installationId` for any webhooks that got triggered while we're doing the migration.  Afterwards, we can start a resync for those installations so no data is lost in the process.
> ARC-436 Adding better webhook logs for maintenance mode

- lib/transforms/pull-request.js
Effectively works around the surprising fact that webhook payloads
generated by PR review comments [omit a `merged` entry](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-34) on the included
`pull_request` object.
Closes atlassian/github-for-jira#372.
> Map PR status with `merged_at` instead of `merged`

- .env.example
- src/transforms/pull-request.ts
We were using the `merged` property of the pull_request payload, which is [apparently based on the data given by the REST API](https://docs.github.com/en/rest/reference/pulls) which shows that the `merged` property is _always_ sent.  However, for the `pull_request_review` payload, it's missing causing issues in the PR status.  @atrigueiro and I confirmed that the `merged_at` property is available on all pull request payloads and are using that instead; it's a ISO8601 string that we can easily use as a truthy conditional replacement for `merged`.
This should fix https://github.com/atlassian/github-for-jira/issues/372
> ARC-220 pull request merge status fix

- src/frontend/get-maintenance.ts
- views/jira-configuration.hbs
- views/maintenance.hbs
Apparently, we don't need to send a 200 http status for it to work in connect, it just needs the connect SDK to be included in the HTML.
> ARC-385 Maintenance status fix

- src/transforms/deployment.ts
We’re already doing the same with builds, when we receive `queued` from GH, we send it as `in progress` to Jira. We'll now send `pending` deployments as `in progress` to Jira as well.
> noissue: change deployment mapping

- src/github/middleware.ts
- src/models/subscription.ts
While maintenance mode is one during the transition, we want to log installationIds from our end so we can resync them.
> ARC-448 log webhook maintenance installation ID

- github-for-jira.sd.yml
Changing APP_URL to point to services domain to test out maintenance mode webhook logs to confirm it's logging installation id.
> ARC-448 webhook logs prod

- github-for-jira.sd.yml
There is no threshold for this alarm which will be high enough to not make it noisy. 
Until we replace this alert with error budget detector we need to lower the priority.
> ARC-460 Lower 5xx alarm priority

- src/github/middleware.ts
Sentry should already get an event through the withSentry() call
> HOT-96452: removing sentry event that we don't need 

- github-for-jira.sd.yml
adding problematic IP to blackhole list for staging and prod.
> ARC-587 Removing proxy from ddev resource as it should default

- src/frontend/github-client-middleware.ts
Added a log to make it easier for us to check user permissions and identify cause of 'issues' on the connect an org page.
> ARC-608 add log to check for user permission level

- src/github/index.ts
- src/github/middleware.ts
- src/github/push.ts
- src/transforms/push.ts
- test/safe/push.test.ts
A few changes here:
* Fixed request failing with 400 when trying to push commits to Jira
* For push webhook path,  carrying webhookId through the queue and adding to logs as a parameter
* Renamed id to webhookId in logs, where we use webhook id to reduce confusion
> ARC-477 add more logs to diagnose jira 400 failures and fix it

- src/frontend/github-oauth.ts
- src/github/middleware.ts
- src/util/getUrl.ts
Customer still can't see the connect button. They are:
- logged into the correct GH account
- are an admin on the org
- are an owner
Trying to add more logs to try and solve why:
- the 2 orgs connected that render to the GH config page don't show up on the connect an org pg
- why they can't see the connect button when they appear to have all the correct permissions (usually only hidden if the user is not an admin)
The only thing I can currently find in the logs for the org they are trying to connect (equinix-enps) is `Halting further execution since no subscriptions were found` which comes from github/middleware.
> ARC-608 adding more logs to solve customer issue where admin/owner cannot connect an org

- src/transforms/branch.ts
We're seeing a bunch of `Deprecation: [@octokit/rest] "sha" parameter is deprecated for ".repos.getCommit()". Use "ref" instead` warning on our logs. 
`getCommit` now expects a parameter called `ref`.
All other places we're calling `getCommit` are already using `ref`.
> ARC-468: Use ref instead of sha for getCommit

- github-for-jira.sd.yml
To prevent logging large JSON blobs in the logs, taking over DB storage.
> ARC-651 Increasing long query timeout to 5 seconds

- src/api/index.ts
The installation queue seems to be polluted with multiple installation jobs per installation. However, there should be only **one** installation job per installation on the queue at any given time.
This explains high number of items on the installation queue and the rate limiting errors we're seeing. 
This PR adds an admin endpoint that allows us to deduplicate the installation queue so that only one job per installation id remains on the queue.
Running this endpoint may relieve the installation queue of its current pressure.
> endpoint to deduplicate the installation queue

- src/sync/installation.ts
From the logs, this is the cause for some syncs to fail.
> fixing null-reference that can cause a sync to fail

- src/worker/main.ts
We increased the timeout of the queue jobs, but the `lockDuration` is still the default (30 seconds). That means that after 30 seconds, a message will be "unlocked" and picked up by another worker to be processed again. Since each job adds a follow-up job to the queue, a job that is processed twice will add two follow-up-jobs to the queue, which might again add new jobs and so on, building up the waiting queue.
This PR should hopefully fix this.
> ARC-666: make lockDuration dependent on the timeout to avoid a job being triggered twice

- src/config/feature-flags.ts
- src/sync/commits.ts
- src/sync/queries.ts
We're seeing a bunch of these errors in the logs, causing backfills to fail. So, we'll catch this error and retry again without asking for the `changedFiles` field.
The `changedFiles` feels can be undefined, it's only used in 2 places and those have a null-check.
> ARC-671: retry loading commits on error "The changedFiles count for this commit is unavailable"

- src/sync/installation.ts
Realised while trying to look for failures for specific customers, that we currently have no way to search for a sync failed log and connect it to a specific jira instance.
> Add jiraHost to sync failed log

- src/config/feature-flags.ts
- src/config/metric-names.ts
- src/models/subscription.ts
- src/sync/installation.ts
- test/unit/sync/helpers/sync-helpers.test.ts
- test/unit/sync/installation.test.ts
Currently, a sync stops completely on a single error. For example, when the GitHub API times out (which it does for large requests), or if there is some other error that we don't have error handling for, the whole sync stops. All repos that have not been synced will stay unsynced.
This PR changes this behavior. If there is an unhandled error, the sync will now continue with the next task, a task being one of the following:
- syncing the commits of a repo
- syncing the PRs of a repo
- syncing the branches of a repo
I.e. if there is an error in the middle of syncing commits, the rest of the commits for this repo are skipped (and left "unsynced") and it continues with the branches and PRs.
In the future, we should add even better handling around this, so that we can continue with the next …
> Arc 676 continue sync on error

- src/frontend/get-jira-configuration.ts
- src/models/subscription.ts
- test/frontend/get-jira-configuration.test.ts
When a subscription hasn't had its `updatedAt` field updated for the last 15 minutes, the UI would show a sync as FAILED, even if it was still running in the background.
This PR updates the `updatedAt` field more often but also removes the mapping to the FAILED state in the UI.
> ARC-682: remove the "sync failed" error on the read path

- src/api/index.ts
- src/models/subscription.ts
Allows filtering for subscriptions with the `updatedAt` field older than a specified number of seconds. We can use this to restart syncs that have been inactive for a time.
> ARC-421: allow filtering for "last updated" date in resync endpoint

- github-for-jira.sd.yml
Added TransactionLogsDiskUsageAlarm to our service descriptor to increase the threshold and evaluation period for the P4 that we keep seeing in #fusion-low-prio-alerts channel.
> ARC-679 transaction log alert

- src/api/index.ts
The deduplication mechanism was a bit too aggressive. It identified duplicates only by the installation ID, but there may be multiple jobs with the same installation ID, but with different Jira hosts. That means jobs were being removed from the queue when they shouldn't. This would explain the behavior we're seeing that some syncs are just stopping to do anything.
With this fix, the deduplication now identifies a job by its installationId **and** jiraHost.
> ARC-421: make the deduplication aware of the jiraHost. 

- src/config/feature-flags.ts
- src/sync/installation.ts
Splitting processInstallation() onto two functions (feature flagged) and adding "job"  to the logger as a property.
This is needed for the future step once I add deduplication logic around the invocation of the new function.
> ARC-764: split processInstallation

- src/sync/installation.ts
- test/unit/sync/installation.test.ts
Just realised that actually there could be a corner-case which might led to a staled sync. 
Let's try to always reschedule :holdonyourbutts:
> ARC-764: always reschedule duplicate messages

- github-for-jira.sd.yml
> Remove ALB latency alerts

- src/config/env.ts
Reverts atlassian/github-for-jira#768
Even though the whitelist proxy was recommended to us for use, it isn't considered the right proxy for using with IP allowlisting on Github.  The network team has updated their documentation and flowchart as to which proxy is the best to use moving forward.  We shouldn't hit rate limiting if we're using the JWT token authentication with the Jira API but we might hit the Jira IP ACLs.  There's currently a ticket to automatically add outbound IPs from our own proxy to all Jira configured ACLs as to not hit any issues if customers want to restrict IPs.
This revert should fix quite a few issues with our enterprise customers.
> Revert "Changing external proxy for whitelist proxy"

- package-lock.json
- src/config/feature-flags.ts
- src/frontend/get-github-configuration.ts
- src/frontend/get-jira-configuration.ts
- src/github/client/github-client.ts
Replacing the iteration through all repositories, with a single GraphQL call. (Iteration was used to count all repos). 
At the same time the new GitHub Client is used to make GraphQL call
> ARC-872: use GraphQL to count repos

- src/frontend/get-github-setup.ts
- src/util/get-url.ts
- test/unit/util/get-url.test.ts
From `getGitHubConfigurationUrl` to `getJiraAppUrl` as it wasn't getting the github configuration page, but instead would return to the app installation if it was already installed on the jira host.
> Change name of util url function to better describe it

- github-for-jira.sd.yml
- src/config/feature-flags.ts
- src/frontend/get-github-configuration.ts
- src/frontend/github-client-middleware.ts
The `isAdmin()` function currently uses an user-based authentication. This PR changes it to an app-based auth in the hopes of fixing some IP allowlisting issues. 
Feature flag: https://hello.atlassian.net/browse/FD-28625
> ARC-642: changing GitHub auth for isAdmin()

- src/frontend/github-client-middleware.ts
- static/css/global.css
- test/unit/frontend/github-client-middleware.test.ts
Merge with `isAdmin` failed because it didn't take into consideration the new way to set `res.locals.github`
> ARC-908 fixing isAdmin function and css issue with body

- docs/ip-allowlist.md
These typos led to broken links in the docs, meaning that users had to manually fix
them before being able to navigate to the referenced pages
> Fix 2 typos in ip-allowlist.md

- Dockerfile
Fixing VULN-645422.
alpine:3.14 has a high sev issue that was introduced by a vulnerable module (busybox). More details [here](https://snyk.io/test/docker/alpine%3A3.14.2?tab=dependencies)
alpine:15 fixed the issue. More details [here](https://snyk.io/test/docker/alpine%3A3.15?tab=dependencies)
We're using it in conjunction with node though and `node:14.17-alpine3.15` isn't a valid tag, so I bumped to `node:14.18-alpine3.15`. See valid tags [here](https://hub.docker.com/_/node).
> VULN-645422: bump alpine to 3.15

- src/config/feature-flags.ts
- src/frontend/get-github-configuration.ts
- src/sync/sync-utils.ts
In this PR I am cleaning up another flag `use-new-github-client-to-count-repos` 
I've made it on the top of https://github.com/atlassian/github-for-jira/pull/1008 so you can review them separately but merge at once
> Fd 28420 cleanup

- src/config/feature-flags.ts
- src/github/client/github-client.ts
- src/sqs/push.ts
- src/transforms/push.ts
- test/safe/branch.test.ts
- test/safe/push.test.ts
Second PR, here I did the following:
* Removed `use-new-github-client-for-push` feature flag
* Removed `bull` library dependency from the `push` queue processing code
* Changed integration test to use SQS handler instead of old redis job processor
* Removed installationID parameter from GitHub Client, which we were passing wrongly
> Removed use-new-github-client-for-push feature flag, removed `bull` dependency from push processor

- src/github/client/errors.ts
- test/github/client/errors.test.ts
Currently, errors (like the infamous IP allowlist issue) don't propagate their stacktrace. That means, in the case of the IP allowlist issue, we can't see which IP addresses are being blocked, for example.
This PR makes it so that the stack trace is propagated
> propagate stack trace on GitHub API errors

- views/jira-configuration.hbs
In-depth context: https://atlassian.slack.com/archives/C01PERFAUHZ/p1633927476248100 
Summary: the * and message we added to show customers the issue key reference limit had been exceeded was causing problems where there didn't need to be problems. Essentially, we were drawing attention to something customers will most likely not even notice. Because of this, we have decided to simply remove it altogether.
Somewhat long video of me installing and uninstalling orgs to make sure nothing broke.
https://user-images.githubusercontent.com/37155488/150894472-2c1fb19f-d4b4-4879-affa-cc550da2703f.mov
> ARC-747 Remove warning about missing issue association

- src/jira/client/axios.ts
order of interceptors is important because auth middleware uses the path (made by URL params) to create the token
> fixing order of middleware because it can break things

- test/setup/setup.ts
While doing tests, I stopped a test halfway through and when I restarted it, some tests data was still in redis (deduplicator) which made my tests fail.  After scratching my head for a while, I figured out the issue and had to stop the redis docker container and delete the volume, then spin it back up.
This prevents having to do that extra work or waste time head scratching.
> clearing redis keys before tests to prevent having test data still there

- src/github/client/github-client.ts
Because we use path of the original URL as a metric tag, doing this:
```
this.axios.post<Octokit.AppsCreateInstallationTokenResponse>(`/app/installations/${githubInstallationId}/access_tokens`
```
exploded our metrics cardinality.
I've reeplaced it with urlParams
> Use url params for GitHub installation Id

- src/sqs/index.ts
- test/unit/sqs/index.test.ts
In this PR I've fixed the visibility timeout change failure in case if we were getting decimal timeout value.
We currently have all Rate Limiting error delays broken, because they pass decimal values. So they use default timeout (Which adds additional load to the rate limited orgs)
Fixing it now
> Allow  decimal values for the queue delays

- src/jira/util/jwt.ts
- test/setup/setup.ts
- test/unit/jira/util/jwt.test.ts
JWT verification was using `req.path` which is not the full path but the local router path.  If you want the full path, you need to concatenate `req.baseUrl + req.path` to get the full path.
> fixing JWT QSH verification to use the correct request parameter for full path

- github-for-jira.sd.yml
In this PR I am increasing max PG connections and max nodes count for prod.
This config can be tested only by deploying it to prod, but our metrics show very low Postgres SPU usage (Less than 1% on average and up to 3% spikes)
Validated it via micros validate command
> ARC-1092 Increased max PG connections and worker nodes count

- github-for-jira.sd.yml
Originally added as a detector in [fusion-monitoring ](https://bitbucket.org/atlassian/fusion-monitoring/pull-requests/444) but moved to our service descriptor to avoid delays and to be consistent with other Micros alerts.
> Alert for messages building in queues

- .eslintrc.json
- src/config/feature-flags.ts
- src/github/branch.ts
- src/github/client/github-client.ts
- src/github/pull-request.ts
- src/interfaces/jira.ts
- src/sqs/branch.ts
- src/sync/branches.ts
- src/sync/commits.ts
- src/transforms/branch.ts
- test/safe/branch.test.ts
Added new Feature flag use-new-github-client-for-branch-event to toggle github client in place of OctoKit for the create branch process.
There were 2 locations that Octokit has been replaced for the GetRef and GetCommit API calls.
> Arc 1177 - Replace Octokit with GitHub Client for Branch events

- src/sqs/index.ts
- test/setup/matchers/to-be-called-with-delay.ts
- test/setup/setup.ts
- test/unit/sqs/index.test.ts
Fixing an issue with Rate Limiting error which was never retried during the backfill.
I've added caps for Message delay and Visibility Timeout. 
We didn't have any checks when we set message delay, so when it we were passing the wrong value, the message remained unsent. It was causing backfill unexpectedly finish for some customers
> ARC-1200 Added maximums for message delay and visibility timeout

- static/css/github-configuration.css
**Prefix**
**Post Fix**
Updated Margin left on the cog link ( followed aui's lead for a 10px margin-left (aui-button ~ aui-button)
**Before**
**After**
> removed fixed height on popup box to allow it to go full size

- src/routes/api/api-router.ts
Adds a check to the `/resync` API to require a filter. Previously, it was possible to call the API without a filter and it would start a backfill for all installations.
> HOT-98735: make the Admin API less susceptible to human error

- src/transforms/push.ts
Makes it easier to check in the logs if pushes are successful for a given Jira site
> HOT-98735: add the jira host to the push logs 

- Dockerfile.prod
Was missing the 3rd config change :(
All 14.18-alpine3.15 references are now updated to 14.19-alpine3.15
> ARC-1167 update missing base image config

- src/config/feature-flags.ts
- src/github/client/app-token-holder.ts
- src/github/client/github-app-client.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/setup/github-setup-get.ts
- src/routes/github/subscription/github-subscription-delete.ts
- src/routes/github/subscription/github-subscription-get.ts
- src/routes/jira/configuration/jira-configuration-get.ts
- src/routes/router.ts
Replace the need for githubinstallationID on the github app client
introduced new feature flag use-new-github-client-for-redirect to use ghclient in place of octokit
> Arc 1284 route gh client

- .github/CODEOWNERS
Adding https://github.com/orgs/atlassian/teams/fusion-arc to CODEOWNERS file
> Update CODEOWNERS file to include atlassian/fusion-arc

- src/middleware/github-webhook-middleware.ts
Attempt to fix JST-761382.
According to the GH API docs, not all repo owners have a name but all have a login https://docs.github.com/en/rest/repos/repos#get-a-repository.
> JST-761382: Use repo owner login instead of repo owner name for orgName

- src/config/env.ts
- src/config/statsd.ts
- src/github/issue.ts
- src/github/push.ts
- src/github/workflow.ts
- src/transforms/transform-workflow.ts
Add new metrics group to global configuration of statd to indicate whether it is from WebServer or Worker.
Have deployed to stg-west and verify it in the dashboard.
> ARC-467 - ARC-467-add-tag-web-worker-metrics

- src/transforms/push.ts
There is still some noise coming through for the data depot migration. Commit message length > 1024
_Kinda tempted to change out limiter to 1023 incase there is a off by 1 error in the logic somewhere e.g. `data < 1024`_
https://splunk.paas-inf.net/en-GB/app/search/search?earliest=-60m%40m&latest=now&q=search%20%60micros_jswdd-processor%60%20env%3Dprod*%20level%3DWARN%20%22submitDevInfo%20failed%20parse%2Fvalidate%22%20provider-namespace%3Dclassic%20provider-id%3Dcom.github.integration.production&display.events.fields=%5B%22message%22%2C%20%22m.sv%22%5D&display.page.search.mode=fast&dispatch.sample_ratio=1&display.page.search.tab=events&display.general.type=events&sid=1653878702.704393_62D9EEBE-1751-48A5-B0C6-CDABAC40F831
Feel like there is more than this change to resolve it, but will …
> limited the commit message length on push events

- static/css/jira-configuration.css
**In this PR**
Added a hitbox to the sync warning icon to keep popup open when transitioning from icon to popup.
Couple of options here in how to achieve it... went with least intrusive.
**Proof**
The thing to look for in the screenshot is the location of the cursor(just above the warning icon) before the change the popup would vanish if the cursor went to the deadzone between icon and popup, much annoying.
It now has a generous hitbox around it so that its more consistent with that atlas feel.
> Added a hitbox for the sync warning hover icon

- src/sync/discovery.ts
Found small issue in FF code for customer that would save `NaN` in the DB for the repository cursor.
> PCS-87130 fixing cursor issue that would save NaN to DB

- src/transforms/transform-pull-request.ts
From Sentry:
> TypeError
>  transformPullRequest(transforms:transform-pull-request)
> Cannot read property 'name' of null
> /app/src/transforms/transform-pull-request.js` in transformPullRequest at line 46:29
We do get some payloads that don't contain a repo for some reason, which we do validate on line 61. This PR only adds a `?` before getting the repo name in case there's no repo.
> ARC-1426: Assert optional when getting repo name

- src/transforms/transform-pull-request.ts
From [Sentry](https://sentry.io/organizations/atlassian-2y/issues/3147532533/events/a0eb3e1e5fb9491cbecb9a1d18924b5c/?project=5988951&query=is%3Aunresolved)
> TypeError
> Cannot read property 'state' of null
> /app/src/transforms/transform-pull-request.js in null.<anonymous> at line 29:40
Wasn't able to quite replicate this one locally but at least this PR will fix type errors.
However, I did come across a scenario where if I add a reviewer while creating the pull request before hitting the "Create pull request" button, the reviewers don't appear in Jira because we do a `getReviews` instead of looking through the `requested_reviewers` field in the payload. Raising a ticket [ARC-1430] in our backlog to address this.
[ARC-1430]: https://softwareteams.atlassian.net/browse/ARC-1430
> ARC-1428: Assert optional when getting PR review status

- src/routes/api/installation/api-installation-get.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/configuration/github-configuration-post.ts
- src/routes/github/configuration/github-configuration-router.ts
- src/routes/github/setup/github-setup-get.ts
- src/routes/github/subscription/github-subscription-delete.ts
- src/routes/github/subscription/github-subscription-get.ts
- src/routes/jira/configuration/jira-configuration-get.ts
- src/routes/router.ts
- src/util/get-github-client-config.ts
Continuing to break https://github.com/atlassian/github-for-jira/pull/1277/ down into smaller PRs.
In this PR:
- added a new function to our get github client config: `getGitHubClientConfigFromAppId`
- updated `createAppClient` to use above function and updates all calls to createAppClient to pass in the `gitHubAppId`
Up next: updating `createUserClient` to use `getGitHubClientConfigFromAppId`
> Arc-1408 part 2

- static/js/jira-connect-ghe.js
- views/jira-connect-ghe.hbs
**Rationale**
- When users type in a GitHub cloud URL when trying to connect to a GitHub Enterprise server, it is now treated as a URL validation error, displaying an error message with a link that redirects to GitHub Cloud site.
**Changes**
- The separate method `checkGHEServerUrl` was removed and the logic was added to `checkValidGHEUrl`.
- A new method was created which simply displays the error messages, based on the error object passed to it.
- Minor code cleanup 
- A new method `hideErrorMessage` was created.
**Video**
https://www.loom.com/share/0605e2c39ac5443a8b76089cbb5bf267
**Whats not done**
- No validation in terms of duplication nor security has been implemented. It will be done in backend.
> ARC-1435 - Update the validation error for GitHub Cloud URL when creating GHE server

- src/routes/jira/events/jira-select-version-router.ts
- src/routes/jira/server/jira-select-version-get.ts
- static/js/jira-select-github-version.js
**Rationale:**
Moving some small clean-up changes out of another [PR](https://github.com/atlassian/github-for-jira/pull/1299) I currently have set a draft. Was going to leave them in there but, seeing they aren't tightly coupled to the main changes, it made more sense to pull them out into a separate PR.
**Changes:**
See comments: https://github.com/atlassian/github-for-jira/pull/1301/files Also deleted static/js/jira-select-github-version.js as it wasn't being used anywhere. The jQuery for this page is handled in jira-select-card-option.js. This was a file that I forgot to remove when I added the GH version view.
> Small clean up items for GHE UI flow

- CONTRIBUTING.md
**Rationale:**
While writing a doc to explain how to manually create a GH app for our GHE customers I realised we never updated the permissions listed in our CONTRIBUTING.md file. Resolved!
> ARC-1466 update required permissions in contributing

- src/util/is-valid-url-test.ts
- src/util/is-valid-url.test.ts
- src/util/is-valid-url.ts
- static/js/jira-server-url.js
Rationale: we need to validate the ghe url on the server side. Once again, created a baby pr for this to keep #1312 on the smaller side.
> adding url validation util

- deploy/lambda/auto-deployment.js
- github-for-jira.sd.yml
- Added condition to make sure not other pipeline is running  before trigerring new pipeline.
- Updated cron expression to run auto deployment lambda in every 10 mins
**Why**
We want to run auto-deployment lambda in every 10 mins and starts deployment if any change in master branch. The pipeline takes ~40 mins to deploy to prod. If auto-deployment lambda again runs in that timeframe, it will trigger the pipeline again. This will result in muti pipelines running for same commit in master branch.
NA
NA
This is running only in Prod. By looking into lamda invocations timestamp and logs.
NA
> ARC-1462 Added check to make sure pipeline is not running before triggering new one

- src/routes/api/api-ping-get.ts
- src/routes/api/api-router.test.ts
- src/routes/api/api-router.ts
Adding an admin endpoint that "pings" a remote URL so we can test if a certain URL is accessible from our staging and production servers.
This is so we can test any network changes, specifically the change we need to do so that our internal GitHub Enterprise Server instance is accessible from our Micros service.
> ARC-1501: add a ping endpoint to test outbound connections

- src/routes/jira/jira-atlassian-connect-get.ts
- test/snapshots/routes/jira/jira-atlassian-connect.test.ts.snap
- test/snapshots/routes/maintenance/maintenance-router.test.ts.snap
- Added `location: none` to all the `generalPages` in the app-connector file.
**Why**
- To hide the pages from showing up in the dropdown(screenshot below). We don’t want our customers to be able to jump ahead in the flow/navigate to any parts of that flow if they’re trying to connect to cloud so we need to figure out a way to prevent them from rendering in the dropdown.
- ![image](https://user-images.githubusercontent.com/13076255/178199673-018295f6-c648-4309-9137-3ebb82ed40e9.png)
> ARC-1487 - Update jira connect to hide pages in dropdown

- src/transforms/transform-code-scanning-alert.ts
Returning early if the code scan alert webhook does not contain any instances or undefined.
Over 7000 errors in the last 30 days 
Splunk query - `micros_github-for-jira env="prod*" "Cannot read property 'map'*" | stats count by event`
**Why**
Firstly, to stop subsequent code try to use a map in an undefined value.
If there are no instances, then we can't extract any refs from the webhook, so exiting early is the best option.
Monitor
> ARC-1427 return early if no array values

- static/css/jira-server-url.css
- static/js/jira-server-url.js
- views/jira-server-url.hbs
- views/partials/server-error-message-box.hbs
- In Jira Server URL page,
- Changed the `Learn more` link to `Learn more about network configuration for GitHub for Jira`
- Removed the `Learn more` link from all error messages
> ARC-1512 - GHE UI tweaks

- src/routes/github/webhook/webhook-receiver-post.test.ts
- src/routes/github/webhook/webhook-receiver-post.ts
Pull webhook secret from env. variable for Github cloud and `GitHubServerApps` table for GHE
**Why**
GHE config data stored in `GitHubServerApps` where as Github cloud config in environment variables. 
use the existing `ghe_server` flag
ARC-1347
**How has this been tested?**
> ARC-1347 Read webhook secret from env. variable for GitHub cloud

- src/models/github-server-app.ts
- src/routes/jira/jira-atlassian-connect-get.ts
- src/routes/jira/jira-router.ts
- src/routes/jira/server/jira-ghe-servers-router.ts
- src/routes/jira/server/jira-ghe-servers.ts
- static/js/jira-server-url.js
- static/js/select-server-table.js
- test/snapshots/routes/jira/jira-atlassian-connect.test.ts.snap
- test/snapshots/routes/maintenance/maintenance-router.test.ts.snap
- views/jira-select-github-cloud-app.hbs
- views/jira-select-server.hbs
- views/partials/select-server-table.hbs
- New module added in app connector.
- New route and methods added to fetch the list of GHE servers for a JIRA instance.
- Fetching the actual list of GHE servers in the view.
- Added `pathNameForAddNew` for navigating back to jira-server-url page.
**Video**
https://user-images.githubusercontent.com/13076255/178638525-597c6512-a985-492b-b635-668062922aaa.mov
> ARC-1458 - GHE UI: Navigate from server url screen to select GH app screen

- src/sync/installation.ts
Dropping the feature flag for build and deployments in backfill, has been running at 100% for over a month.
**Why**
Its time, but also about to make some changes here and it was complicating my life.
**Removed feature flags**
run-backfill-for-builds-and-deployments
Tested locally and soaked on stage
> remove build deploy backfill flag

- src/config/feature-flags.ts
- src/transforms/transform-deployment.ts
- src/transforms/transform-deployments.test.ts
- removed FF
- feature for sending related commits with deployments is now enabled permanently
**Why**
- the feature has been rolled out 100% in production
- unit tests
> SAI-12053 Removed feature flag controlling sending associated commits with deployments

- .yarnrc
Defaulting `yarn install` to ignore optional dependencies
**Why**
Because it was annoying of writing `yarn install --ignore-optional` every time.
None
_Jira Issues_
`yarn install` while not connected to VPN should not break
Profit.
> Adding yarnrc for defaulting ignore-optional on yarn install

- static/css/global.css
- static/js/navigation.js
- views/github-configuration.hbs
- views/partials/navigation.hbs
- The back button in the Github Configuration/Connect Page, which is opened as a child window, was removed.
- The attribute `closeOnBack` was removed and a new attribute `hideBackButton` was added in partial `navigation`.
**Why**
- [Outcome based on this discussion ](https://atlassian.slack.com/archives/C039YPCGCSG/p1658711208126409)
- In local dev environment
- In Staging environment
> ARC-1546 - GHE UI - Lose the back button in the GH cloud connect page(child window)

- src/jira/util/jwt.test.ts
- src/jira/util/jwt.ts
- The encoded URLs in the path are decoded before being passed through `createQueryStringHash`.
- Test case added
**Why**
- In our connect-app, when the user has an encoded URI in the request path, the request fails with an error `wrong qsh`. 
- ARC-1519
- In local environment
- Test case
> ARC 1555 - JWT wrong QSH for encoded URLs in path

- src/github/client/github-client-interceptors.ts
There was an issue using logging inside a ternary in `axios.ts`, so I'm fixing it in the GitHub client interceptors as well.
> replace ternary operator with if/else to avoid logging issues

- github-for-jira.sd.yml
Add depends_on for cryptor to the app itself.
**Why**
It seems the worker start consuming sqs before cryptor sidecar is ready. Having this "depends_on" will "ease" the problem.
N/A
ARC-1354
ddev
Check whether it works over each deployments. If no, may need to add more sophisticated checking for cryptor.
> ARC-1354 fix starting dependencies of cryptor.

- src/github/client/github-queries.ts
- src/github/deployment.test.ts
- src/sync/deployment.test.ts
- src/transforms/transform-deployment.ts
- src/transforms/transform-deployments.test.ts
- test/fixtures/api/graphql/deployment-nodes-mixed.json
- test/fixtures/api/graphql/deployment-nodes.json
- test/fixtures/deployment_status-basic.json
reverting `repositoryId` to use `repository.id` instead of `repository.node_id`
**Why**
Because `node_id` has certain special characters that data depot doesn't allow.  We sometimes see the error `Id must match the pattern '[A-Za-z0-9\-._~]+` depending on the the repository which means that the deployment call to jira will fail and won't show for the customer. We've decided (arc and sayans) that this is the quickest simplest fix for now until the sayans change that id validation to be more broad for our purposes.
none
HOT-99909
unit tests
Deploy it, do another PR that reverts this change waiting for the sayans to fix data depot validation.
> Reverting repositoryId change on deployment fix

- github-for-jira.sd.yml
Increase alarm threshold for `AlarmOnTooManyMessages` to match autoscaling target * 2
**Why**
We changed autoscaling rules but not alarms to match, therefore we need to give a bit more opportunity for autoscaling to handle the messages before we panic and raise an alarm.
> Update alarm threshold to match autoscaling

- src/routes/github/webhook/webhook-context.ts
- src/routes/github/webhook/webhook-receiver-post.test.ts
- src/routes/github/webhook/webhook-receiver-post.ts
- src/sqs/sqs.types.ts
2/3 Pushing gitHub App data to queue
Add gitHubAppConfig to the webhook context, so that we can push it to payload.
**Why**
existing gitHubInstallationId is not unique, need more info.
N/A
ARC-1558
Unit test.
3/3 Add those info to payload.
> Add gitHubAppConfig to webhook context

- src/config/feature-flags.ts
- src/github/client/app-token-holder.ts
- src/routes/jira/jira-get.ts
- src/util/get-github-client-config.ts
Added a ghe_server constant.
**Why**
So we can easily turn the GHE_SERVER flag on/off to test locally and there's no way to easily do this with our current ff setup.
Update our ff config?
> create global to easily turn ghe_server on/off

- src/models/github-server-app.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-delete.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-delete.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-router.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts
- src/routes/jira/connect/enterprise/server_app/jira-connect-enterprise-server-app-get.ts
- static/css/jira-configuration-new.css
- static/js/jira-configuration.js
- views/jira-configuration-new.hbs
Functionality for 'edit' and 'delete' in the GH app dropdown for GHES.
**Why**
So users can edit and delete GH apps.
All behind GHE_SERVER
ARC-1563
Tested in stg and locally:
https://user-images.githubusercontent.com/37155488/183027316-f5880528-58c6-48d2-b8d8-960e619b4796.mov
- ARC 1572: update a GH app. In this PR I'm simply navigating to the form. Will take care of actually updating the fields in this issue.
- ARC 1577: we need to refactor the jira configuration table partial so it is an actual reusable component. We should be using this for the dropdown from cloud and for server gh apps. This will be addressed outside of the scope for this project.
> ARC-1563 delete app and navigate to form on edit

- src/jira/client/jira-client.ts
- test/snapshots/jira/client/jira-client.test.ts.snap
Removal of unused endpoints from jiraClient.
**Why**
Because we don't need them...
ARC-1561
Deployed to staging and no issues detected. Have triple checked the removed endpoints aren't being used anywhere.
Continue on ARC-1561: updating all calls the jiraClient that use gitHubInstallationId. Was going to do them all in one PR but figured that's a sure fire way to break something. Going to tackle each yellow highlighted area in this doc separately https://hello.atlassian.net/wiki/spaces/PF/pages/1856341692/Jira+Client
> ARC-1561 remove unused endpoints from jira client

- views/jira-manual-app-creation.hbs
Converting webhooks secret field into plain text
**Why**
To match designs
Under existing ghe_server flag
NONE (too lazy)
locally
:susp:
> NONE: convert a password field into a text one

- src/models/installation.ts
Removing unused column from Installations table/model
**Why**
Because it is not used
Nah
None (too lazy)
locally
Schema migration after this one is in prod.
> Easy Karma: remove unused gitHubAppId from Installations model

- Dockerfile
- Dockerfile.prod
Update zlib package.
Annoyingly, the image we are using Alpine 3.16 has the correct package but the scanner still complains so have to force the zlib package to update.....This highlights that there is something else wrong for me. We shouldn't need to do this, so need to investigate why the image update isn't satisfying Snyk!!
**Why**
VULN scanner picked up a vulnerability
[VULN](https://asecurityteam.atlassian.net/browse/VULN-892689?jql=project%20%3D%20VULN%20AND%20resolution%20%3D%20Unresolved%20AND%20%22Product%20-%20Team%5BSelect%20List%20(cascading)%5D%22%20in%20cascadeOption(%22Fusion%22%2C%22Arc%22)%20AND%20%22SLO%20Start%20Date%5BDate%5D%22%20IS%20NOT%20EMPTY%20AND%20assignee%20IS%20NOT%20EMPTY%20ORDER%20BY%20created%20DESC)
> VULN-892689 - Forced zlib update for docker image

- src/models/subscription.test.ts
- src/models/subscription.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/configuration/github-configuration-router.test.ts
- Added `gitHubAppId` to fetch the correct subscriptions in `github-configuration-get`
- Removed multiple DB calls.
**Why**
- The previous usage of `Subscription.getAllForHost` was pulling both cloud and server apps. This caused the cloud apps to be failed installations because they don't exist in the GHES. So, it was being removed from the DB as failed installations are all being removed. 
- In local and ddev environment
> ARC 1605 - Endpoint GitHubConfigurationGet removes the previous GH cloudconnection 

- src/models/encrypted-model.ts
- src/routes/healthcheck/deepcheck-get.ts
- src/routes/healthcheck/healthcheck-get.ts
- src/util/encryption-client.ts
Move the error logging from within EncryptionClient to EncryptedModel
**Why**
Don't want to get too much noise during worker starting up and when cryptor is not ready. It is okay because:
1. If it stays error, we will found out, the cicd pipeline will be red.
2. If it is only transient, it will turns green when the cryptor sidecar catchup and started, then we shouldn't care about this error. So warn instead.
N/A
ARC-1354
N/A
N/A
> ARC-1354 Supress error logging during healthcheck for Worker

- src/github/branch.ts
- src/github/code-scanning-alert.ts
- src/github/deployment.ts
- src/github/issue-comment.ts
- src/github/issue.ts
- src/github/pull-request.ts
- src/github/repository.ts
- src/github/workflow.ts
- src/transforms/push.ts
- src/util/webhook-utils.ts
- src/util/webhooks.test.ts
Passing gitHubAppId to emitWebhookProcessedMetrics so we can pass the gitHubProduct tag (cloud/server).
**Why**
So we can update our charts to compare cloud/server.
ARC-1543
Updating the chart/s in our metrics.
> Arc-1543 webhook metrics

- github-for-jira.sd.yml
Increasing the number of allowed connections to pgbouncer
**Why**
Because it refuses connections in peak hours, which causes broken syncs: SequelizeConnectionError strongly correlates with "no more connections allowed (max_client_conn)" from pgbouncer (check the ticket)
ARC-1621
We will check the effect in prod :cowboy:
:susp:
> ARC-1621: increase max_client_conn for pgbouncer

- static/js/jira-select-card-option.js
- Flipped the condition to check for manual first instead of automatic.
**Why**
- In the view, by default automatic app is selected, but nothing has been selected yet. So, when the user slicks on the **Create** button, the selected option is undefined, which was just going to the `else` part. 
- So, went with the quick solution by simply flipping the condition to check manual first.
- Local
> ARC-1615 - Nits and Frogs - App selection screen

- src/interfaces/common.ts
- src/routes/github/github-oauth-router.ts
- src/routes/github/github-router.test.ts
- Added github UUID in the session.
- Checking this saved UUID with the UUID from githubAppConfig.
- If same do nothing
- If different, do another login to fetch new gitHubToken. 
**Why**
- The `githubToken` for the endpoint `user/installations`, which fetches the list of installations for a user, is based on the app. So, for every new app, we need a new token. Thats why we are re-authenticating every time when the UUIDs do not match.
- In local
- In ddev
**Video**
https://user-images.githubusercontent.com/13076255/185519062-a4b7bc43-e5b1-498a-af7f-e789f9790085.mov
> ARC-1594 - Only render orgs connected to an app on the connect an org page

- views/jira-configuration-new.hbs
- The collapsibles are all opened by default in Jira Config page.
**Why**
- People's demand
- Locally
> ARC-1638 - Expand github apps by default for GHE server

- static/js/jira-manual-app-creation.js
- static/js/jira-server-url.js
- views/jira-manual-app-creation.hbs
- views/jira-select-app-creation.hbs
- views/jira-server-url.hbs
What's in this PR?
Links to documentation.
Why
So customers can read documentation... but they probably won't coz nobody reads things 🙃
Added feature flags
GHE_SERVER
Affected issues
ARC-1620
How has this been tested?
Locally
What's Next?
Publication of docs so links actually work (won't merge before then)
> DO NOT MERGE: ARC-1620 doc links (redo)

- static/js/jira-manual-app-creation.js
- views/jira-manual-app-creation.hbs
- Condition updated to check if the file is valid before displaying the success flag.
**Why**
- To avoid confusion when uploading an invalid file.
- Tested in local and staging.
**Video**
https://user-images.githubusercontent.com/13076255/186343546-72034b2b-a4b7-4234-9aaf-b0375078139f.mov
> ARC-1641 - Block uploading files that don't have the .pem extension

- src/services/user-config-service.test.ts
- src/services/user-config-service.ts
- src/sync/discovery.ts
- src/transforms/transform-deployment.test.ts
- src/transforms/transform-deployment.ts
This PR adds some missing pieces to the config-as-code feature.
A [previous PR ](https://github.com/atlassian/github-for-jira/pulls?q=is%3Apr+is%3Aclosed+config-as-code) added the feature that when someone changes the contents of the file `.jira/config.yml` in a repo, this config is saved in our database.
This PR adds the same thing during discovery (i.e. at the start of a backfilling), so that the config is available shortly after the backfilling has been started.
> Load user config during discovery

- src/routes/github/create-branch/github-create-branch-get.test.ts
- src/routes/github/create-branch/github-create-branch-get.ts
- src/routes/github/create-branch/github-create-branch-router.ts
- src/routes/github/github-router.ts
- static/css/github-create-branch.css
- views/github-create-branch.hbs
- New route(GET), view and css file for Create Branch.
- Test case added for the new route.
**Why**
- To unblock other tasks.
- Tested the route `/github/create-branch` in local and staging environments.
**Screenshot**
- In local
- In staging
> ARC 1591 - Create a new route and placeholder page for create-branch

- Dockerfile.prod
Small change to the Dockerfile for prod to ignore the yarnrc file.
**Why**
Analytics are currently broken but work if we remove the .yarnrc file. We can't simply rip this out otherwise anyone who doesn't have access to SOX packages won't be able to run the app locally. 
ARC-1644
Deployed to staging and checked our logs to make sure the analytics client exists.
This is a temporary fix. @mboudreau is going to keep digging into the issue.
> ignore yarnrc in prod

- src/config/feature-flags.ts
- src/github/client/github-app-client.ts
- src/github/client/github-client-cloud.test.ts
- src/github/client/github-client-server.test.ts
- src/github/client/github-client.test.ts
- src/github/client/github-client.ts
- src/github/client/github-installation-client.ts
- src/github/client/github-user-client.ts
- src/transforms/transform-deployment.test.ts
- src/util/get-github-client-config.ts
- src/util/github-utils.test.ts
Currently we have 2 places where we configure the client with duplicating code: 
- `src/github/client/github-client.ts` and
- `src/util/get-github-client-config.ts`
This refactoring will leave in only one place in `get-github-client-config` (after FF is removed). In that place, there's also access to `jiraHost` , which I need in order to configure the proxy (next step).
**Why**
Currently there's no way to configure outbound proxy based on `jiraHost`, because 
1. we don't have it in the place where we do configuration now (client)
2. even if we bring it over, we cannot use it because that's in a constructor and constructors cannot be async (the list of hosts that should be skipped are to be fetched from a FF)
3. this needs to be done in a common place so we could …
> ARC-1643 refactor config class a bit

- src/sqs/backfill-discovery.test.ts
- Used an actual private key when creating `GitHubServerApp`
**Why**
- `backfill-discovery.test.ts` failed when FF `GHE_SERVER` was turned on.
- Locally
> Test case fix when FF GHE_SERVER is on

- src/config/feature-flags.ts
- src/github/code-scanning-alert.ts
Removing send-code-scanning-alerts-as-remote-links FF
**Why**
Because it has been out in prod for ages and I want my name out of the Board of Shame
_Jira Issues_
> noissue: Remove ff send-code-scanning-alerts-as-remote-links

- github-for-jira.sd.yml
Adjusting pgbouncer and postgres config in stg
**Why**
Because currently postgres can have too small number of connections and the current configuration of pgbouncer can easily overwhelm it when multiple stacks are running at the same time.
Config change for staging, will be tested during deployment
Think what to do with the "autodeploy" lambda
> NONE: adjust pgbouncer and postgres (in stg) configs

- src/github/client/github-queries.ts
- src/github/client/github-user-client.ts
- src/routes/github/create-branch/github-branches-get.test.ts
- src/routes/github/create-branch/github-branches-get.ts
- src/routes/github/create-branch/github-create-branch-router.ts
Implented an endpint that return all the branches for a given `org` and `repo`
**Why**
This endpoint will be used to display branches in drop down for create-branch UI.
[ARC-1608]
Unit test cases added
[ARC-1608]: https://softwareteams.atlassian.net/browse/ARC-1608
> ARC-1608 Get branches endpoint

- src/sync/installation.ts
- src/util/logger-utils.ts
Adding prTitle and prRef to the sensitive data list
Removing a complete payload object in a log
**Why**
prTitle and prRef is UGC and needs to be hidden
an entire payload it too much logging! we need to be targeted, payload is ok during debug but not as a default, we cannot always be sure what is in it and could potentially leak PII/UGC
nope
nope
locally only, changes are minor enough that I feel this is sufficient.
Keep hunting for UGC!
> prTitle and prRef are now hashed - removed payload dump on log

- src/github/client/github-user-client.ts
- src/routes/github/create-branch/github-branches-get.ts
- src/routes/github/create-branch/github-create-branch-post.ts
- static/js/github-create-branch.js
We're showing only first 100 branches in `create-branch` page. This will give a user flexibility to provide the source branch
in case repo has more than 100 branches and the intended branch not in the drop down list. 
Show error in case of invalid source branch
**Why**
To support use case with more than 100 branches
[ARC-1682]
Local
[ARC-1682]: https://softwareteams.atlassian.net/browse/ARC-1682
> ARC-1682 Manual source branch

- src/routes/error-router.ts
The SLO of the rendering of the GitHub config page is failing because there are too many "bad events". The logs show a lot of errors like `Error: Jira Host url is missing`. So, I mapped this error (and some others) to an HTTP status code `400` (instead of the default `500`). `400`s don't count as "bad events" in the SLO
> ARC-1688: map some errors to 400 instead of 500

- src/routes/github/github-oauth-router.ts
- src/routes/github/github-router.test.ts
Reverts atlassian/github-for-jira#1615
Seeing `Error creating branch` in staging, so we do need `repo` scope for listing repositories and `user` scope for creating branches.
> Revert "ARC-1351: Remove OAuth scopes for the user's access_token"

- src/routes/github/create-branch/github-create-branch-get.test.ts
- src/routes/github/create-branch/github-create-branch-get.ts
- src/routes/github/create-branch/github-create-branch-router.ts
- src/routes/github/create-branch/github-remove-session.test.ts
- src/routes/github/create-branch/github-remove-session.ts
- static/css/github-create-branch.css
- static/js/github-create-branch.js
- views/github-create-branch.hbs
Display logged-in GitHub user details with an option to change GitHub login. 
When `Change GitHub login` link is clicked, it will clear the `GitHub` token from session and opens up GitHub cloud or enterprise site in a new window to logout from the portal itself.
[ARC-1606]
Local
[ARC-1606]: https://softwareteams.atlassian.net/browse/ARC-1606
> ARC-1606 Display user details

- static/js/github-create-branch.js
- Added label headers for the list of repos:
- Default repos 
- List of repos when searched 
**Why**
- For better UX
- Local
- For the initial list of repos
- For the list of repos when searched by the user
> ARC-1701 - Repo search labels

- src/config/feature-flags.ts
- src/github/client/github-installation-client.ts
- src/transforms/transform-branch.ts
Trying to not encode "head/" in URL
**Why**
Since yesterday we see a lot of 404s when trying to fetch ref. This is an attempt to fix it in case the problem is with the percent encoding, because, according to docs, it shouldn't be escaped
USE_FIXED_GET_REF
It is broken in prod anyway, we will see if it helps or not.
not sure
> NONE: try not to escape head/

- src/jira/verify-installation.test.ts
- src/middleware/jira-jwt-middleware.test.ts
- src/models/installation.ts
- src/routes/github/setup/github-setup-router.test.ts
- src/routes/jira/events/jira-events-install-post.test.ts
- src/routes/jira/events/jira-events-uninstall-post.test.ts
Remove the code access to old Installation secrets column
**Why**
So that we can deprecate the sequelize encrypt
N/A
The col is not being read/write any more (two FF to managed this). This is just to clean up the code.
ARC-1354
Not yet except unit test.
> Remove the code access to old column

- .github/workflows/on-push.yml
Running pull_request event only when we first open it to prevent duplicate builds
Quick fix to github workflow to prevent duplication of actions across push and pr
**Why**
Duplicate build are redundent and take longer to finish, costs more.
none
none
manually
nothing
> Fix build duplication in PR

- static/css/github-create-branch.css
- static/js/github-create-branch.js
- views/github-create-branch.hbs
- Added a help link and popup when users types in a repo that is unavailable
**Why**
- Better user experience
- Locally
**Video**
https://user-images.githubusercontent.com/13076255/194064752-1cfb1627-5131-4236-a4d7-e3f8aec54bbb.mov
> ARC 1602 - Help link and popup for repo search help

- src/config/env.ts
- src/config/redis-info.ts
Pulling redis info from envVars so it can be overriden in .env file
**Why**
Cause now it is annoying to our customers: whoever spins the app in their network cannot override the settings
N/a
N/a
Locally
> [Easy Karma] NONE: use redis from envVars

- src/config/env.ts
- src/config/redis-info.ts
Adding ability to turn on tls for redis
**Why**
Because currently it is ON for prod and OFF for dev, which means it is impossible to integrate a dev-running app with an encrypted-in-transit redis
nah
N/a
Typing and prayers
I hope that would suffice
> NONE: make REDISX tls configurable

- src/middleware/frontend-log-middleware.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/create-branch/github-create-branch-options-get.ts
- The status code for error _Jira host is missing_ was updated from 500 to 404.
- Added a new uuid in the request id for `frontend-log-middleware`.
**Why**
- To get SLO back to 99%.
- Staging 
- _MISSING_JIRA_HOST_ is not viewed in the error logs as 500s anymore
> ARC-1733 - Correcting SLO for github/configuration

- src/models/subscription.ts
- src/routes/github/create-branch/github-create-branch-get.ts
Filter out subscriptions based on githubAppId. Earlier it was showing repos from all subscriptions which means repo listing for cloud also includes enterprise repos.
Local
> Fix repo listing

- src/worker/startup.ts
Stop the `stop the probot httpServer`
**Why**
For each deployment, we don't want the existing stack to stop the probot (WORKER) http server from receiving healthcheck request, in case we want to rollback, we still need the existing stack (healthcheck endpoint) to function.
N/A
ARC-1444
ddev
Multiple deploy to make sure it still works
rollback and make sure old stack works
However, before this change, I can't make old stack (health endpoint) cease functioning during rollback to verify my theory. I suspect it is due to healthcheck in worker group is quite special, the stack may still work even that healthcheck endpoint is broken. Too much micros assumption here, can't 100% prove anything. …
> Arc 1444 keep probot running on stop

- src/routes/github/create-branch/github-create-branch-get.ts
- static/css/github-create-branch.css
- static/js/github-create-branch.js
- views/github-create-branch.hbs
- Added the final success state in the same page using jQuery. This is not done in a separate route as intended previously, because:
- Creating a new route means redirect, which means we lose the animating flow.
- There’s not much value in creating a separate route for this.
- After the branch has been created successfully, added a 1.5 second timeout to show the action links.
**Why**
- Following the UI with the smooth animation 😎 
- Local
- Staging
**Video**
https://user-images.githubusercontent.com/13076255/195258732-f6528e8d-aab3-48da-80e2-94c754bd53cf.mov
> ARC-1728 - Success Page after creating a branch

- src/routes/github/create-branch/github-create-branch-options-get.ts
If same app is installed on multiple orgs, it shows same app multiple times in GHE instance drop down.
Fix the issue by filtering out duplicate githubAppIds.
Local
> Fix GH enterprise listing 

- src/routes/router.ts
Set the express json parse size to 50mb for ddev/stg/prod
**Why**
When we cut over to use new webhook route, the default size limit 1mb is not enough according to [github cloud](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads) and [enterpriser server doc](https://docs.github.com/en/enterprise-server@3.3/developers/webhooks-and-events/webhooks/webhook-events-and-payloads).
N/A
ARC-1662
Unit test.
Test on stage and cut over prod traffic for webhook
> Arc 1662 increase payload limit for enterprise

- static/js/github-create-branch.js
- views/github-create-branch.hbs
- Updated the final success page after creating a branch.
- Removed the copy code part
**Why**
- Copy code(copy to clipboard) doesn't work with iframes. 
- Test
**Videos**
https://user-images.githubusercontent.com/13076255/196085161-0bd5f3c0-4e6d-414a-b385-5c0d2a54edb0.mov
> ARC-1742- Update success page to stay big mode

- static/js/github-create-branch.js
- views/github-create-branch.hbs
- Selection of unavailable repositories has been removed.
- Condition for displaying **Configure GitHub Integration** has been updated.
- True only when the input has no value selected and the user types in a repo that is not available.
- **No results text** updated to **No search results**.
- Link added for **Configure GitHub Integration**.
**Why**
- Discussed during the catchup.
- Local
**Video**
https://user-images.githubusercontent.com/13076255/196088442-d4bd0078-b1df-4e77-8899-2854640033a5.mov
> ARC 1752 - Shows search text instead of no results found on repo search

- src/interfaces/common.ts
- src/routes/github/webhook/webhook-receiver-post.test.ts
- src/routes/github/webhook/webhook-receiver-post.ts
- src/routes/router.test.ts
- src/routes/router.ts
- test/utils/create-webhook-app.ts
Calculate signature on rawBody, not the parsed payload
**Why**
Because parsing affects the content (e.g. removes spaces) and that affects the signature
Not needed: we had tested it before + we have a pollinator run-once check in staging for webhooks
splunk
splunk
> NONE: calculate signature using rawBody instead of parsed payload

- src/config/feature-flags.ts
- src/interfaces/common.ts
- src/interfaces/jira.ts
- src/services/user-config-service.test.ts
- src/services/user-config-service.ts
- src/transforms/transform-deployment.test.ts
- src/transforms/transform-deployment.ts
Service association for deployments has been added. 
**Why**
We need to add a support service association for Deployments that has been created by GitHub. In order to use those at multiple features at JSM. 
-
[SALTBAE-337](https://jdog.jira-dev.com/browse/SALTBAE-337)
Locally
Unit Test cases also added. 
We're going to add Deployment Gating capability for GitHub Deployments.
> SALTBAE-337 Add service association to deployments

- src/util/jira-utils.test.ts
- src/util/jira-utils.ts
Fix for  jira issue parser expecting a minimum of 2 numbers in the id and accompanied tests
**Why**
it borked the pollinator tests when on
already had one
None
Added tests
Deploy and turn on FF
> fixing problem with issue key parser

- etc/poco/bundle/extras-prod.json
Just adding the new pollinator check uuid to the POCO policy
**Why**
Because pollinator needs to delete a repo 
n/a
ARC-936
https://pollinator.prod.atl-paas.net/checks/ccf05819-f0a7-4c55-8b42-8d3db0c11bce
Adding uuid for backfil test later
> ARC-936: Add new GHE pollinator check to POCO policy

- src/models/github-server-app.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-delete.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-delete.ts
🔐 🐞 Add a new where clause when deleting GHE apps.
**Why**
Currently it seems when user disconnect a GHE server from a jiraHost, all other jiraHosts that also has connection to the same server will be disconnected as well.
N/A
ARC-1802
Unit test.
Use can also delete ANY GHE apps as long as they know the uuid (which is public on the url anyway), need to fix that as well.
> Arc 1802 fix cross site ghe deletion

- src/middleware/github-server-app-middleware.test.ts
- src/middleware/github-server-app-middleware.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-delete.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-delete.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-router.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-router.ts
- src/routes/router.test.ts
- test/utils/jwt.ts
Add protection on GHE app deletion.
**Why**
Currently anyone (with legit app installation) can delete anyone's ghe app record in db if they know the uuid (which is public anyway)
N/A
ARC-1803
Unit test
stage: [wip]
N/A
> Arc 1803 fix insecure deletion of ghe apps

- src/middleware/github-server-app-middleware.test.ts
- src/middleware/github-server-app-middleware.ts
- src/models/github-server-app.test.ts
- src/models/github-server-app.ts
- src/routes/github/github-oauth-router.ts
- src/routes/github/github-router.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-router.test.ts
- src/sqs/sqs.types.ts
Remove the decrypted secrets in `res.locals.gitHubAppConfig` to avoid risk that it might be deserialized and sent to somewhere like in the splunk or worse frontend.
Replace those secrets with a closure method.
**Why**
It is generally dangerous have something secrets in the json object hanging around for long. 
N/A
ARC-1810
Unit test
Tested on Stage.
1. Need more proper typings on the `res.locals`. Already have some ideas. Will raise a PR soon.
2. Also remove the decrypted secrets in `gitHubClient` as well.
> ARC-1810 remove decrypted ghe app secrets from res.locals

- static/css/github-create-branch.css
all on the create branch page
The select2 arrow color updated to design.
Text color for select2 and text darkened
Brighter background on text input when focued
**Why**
To match designs!
> Updated styles for create branch

- github-for-jira.sd.yml
- src/config/logger.ts
- src/sqs/sqs.ts
- src/util/logger-utils.test.ts
- src/util/logger-utils.ts
Updated the SQS message attribute to be messageId so its more obvious when Splunking
Sent DLQ errors to the unsafe logging environment so we can use legit data
create DLQ alarms - low prio and the numbers are best guess at this point.
**Why**
We had trouble last time we had an outage with error handling on SQS and was lacking details of the messages
Testing Alarms in stage(forced with a lower threshold)
Tested that unsafe logs containing UGC/PII only show up in [env]-unsafe Splunk partition.
When the world collapses and we need to know what some of the failed messages are we wont have a shake our fists.
> ARC-1817 improve failed SQS logging and add DLQ alarms

- src/routes/github/create-branch/github-create-branch-post.ts
- static/js/github-create-branch.js
Pass the jirahost as part of the create branch post
**Why**
There is a possible scenario when you get in a tangle and we still cant rely on the session jirahost, so have pass this then when the jwt story is played we can rely on it again
> pass jirahost as part of body on create branch post

- github-for-jira.sd.yml
While we backfill all the pull we dont want to reset the instances every release !! so temporarily adding it so we can fish backfill in peace.
revert to 15 on backfill completion
> temp update scaling rules for a max of 35 instacnces

- src/routes/jira/jira-get.test.ts
- src/routes/jira/jira-get.ts
Addition of an else clause to add `isConfigured: true` for any customers that land on our config page and have existing connections.
**Why**
Because I forgot to do it in my last pr :coneofshame:
Locally
> add else clause

- .github/workflows/on-push.yml
Fix to prevent duplication of pull_request builds and push builds
**Why**
There was still some builds being duplicated between push/pull_request events which is not good as the e2e tests will conflict with each other
visually
> Trying to fix build duplicates

- src/util/analytics-client.ts
Move track even source one level up.
Also add more detail
**Why**
To match the doc and fix the error of `Cannot sendAnalytics event: Error: Value trackEvent.source cannot be undefined`
This is what splunk complain about
This is what the doc said: https://bitbucket.org/atlassian/analytics-node-client/src/v3.1.1/
N/A
ARC-1857
N/A
N/A
> udpate track source to one level up

- github-for-jira.sd.yml
Setting min workers to 5 and max to 15 (back from 35 since backfilling is done)
**Why**
Because 3 is not enough and 35 is too much (was a temporary change)
n/a
n/a
> noissue: Set min workers to 5 and max to 15

- src/routes/jira/events/jira-events-uninstall-post.ts
very small change to not prevent uninstall on app-properties issue
**Why**
Because it might not be set, it might fail and prevent the installation from being uninstalled
ARC-1873
> ARC-1873 Making the uninstall non-blocking on app property which might not be set

- src/jira/util/jira-client-util.test.ts
- src/jira/util/jira-client-util.ts
- src/util/jira-utils.ts
- test/fixtures/text/issue-keys-with-alphanumeric-values.rendered.md
- test/fixtures/text/issue-keys-with-alphanumeric-values.source.md
- Updating the Regex for `addJiraIssueLinks` to match with the Regex being used for `jiraIssueKeyParser`
**Why**
- The current Regex is outdated and does not support alphanumeric issue keys like `K1-1`.
- Raised up in a DOS ticket - [JST-827001](https://getsupport.atlassian.com/browse/JST-827001)
- Added Test case
- Locally
- Merge and notify the customer
> ARC 1886 - [JST-827001] - Fixing Regex to support alphanumeric issue keys

- CONTRIBUTING.md
- src/github/push.ts
- src/interfaces/common.ts
Sends an analytic event to track the total commits pushed and number of commits containing the jira issue key in the commit message.
I'm not sure if such an event is useful for the backfilled commits.
**Why**
Context: We are planning to associate commits to services in Jira Service Management(JSM) most probably via deployment association to services. This will help JSM users to find the root cause fast during incident investigation.
Reason: We need stats on percentage of commits not stored in Open Toolchain due to lack of jira issue keys in the commit message. This stat will help us decide if we should plan additional work to store commits without issue keys in the future. 
None.
None. This was discussed in Atlassian …
> Track stats for total commits pushed and commits with jira issue key

- src/github/client/github-client-interceptors.ts
- src/github/client/github-installation-client.ts
- src/github/client/github-queries.ts
- src/sync/installation.ts
- src/transforms/transform-deployment.ts
- src/transforms/util/github-api-requests.ts
- src/util/get-github-client-config.ts
changing `changedFiles` GraphQL property to `changedFilesIfAvailable` .
**Why**
`changedFiles` is deprecated as of January 1st and changing it to `changedFilesIfAvailable` should fix some 422s and 500s we've been seeing while backfilling large customers.
None
a few
Updated tests that were already there
Deploy and test backfilling on large customers currently blocked.
> changing changedFiles to changedFilesIfAvailable

- src/transforms/push.ts
Splunk suggest excessive GitHub calls, I believe is on the mapping of the SHAs for push, GitHub docs say that there should only be 20 on the webhook payload, it looks like more so want to confirm it before I make the changes to limit it.
> Additional logging on push transform

- src/jira/client/jira-client.ts
- src/jira/verify-installation.ts
- src/middleware/jira-jwt-middleware.ts
- src/middleware/jira-symmetric-jwt-middleware.ts
- src/models/encrypted-model.test.ts
- src/models/encrypted-model.ts
- src/models/installation.ts
- src/models/jira-client.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.test.ts
- src/routes/jira/sync/jira-sync-post.test.ts
- src/sync/installation.test.ts
- src/sync/installation.ts
1. use existing loggers for logging to stitch logs together
2. retry cryptor errors during backfill
**Why**
Long backfills might face some intermittent cryptor errors and we don't want this to break the backfilling
🤠 
CES-10000
🤠 
🤠
> NONE: improve logging for cryptor; retry when cryptor is not there

- src/github/pull-request.test.ts
- src/interfaces/jira.ts
- src/sync/pull-requests.test.ts
- src/transforms/transform-pull-request.ts
- test/jira/multiple-jira.test.ts
Adding a `getGithubUser` call after we map the reviews because the reviewers' data we get on the webhook payload doesn’t contain the email for that user.
**Why**
So PR Reviewers can be matched to their Atlassian account IDs.
[ARC-1945]
Locally - I'll test in staging now.
[ARC-1945]: https://softwareteams.atlassian.net/browse/ARC-1945
> ARC-1945: Get reviewers email before sending PR review to Jira.

- src/sync/installation.test.ts
- src/sync/installation.ts
Retrying yet another error that could stop backfilling
Kudos to ChatGPT for help!
**Why**
Customer is complaining
The end of the world
> [EZY KARMA] [GENERATED BY CHATGPT] NONE: retry database connection errors on backfill

- package.json
- src/routes/api/client-key/client-key-regex.ts
- yarn.lock
Replace xml2json to xml2json-light
**Why**
The old dep xml2json relies on python on the cli path.
Unit Test
N/A
> Remove dep on xml2json as it depends on python.

- src/routes/github/repository/github-repository-get.ts
Use the correct logger
**Why**
Cause currently it is impossible to see logs for a single jiraHost
> [ONE-LINER] NONE: pass over the correct logger

- src/github/client/token-cache.test.ts
- src/models/models.test.ts
- src/models/subscription.test.ts
- src/models/subscription.ts
- src/routes/api/configuration/api-configuration-get.test.ts
- src/routes/api/configuration/api-configuration-post.test.ts
- src/routes/api/installation/api-installation-delete.test.ts
- src/routes/api/installation/api-installation-get.test.ts
- src/routes/api/installation/api-installation-sync-post.test.ts
- src/routes/api/installation/api-installation-syncstate-get.test.ts
- src/routes/github/configuration/github-configuration-post.ts
- src/routes/github/configuration/github-configuration-router.test.ts
- src/routes/github/create-branch/github-create-branch-options-get.test.ts
- src/routes/jira/sync/jira-sync-post.test.ts
- src/sync/sync-utils.test.ts
Bug fix on double hashed client key
**Why**
Coz it is a bug.
Last time we have a correct "Subscription" record is 2021
`select "createdAt" from "Subscriptions" where exists (select 1 from "Installations" where "jiraClientKey" = "clientKey") order by "createdAt" desc limit 2;`
N/A
_Jira Issues_
ARC-1958
Unit test.
> ARC-1958 fix the bug that client key is double hashed on Subscription table

- src/routes/github/repository/github-repository-get.test.ts
- src/routes/github/repository/github-repository-get.ts
Be more tolerant towards GitHub API errors in create-branch call
**Why**
https://github.com/atlassian/github-for-jira/issues/1845
According to https://docs.github.com/en/rest/search?apiVersion=2022-11-28#access-errors-or-missing-search-results , if a user don't have perms to access an org, the API might throw a error. And if the customer has multiple orgs connected to it, that shouldn't be a reason to kill the whole request only because of a single org
> None do not blow repo seach on single error

- src/config/feature-flags.ts
- src/github/client/github-anonymous-client.ts
- src/interfaces/common.ts
- src/routes/github/create-branch/github-remove-session.ts
- src/routes/github/github-oauth-router.test.ts
- src/routes/github/github-oauth-router.ts
- src/util/get-github-client-config.ts
The current behaviour was when GitHub access token becomes invalid, user is redirected to OAuth flow to generate new access token. We were not leveraging the refresh token which is also generated along with access token.  Now the refresh token is stored in session along with access token. When access token becomes invalid, refresh token is being used to generate a new access token if possible (refresh token also have expiry). If not, redirected to OAuth flow.
**Why**
This will improve the user experience not to reload the page for generating GitHub access token
RENEW_GITHUB_TOKEN
[ARC-942]
Unit Test
Local
[ARC-942]: https://softwareteams.atlassian.net/browse/ARC-942
> ARC-942 Renew Github token with a refresh token

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
Templates and links to:    
* Direct support and bug requests to support portal
* Put more structure to help people give more details when they leave feature requests
**Why**
* At the moment we are under-resourced to act like a support team and attend to all the support and bug requests in GH issues, and we want our users to be better served when they need help.
* More details on feature requests help the product team to better manage and triage features.
_Jira Issues_
Only tested with my personal repo. Someone should review the copy writing here.
> Add template for feature request, and direct requests to support portal

- src/config/feature-flags.ts
- src/routes/github/github-encrypt-header-post.test.ts
- src/routes/github/github-encrypt-header-post.ts
- src/routes/github/github-router.ts
- src/util/encryption-client.ts
Adding a temp endpoint for our enterprise customer to encrypt a header. 
**Why**
This is needed for BTF work: until we have UI we will support them with feature flags
https://app.launchdarkly.com/github-for-jira/production/features/headers-to-encrypt/targeting
ARC-1976
Locally
> ARC-1976: add encryption endpoint

- src/github/client/github-client.ts
We are adding some logging to estimate the number of calls we are doing to GH per ort
**Why**
Support is asking us the numbers so they could ask GH for extension
> NONE: add logging to debug rate-limiting

- src/util/preemptive-rate-limit.test.ts
- src/util/preemptive-rate-limit.ts
Fix the negative number problem.
**Why**
Block the sync.
N/A
_Jira Issues_
Unit test.
N/A
> ARC-1231 fix preemptive rate limit negative number problem

- src/config/feature-flags.ts
- src/sync/build.test.ts
- src/sync/build.ts
- src/sync/sync.types.ts
- test/utils/database-state-creator.ts
Increaseing page size for builds: a sync is going on forever for one particular customer
**Why**
I'd like to see how the changed page size affects the speed of the sync. 
- increase-builds-page-size-coef
> NONE: add coef for page size for builds

- src/sqs/sqs.test.ts
- src/sqs/sqs.ts
- src/sqs/sqs.types.ts
- src/sync/branch.test.ts
- src/sync/build.test.ts
- src/sync/commits.test.ts
- src/sync/deployment.test.ts
- src/sync/sync-utils.ts
- src/util/preemptive-rate-limit.test.ts
- src/util/preemptive-rate-limit.ts
Fix the bug of preemtively rate limiting.
**Why**
1. It sometimes reschdule the msg immediately. Fixed via added minimum delay. This seems to be something strange from the github side. It return the reset time that's almost exactly same as current time.
2. It use changeMsgVisiblity, which will incurr exceed retry count and lost the msg, customer sync will get stuck. Fixed via sending a new message. 
N/A
ARC-1995
Unit test.
On stage:
When setting threshold to 1, rate limit kicked in, new msg was scheduled
Reset the threshold back to normal, and after 15min (the maximum new msg delay), backfill success again.
N/A
> Arc 1995 keep msg in queue for exceed ratelimit

- src/config/interfaces.ts
- src/routes/jira/jira-get.ts
- src/util/handlebars/handlebar-helpers.test.ts
- src/util/handlebars/handlebar-helpers.ts
- static/css/jira-configuration-new.css
- static/js/jira-configuration.js
- views/jira-configuration-new.hbs
- views/partials/jira-configuration-table.hbs
Add a ui label to tell when is the last success backfill date.
FF On, backfilled all
FF On, backfilled till sometime:
FF On, backfilled not success
**Why**
So the user is aware of when to continue to.
Reuse backfill-algorithm-incremental
ARC-1975
Unit test & local
Turn on FF.
> Arc 1975 show backfill since label

- src/routes/api/api-reset-subscription-failed-tasks.ts
- src/routes/api/api-router.test.ts
- src/routes/api/api-router.ts
- test/utils/database-state-creator.ts
Adding admin endpoint to reset failed tasks
**Why**
we have no way now
> NONE: add reset failed task endpoint

- src/sqs/deployment.test.ts
- src/util/preemptive-rate-limit.ts
Applying preemptive rate limiting to the deployment queue
**Why**
Because according to our investigations, most of the failures from deployments that end up going to the DLQ are from rate-limiting failures.
ARC-1837
Monitoring on Splunk and SignalFx for the next week or so. We expect to see a big drop on the number of messages in the DLQ.
> ARC-1837: Apply preemptive rate limiting to the deployment queue

- db/migrations/20230310104700-add-reposync-failedcode-col.js
New column added to Reposyncstates so we can track the failed states for skipped tasks during backfill,
It is an integer instead of a string because we intend to collate the results and and changes to the string values will be a massive pain.
> ARC-1995-PART-ONE added new failed code column to the reposyncstates

- src/sync/parallel-page-fetcher.test.ts
- src/sync/parallel-page-fetcher.ts
- src/sync/pull-request.ts
- src/sync/pull-requests.test.ts
Refactoring parallel fetching logic into a common component that could be used across different entities
**Why**
1. Want to do same for builds
2. We might want to extend it to other big customers
Already behind one.
Use it to fetch builds in parallel
> None refactor parallel fetching into common component

- src/routes/api/api-router.ts
- src/routes/api/commits-from-date/recover-commits-from-dates.ts
- src/sync/sync-utils.test.ts
- src/sync/sync-utils.ts
1. Fix how to determine the commits from date
2. Add admin api to recover existing commits from date.
**Why**
Current in the ff launch darkly, the "disable" state return a large number `1654506600000` <-- which is roughly like 1970-10-08. The origin logic has flaw, it takes it to be the commitsFromDate.
The fix is to use -1 as indicator for disable state so that it is more stable.
Related to sync-main-commit-time-limit and sync-branch-commit-time-limit
ARC-1975
Unit test and local db test.
N/A
> Arc 1975 fix commits from date var all time

- db/migrations/20230309051227-add-commit-from.js
Adding `commitFrom` column in `RepoSyncStates` table. This will be used to hold the actual sync date for commits during incremental backfilling.
[Arc-1996]
> ARC-1996  Adding commitFrom column

- src/github/client/github-installation-client.ts
- src/github/client/github-queries.ts
- src/routes/api/commits-from-date/reset-failed-and-pending-deployment-cursors.ts
- src/sync/deployment.test.ts
- src/sync/deployment.ts
Use the desc in sort order when getting deployments data.
**Why**
I was planning to use FF `USE_BACKFILL_ALGORITHM_INCREMENTAL` to controller the rollout of this `desc ordering` for deployment. But I realised we are going to do percentage rollout of that ff, and I can't really tell which is which when calling the admin api to reset cursor for failed/pending deployment. 
So I'd like to have this turn on and ready now instead of later.
N/A
ARC-2033
Unit test and local
N/A
> Arc 2033 apply backfill from date on deployment  turn on desc

- src/config/feature-flags.ts
- src/routes/github/github-oauth-router.test.ts
- src/routes/github/github-oauth-router.ts
Removed FF  RENEW_GITHUB_TOKEN
**Why**
This FF is enabled in production for last one month, so cleaning up.
[ARC-2040]
[ARC-2040]: https://softwareteams.atlassian.net/browse/ARC-2040
> ARC-2040 Clean up FF RENEW_GITHUB_TOKEN

- src/sqs/backfill.test.ts
- src/sqs/backfill.ts
- src/sqs/queues.ts
- src/sync/branch.test.ts
- src/sync/build.test.ts
- src/sync/commits.test.ts
- src/sync/deployment.test.ts
- src/sync/installation.test.ts
- src/sync/installation.ts
- src/sync/pull-requests.test.ts
Replacing calling sqs in backfill with dependency injection. It all comes down to the change of signatures of
- processInstallation
- doProcessInstallation
- markCurrentTaskAsFailedAndContinue
The rest is just to make the code work with the new signature...
**Why**
To streamline the dependency path in the code and to avoid cyclic dependencies. To handle backfilling, we need more calls from SQS "package" to backfill, therefore trying to simplify it beforehand.
> ARC-1997: refactor usage of SQS in backfill to remove cyclic dependency

- src/config/metric-names.ts
- src/github/client/github-client-errors.ts
- src/github/client/github-client-interceptors.test.ts
- src/github/client/github-client-interceptors.ts
- src/github/client/github-client.nock.test.ts
- src/github/client/github-client.ts
- src/sqs/backfill-error-handler.test.ts
- src/sqs/backfill-error-handler.ts
- src/sync/branch.test.ts
- src/sync/installation.test.ts
- src/sync/installation.ts
Removing all error handling from sync/installations to SQS error handler
**Why**
To leverage SQS retries instead of relying on ad-hoc logic and make the code cleaner
> ARC-1997: move remnants of error handling from sync/installations to sqs

- src/config/logger.test.ts
- src/config/logger.ts
- src/sync/installation.ts
- simplify try/catch logic in sync/installation a little bit
- remove more UGC from logs
- log stacktraces
**Why**
- cause it simplifies code
- cause we don't want to log UGC
- cause stracktraces are helpful
> ARC-1997: minor refactoring and removing UGC from logs

- src/github/client/github-anonymous-client.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/github-oauth-router.ts
Added some temporary logs.
**Why**
To try and help us figure out why our response times our so slow for /github/configuration. Focused only on the GET in this PR as the response times are typically worse for this method (although POST ain't great). 
ARC-2052
Locally
Check out the logs once this is in prod to see if we can narrow down where the issue is coming from.
> ARC-2052 - adding temp logs to try and track down issue with gh/config response times

- static/css/jira-select-github-product.css
Set a max width on the cards so that they have a delightful space in the middle and are the same width
**Before**
**After**
> Added space between GHE and cloud cards and made them same width

- src/github/deployment.ts
- src/sqs/deployment.ts
- src/sqs/sqs.test.ts
- src/sqs/sqs.ts
- src/sqs/sqs.types.ts
- src/util/preemptive-rate-limit.test.ts
- src/util/preemptive-rate-limit.ts
Temporary change to stop Deployments SLO 
Avoid processing metrics for deployment queue when it has been rate limited.
Will have a seperate discussion on this implementation, I would prefer we tracked both rate limited and non but that will be covered in the DACI.
> avoid processing metrics for deployment queue when it has been rate limited

- views/partials/jira-configuration-table.hbs
Adding tooltip next to `Backfilled from <date>` to  tell users about the Continue backfill functionality
**Why**
To inform users about continue backfill functionality 
backfill-algorithm-incremental
[ARC-2054]
Local
[ARC-2054]: https://softwareteams.atlassian.net/browse/ARC-2054
> ARC-2054 Adding tootip

- src/github/client/github-installation-client.ts
- src/sync/build.test.ts
- src/sync/build.ts
- src/sync/pull-request.ts
- src/sync/pull-requests.test.ts
Return the PR data that could be missing if page returned contains data older than backfill from date.
**Why**
We don't want to miss any data.
I think the problem essentially lies in:
For graphQL it should be fine
For rest api, whenever we try to “filtering”, either on our consumer side (pullrequest) or from the github api side (build), it won’t work. It will miss data as the page size can be large, and bump to next page will miss data. Instead, if we “over fetch” instead of “filtering”, then it should be fine. Only drawback is user might see date earlier than their specified backfill date. But I think we can accept that for now.
use incremental flag
ARC-2084
Unit test
> Arc 2084 fix missing data on pr

- src/routes/api/installation/api-installation-delete.test.ts
- src/routes/api/installation/api-installation-delete.ts
Updated Admin API to reset the sync data on removing dev Info data from Jira
**Why**
Pollinator check should able to execute same check again and again
Incremental Backfilling
[ARC-2080]
[ARC-2065]: https://softwareteams.atlassian.net/browse/ARC-2065
[ARC-2080]: https://softwareteams.atlassian.net/browse/ARC-2080
> ARC-2080 Reset sync information on removing data from Jira

- src/github/client/github-installation-client.ts
- src/github/client/installation-token-cache.test.ts
- src/github/client/installation-token-cache.ts
- src/github/client/token-cache.test.ts
Add `gitHubAppId` as the key for token cache
**Why**
Different GHES server will have same `gitHubInstallationId`
N/A
N/A
Unit test
N/A
> NONE fix conflicts token installatin id

- static/css/jira-configuration-new.css
- views/partials/jira-configuration-table.hbs
Fixing help icon alignment issue which is next to `Backfilled from <date>`. It is moved to next line on small screens. 
Incremental Backfill
> Fixing help icon alignment issue

- src/config/feature-flags.ts
- src/routes/jira/jira-get.ts
Add statsd for tracking flags percentage rollout bucket.
**Why**
I want to know whether different flags put same jiraHost into same percentage bucket, which should be true by this doc https://docs.launchdarkly.com/home/flags/rollouts
ARC-2091
N/A
Remove and disable the flags
> ARC-2091 test flags percentage bucket

- src/config/feature-flags.ts
- src/sqs/sqs.types.ts
- src/sync/branch.test.ts
- src/sync/branches.ts
- src/sync/sync-utils.test.ts
- src/sync/sync-utils.ts
1. Remove the branch commits from date and use the main commits from date instead
**Why**
1. The branch commits from date in graphql is not reducing the amount of branches to pull. GraphQL still pull same amount of branchces (although amount of commits might be different, but continue to 2)
2. The amount of commits pulled in graphql is also limited by 50, so even if we don't have this from date, it shouldn't be a big problem. In this PR using main commits from date will put a hard limit on it still.
Unit test.
> Remove branch comites from date and use main commites from date instead

- src/routes/github/configuration/github-configuration-post.ts
- src/routes/github/configuration/github-configuration-router.test.ts
- src/routes/github/github-oauth-router.test.ts
- src/routes/github/github-oauth-router.ts
- static/js/github-configuration.js
- views/github-configuration.hbs
- Do not pass clientKey in payload, use one from installation instead
**Why**
- Because that might cause data inconsistency, as we had with one of our client. All the pages are JWT-protected and installation is guaranteed to be there, there's only one possible value.
Locally.
> NONE use installation client key

- src/config/feature-flags.ts
- src/interfaces/common.ts
- src/middleware/jira-admin-permission-middleware.test.ts
- src/middleware/jira-admin-permission-middleware.ts
- src/middleware/jira-symmetric-jwt-middleware.test.ts
- src/middleware/jira-symmetric-jwt-middleware.ts
- src/routes/github/github-router.ts
- src/routes/jira/configuration/jira-configuration-router.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-router.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-router.ts
- src/routes/jira/connect/jira-connect-router.ts
- src/routes/jira/jira-router.ts
Created new middleware to return 403 for endpoints that require Jira Admin privileges
**Why**
So we can be sure that endpoints are being called by allowed folks.
Plus the create branch JWT token can be any user so we dont want any funny business
JIRA_CHECK_ADMIN
_Jira Issues_
Complete covereage unit tests, testing on STAGE with on/off flag
Remove the user token from create branch and turn on JWT for create branch
> created new jira admin middleware and tests to return 403 when no auth

- src/config/feature-flags.ts
- src/sqs/sqs.test.ts
- src/sqs/sqs.ts
created a function to delete preemptively rate limited messages that meet the "stale" criteria, it is isolated to deployments at the moment
**Why**
CUZ THERES SO DAMN MANY
> remove stale deployment messages

- src/sync/installation.test.ts
- src/sync/installation.ts
Foring deployments task to be marked as complete
**Why**
Because deployments backfilling is broken and we only mislead the customers
> ARC-2119: force deployments status to go to complete on error during backfill

- src/routes/api/db-migrations/db-migration-down.test.ts
- src/routes/api/db-migrations/db-migration-up.test.ts
- src/routes/api/installation/api-installation-router.test.ts
- src/routes/github/configuration/github-configuration-router.test.ts
- src/routes/github/create-branch/github-create-branch-get.test.ts
- src/routes/github/github-encrypt-header-post.test.ts
- src/routes/github/github-router.test.ts
- src/routes/github/manifest/github-manifest-complete-get.test.ts
- src/routes/github/manifest/github-manifest-complete-get.ts
- src/routes/github/manifest/github-manifest-get.test.ts
- src/routes/github/repository/github-repository-get.test.ts
- src/routes/github/setup/github-setup-router.test.ts
- src/routes/jira/atlassian-connect/jira-atlassian-connect-get.test.ts
- src/routes/jira/atlassian-connect/jira-atlassian-connect-get.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-apps-get.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-apps-get.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-get.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-router.ts
- src/routes/jira/jira-get.test.ts
- src/routes/maintenance/maintenance-router.test.ts
- src/routes/session/session-get.test.ts
- static/js/jira-select-card-option.js
- test/snapshots/routes/jira/atlassian-connect/jira-atlassian-connect-get.test.ts.snap
- test/snapshots/routes/maintenance/maintenance-router.test.ts.snap
- test/utils/database-state-creator.ts
- views/jira-select-app-creation.hbs
Moving manual flow off serverUrl to connect config object.
**Why**
In the future we will need to pass more fields (e.g. API key)
manually
> ARC-2122: making manual app creation flow to use config object

- src/models/subscription.ts
- src/routes/github/create-branch/github-branches-get.test.ts
- src/routes/github/create-branch/github-branches-get.ts
The reposyncstate isn't always complete so trying to get the sub id from it using repo name and owner can be problamatic, therefore, instead we look up with just the owner since the combination will be unique.
> lookup subscription by repo owner

- src/middleware/github-webhook-middleware.ts
allow app created branchs to be processed by webhook handler
**Why**
App created branches were being treated as a bot doing things, so we skipped it :(
> HOT-103341 - process app created branches

- src/models/installation.ts
- src/routes/api/api-resync-post.test.ts
- src/routes/api/api-resync-post.ts
- src/routes/api/api-router.ts
Added additional checks to send 400 if no installations are found for passed IDs or wrong data type is passed (the latter now fails on an error but still good to be more explicit).
**Why**
To address 2 tickets that has been open in the disturbed/ops backlog for almost a year (2nd one didn't require much additional effort so it piggy backed off the first).
ARC-1424 and ARC-1425
Wrote tests for these additions (plus wrote tests for the existing code because there was none!) and tested in stg
Grab another ticket from the backlog
> ARC-1424 and ARC-1425 update api resync post

- src/transforms/transform-deployment.test.ts
- src/transforms/transform-deployment.ts
Add a check to only compare with past deployments when processing webhook and backfill (well, in backfill, this will most likely ends up as compared to nothing).
**Why**
1. This will "slightly" enhance the logic, to make it more accurate.
2. Also might "slightly" increase the efficiency by skipping comparing to base commit, especially in backfill.
ARC-2144
Unit test
1. Try filter by deployment branch as well.
3. Try ignore the commit compare if they are from different branches. 
4. See weather we can find some api to fetch "last deployments" from past date, instead of from current date. I haven't found any api successfully yet.
> ARC-2144 try to compare to future deployments only

- src/routes/github/github-oauth-router.ts
- src/routes/github/repository/github-repository-get.ts
- src/routes/jira/jira-delete.ts
- src/routes/jira/jira-get.ts
Updated missing jiraHost warnings to use the Errors enum
**Why**
To clean up the errors/warnings that were doing their own thing / for consistency.
Probs do the same with the other Errors messages.
> NONE - update missing jiraHost warnings for consistency

- src/sync/sync-utils.test.ts
- src/sync/sync-utils.ts
Skip resetting the failed code if target task is emtpy.
**Why**
We are about to turn on ff for create repo (and kick off partial sync) on repo_created webhooks.
However existing logic reset the failCode for all existing repos. We should skip that.
ARC-968
Unit test.
> Skip resetting fail code is target task is empty

- src/config/logger.test.ts
- src/github/client/github-anonymous-client.ts
- src/github/client/github-client-interceptors.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-post.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts
- src/sqs/backfill-error-handler.test.ts
- src/util/get-github-client-config.test.ts
Call a real API endpoint on GHE URL check page with some fake Auth header
**Why**
Our customers might configure their API gateway to filter out requests that doesn't look like real ones. And we don't care which status will be returned as we look at GitHub headers mostly.
> NONE: behave more similarly to production on ghe connect page

- src/models/github-server-app.test.ts
- src/models/github-server-app.ts
- src/routes/github/manifest/github-manifest-complete-get.test.ts
- src/routes/github/manifest/github-manifest-complete-get.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts
- src/util/get-github-client-config.test.ts
- src/util/get-github-client-config.ts
- On manifest complete store API key and value to Db
- Use the values in backend calls
**Why**
- Part of BTF work
Existing one.
ARC-2156
Unit tests, staging
-the first one was created as a new one; the second one was created for the same server (values were copied over)
Manual flow.
> ARC-2156: store API key on manifest complete and use it for calls

- src/transforms/transform-deployment.test.ts
- src/transforms/transform-deployment.ts
Added 'develop' to our development deployment mapping.
**Why**
To try and help resolve the [mapping issue](https://customerfeedback.atlassian.net/browse/JSF-8662) until we can find the root cause
Locally
Keep looking into the issue and chat with Solaris
> NONE: add develop to deployment dev mapping

- etc/poco/README.md
- etc/poco/bundle/main-test.json
- etc/poco/bundle/main.json
Update to our poco config
**Why**
So support can access our hash endpoint
Grant access to splunk logs for support
> NONE: give support access to api/hash endpoint

- src/models/github-server-app.test.ts
- src/models/github-server-app.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.frontend.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-get.frontend.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-get.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-get.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-post.test.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts
- src/util/api-key-validator.test.ts
- src/util/api-key-validator.ts
- static/css/jira-manual-app-creation.css
- static/js/jira-api-key-validation.js
- static/js/jira-manual-app-creation.js
- static/js/jira-server-url.js
- views/jira-manual-app-creation.hbs
- views/jira-server-url.hbs
Adding API key header name and value to the manual form
**Why**
Unblock BTF customers who are using manual way of connecting to GHE
Existing one
ARC-2157
Manuall, unit tests, including frontend ones
> ARC-2157: add fields to manual page config

- src/jira/client/jira-client.test.ts
- src/jira/client/jira-client.ts
Bumping ISSUE_KEY_API_LIMIT to 500 since DevInfo bumped on their end according to docs https://developer.atlassian.com/cloud/jira/software/rest/api-group-development-information/#api-group-development-information (and Saiyans)
> noissue: Bump issue_key limit from 100 to 500

- etc/poco/bundle/main-test.json
- etc/poco/bundle/main.json
Changed the name of the group that can make GET requests to our hash endpoint.
**Why**
Support asked if we could change the group.
Updated main tests and ran locally.
> change name after request from support

- src/github/deployment.ts
- src/transforms/transform-deployment.ts
Added some fields to the processing deployments log.
**Why**
Trying to debug a customer issue where their deployments are getting stuck in the 'in progress' state for certain environments. Logs aren't too helpful on this front currently.
Wait for logs to start showing up, get customer to run some deployments, :blob_pray:
> NONE: add state and environment to deployment log

- package.json
- src/github/branch.test.ts
- src/github/branch.ts
- src/github/deployment.test.ts
- src/github/deployment.ts
- src/github/issue.ts
- src/sqs/sqs.types.ts
- src/sync/deployment.ts
- src/transforms/transform-branch.ts
- src/transforms/transform-deployment.ts
- yarn.lock
- Upgrade `@octokit/webhooks` to the latest `@octokit/webhooks-types`
**Why**
- Existing types are outdated. E.g. see #2132
- No
- None
- Since this is a TypeScript-only change, as long as the build passes it should be safe
- nothing?
> Upgrade @octokit/webhooks-types

- static/js/jira-configuration.js
- Got rid of the ugly "Unauthorised" screen by updating the URL for **Connect a GitHub Organization**.
**Why**
-  The users were getting a blank Unauthorised screen when trying to click on the link **Connect a GitHub Organization** when the token was not available (e.g. opening in private window).
- Local
**Video**
https://github.com/atlassian/github-for-jira/assets/13076255/fe35c008-1d1c-484e-9fa7-841dd0fb43c7
> ARC-2103 - Getting unauthorised when clicking on Connect a GitHub Organization in the list of Applications for Reversed Proxy Servers 

- src/routes/github/github-oauth-router.ts
- Adding a log to know if the users are clicking on the reset link with the reset parameter `resetGithubToken`
**Why**
- Due to the lack of event tracking in the frontend, adding logs so that we can have some info.
> Adding log for `resetGithubToken`

- src/routes/github/create-branch/github-create-branch-get.test.ts
- src/routes/github/create-branch/github-create-branch-get.ts
- test/fixtures/api/graphql/repositories.json
On create-branch, show only connected repos
**Why**
Otherwise the next call will fail (see this line: https://github.com/atlassian/github-for-jira/blob/b38d0b426569351c3d6fdcaacff668eab44226d6/src/routes/github/create-branch/github-branches-get.ts#L27-L27
🤠 
disturbed
locally, tests
moar disturbed
> NONE: show only connected repos on create-branch page

- src/sync/branches.ts
- src/sync/build.ts
- src/sync/commits.ts
- src/sync/deployment.ts
- src/sync/discovery.ts
- src/sync/pull-request.ts
Making all the start/complete logging for the 5 backfill tasks the same!!!
**Why**
Makes Splunking a lot easier, and it give us way easier debugging when trying to follow the backfill.
You can now search Splunk with "Backfill task *" and you will see when each task started and completed and whether there was data. JiraHost, messageId and githubInstallationId to filter it further.
Probably a small runbook to help
> ARC-2131 - unified logging for backfill tasks

- github-for-jira.sd.yml
- src/sqs/backfill-error-handler.test.ts
- src/sqs/backfill-error-handler.ts
- src/sqs/queues.ts
- src/sync/installation.ts
Increasing number of retries for repo discovery task.
**Why**
I was digging Db and spotted a backfill that was failing on repo sync. The interesting fact: it had 2 subscriptions for the same gitHubInstallationId and they were failing on different repos, which makes me think increasing number of retries might've solved the issue (see "n" column - this is the number of repos)
```
id   |         createdAt          | numberOfSyncedRepos |       backfillSince        | syncStatus | gitHubInstallationId |   n    |       lastupdatedat
--------+----------------------------+---------------------+----------------------------+------------+----------------------+--------+----------------------------
70441 | 2021-04-26 13:06:54.071+00 |                   0 | …
```
> [EAZY kARMA] NONE: add more retries for discovery

- src/util/jira-utils.test.ts
- src/util/jira-utils.ts
Add some regex to the parsing
**Why**
Right now we parse the branch name to extra Jira issue key
Current behaviour:
abcd-123lfr1m will yield Jira issue key abcd-123
As discussed, we  want to make it as:
abcd-123lfr1m will yield NO Jira issue key
The be more specific, we should parse that Jira issue key only when it is “sort of” like whole word:
abcd-admin-6lfr1m --> ❌
abcd-admin-6-lfr1m --> ✅
abcd-admin-6 --> ✅
abcd-admin-6_ --> ✅
admin-6lfr1m --> ❌
admin-6-lfr1m
N/A
ARC-2226
Unit test
N/A
> ARC-2226 use whold word to regex parse jira issue key

- src/services/user-config-service.test.ts
- src/services/user-config-service.ts
- src/transforms/transform-deployment.test.ts
- src/transforms/transform-deployment.ts
Maintain environmentMapping order from config.yml
**Why**
- [the docs here](https://github.com/atlassian/github-for-jira/blob/3a0f6a47a9ea324f3f5def49dd77ae604eef79f2/SUPPORT.md#deployment-mapping) say "Think top-down if you ever need to override the mapping defined in GitHub for Jira" and suggest the order of environments matters for matching
- [the matching code respects ordering today](https://github.com/atlassian/github-for-jira/blob/e9f93406f398237bd2f4ed0228d70c3c6a1f5686/src/transforms/transform-deployment.ts#L194C1-L197), but the YML -> JS config parser does not, so the docs are inaccurate
- This PR fixes that
**Why - my specific use case**
- My team is trying to use this configuration:
```yml
environmentMapping:
development: ["local"]
staging: ["uat"] …
```
> Maintain environmentMapping order from config.yml

- src/sync/pull-request.ts
metrics were firing off too soon on the pull sync task to accurately compare with the other version
> None fix metrics

- github-for-jira.sd.yml
Increase the period test over 6 so its an hour instead of 50 minutes.
I considered adjusting the threshold or auto-scaling but settled on this as we are always minutes off.... I think it is worth reviewing our autoscaling as well though...next time
> increase the period test over 6 so its an hour instead of 50 minutes

- src/models/reposyncstate.test.ts
- src/models/reposyncstate.ts
- src/routes/github/create-branch/github-create-branch-get.ts
- src/routes/github/repository/github-repository-get.test.ts
- src/routes/github/repository/github-repository-get.ts
- Check only that the app knows about the org, don't look for exact repo
**Why**
- In case the repo somehow is not in RepoSyncState table (e.g. was created before we enabled create-repo event, or we missed the event whatsoever...)
Nah
HOT
tests, locally
> HOT: loose condition on RepoSyncState

- src/transforms/transform-deployment.ts
Early exit on empty param
**Why**
There're lots of error on searching dynamodb due to empty create_at. Need to mark early exit as marked those as non error to reduce noises.
This is due to github not returning proper data I suspect. 
_Jira Issues_
> Early exit to avoid marked as error entry

- src/config/feature-flags.ts
- src/sync/installation.ts
Delete the backfill message if it is found working on another worker
**Why**
1. Our backfill msg count climb. up very high
2. Alert fire off
3. msg count doesn't comes down
4. Rate limit slooooow the process
5. I think there're a lots of same backfill msg for one customer
6. Previously there's no retry on backfill message in some cases. Now we cover all cases to retry for backfill, so it is safe to delete the message it self.j
enable-dedup-backfill-sqs-msg
**Affected issues**
ARC-2253
**How has this been tested?**
N/A
Turn on ff and test.
> ARC-2253 delete backfill msg if there's another job running it

- src/config/errors.ts
- src/routes/jira/workspaces/repositories/jira-workspaces-repositories-associate.test.ts
- src/routes/jira/workspaces/repositories/jira-workspaces-repositories-associate.ts
Change to the response for associate repository
**Why**
Because the spec changes for GC are never ending?
Unit tests
If there's another spec request :tableflipp:
If not, :nothingtodo:
> NONE - update response for associate repository if no repo is found

- docker-compose.yml
Use host.docker.internal to visit yarn dev server on host network
**Why**
So that ngrok works
N/A
N/A
Locally
N/A
> Use host.docker.internal to visit yarn dev server on host network

- src/routes/github/create-branch/github-create-branch-get.ts
- src/routes/github/create-branch/github-create-branch-options-get.test.ts
- src/routes/github/create-branch/github-create-branch-options-get.ts
tested in stage
Apparently 301/302 redirects can strip header data usually **Authorization**, in the logs we have some calls getting 401s at the create-branch route, but successfully making through the create-branch-options route, which means that they were authorized for the first call but not the second, we have that backed up by some error messaging saying header data is incomplete... Hopefully this resolves that!
> None resolve 504

- db/migrations/20230717232437-add-dependabot-alert-cols.js
Adding script to add columns for dependabot alerts backfill in `RepoSyncStates` table 
**Why**
Need these columns to track the status of dependabot alerts backfill
N/A
[ISOC-3691]
Local
Dependabot alerts backfill
[ISOC-3691]: https://softwareteams.atlassian.net/browse/ISOC-3691
> ISOC-3691 add DB columns for Dependabot alerts backfill

- etc/poco/bundle/main-test.json
- etc/poco/bundle/main.json
Just removing the permissions for us to call the `deleteInstallation` endpoint manually via the cli. It's currently being called by Pollinator only, so they will continue to do so (policies are already defined in the `extras-stg` and `extras-prod` policies).
**Why**
[Spotlight](https://hello.atlassian.net/wiki/spaces/JST/pages/2101826308/Spotlight+Agile+and+Open+Toolchain+dangerous+operations+audit) project (response to last year's sev 0).
Removing operations that can be considered dangerous.
None.
ARC-1913
SPOT-197
Added a new test on `mais-test.json`
> ARC-1913 and SPOT-197: Remove admins permissions to call /deleteInstallation

- spa/src/pages/ConfigSteps/index.tsx
- spa/src/services/app-manager/index.ts
- spa/src/services/oauth-manager/index.ts
Use popup instead of new tab
**Why**
It gave user more in-context experience
https://github.com/atlassian/github-for-jira/assets/105693507/1cfa31f2-0ff5-4078-bced-407136152da4
> Use popup instead of new tab for oauth/install/and sign out

- package.json
- src/github/dependabot-alert.test.ts
- src/github/dependabot-alert.ts
- src/github/secret-scanning-alert.test.ts
- src/github/secret-scanning-alert.ts
- src/routes/github/webhook/webhook-receiver-post.test.ts
- src/routes/github/webhook/webhook-receiver-post.ts
- src/transforms/transform-secret-scanning-alert.test.ts
- src/transforms/transform-secret-scanning-alert.ts
- yarn.lock
Adding support to listen to `secret_scanning_alert` webhook event, transform the payload to Jira vulnerability and submit to Jira.
Updated `@octokit/webhooks-types` to latest version as support for secret scanning added in version `7.x`
**Why**
Part of the work to integrate GitHub with Security in Jira
https://hello.atlassian.net/wiki/spaces/CDX/pages/2673460294/RFC+GitHub+for+Jira+Security
[ISOC-3690]
Unit test
Local testing
[ISOC-3690]: https://softwareteams.atlassian.net/browse/ISOC-3690
> ISOC-3690 Secret scanning webhook handler

- db/migrations/20230731063755-add-security-permission-col.js
Adding `isSecurityPermissionsAccepted` column in `Subscriptions` table to track whether the new permissions are accepted by the GH Admin.
**Why**
We are introducing new permissions to access `dependabot_alerts` and `secret_scanning`. Once these permissions are made available in the GH app, the GH Admin will need to accept them. We will use this data to track customers whose permission requests are still pending.
We are currently considering various proposals how to push customers to accept the permissions using this data -
- Sending an email to customers to accept the new permissions.
- Implementing changes in GH4J UI to prompt customers to accept the permissions.
[ISOC-3776]
Local
Listen to …
> ISOC-3776 Add DB col in Subscriptions table

- etc/poco/bundle/main-test.json
- etc/poco/bundle/main.json
- src/routes/healthcheck/healthcheck-get-post.ts
- src/routes/healthcheck/healthcheck-router.test.ts
- src/routes/healthcheck/healthcheck-router.ts
- test/snapshots/app.test.ts.snap
- Adding a new public endpoint
**Why**
Writing a runbook how to troubleshoot connectivity issues between GHEs and the app. This endpoint is to make sure a webhook can be delivered to the app, thus ruling out network issues.
Yeah nah
> DISTURBED: add healtcheck endpoint to troubleshoot GHEs webhooks

- spa/src/pages/ConfigSteps/index.tsx
- spa/src/services/oauth-manager/index.ts
Reset auth button when auth window close regardless of flow state
**Why**
Otherwise, the auth button stays spinning, forbid user to try to auth again.
N/A
None
Local
> Reset auth button when auth window close regardless of flow state

- db/migrations/20230731063755-add-security-permission-col.js
- src/github/installation.test.ts
- src/github/installation.ts
- src/models/subscription.ts
- src/routes/github/webhook/webhook-receiver-post.test.ts
- src/routes/github/webhook/webhook-receiver-post.ts
- src/services/subscription-installation-service.ts
Implemented `installation` webhook handler to check whether security permissions has been accepted or not. If yes, then
- update`isSecurityPermissionsAccepted` column in `Subscriptions` table to true
-  Submit request to Jira to link security workspace
**Why**
We are introducing new permissions to access `dependabot_alerts` and `secret_scanning`. Once these permissions are made available in the GH app, the GH Admin will need to accept them. We will use this data to track customers whose permission requests are still pending. Backfill for security VULNS will also be triggered on permission acceptance 
[ISOC-3776]
Unit test
Local
[ISOC-3776]: …
> ISOC-3776 Installation webhook handler

- spa/src/pages/ConfigSteps/index.tsx
- After successful login, setIsLogged is set to true, which triggers the `useEffect` with `recheckValidity` and calls `getOrganization`. So, no need to call `getOrganization` again in the other `useEffect`.
> Fixing the opening of 2 tabs after logging in

- spa/src/pages/ConfigSteps/index.tsx
- spa/src/services/app-manager/index.ts
- src/github/code-scanning-alert.ts
1. Remove the cycle reference on getOrgs <--> installNewOrgs
2. Add lock to forbid open tabs multi times. 
**Why**
1. Cycle reference is always bad
2. From some reference page https://upmostly.com/tutorials/why-is-my-useeffect-hook-running-twice-in-react , it is better to model our api (in useEffect) to be idempotent (as much as we can)
Local
> None fix multi org install popup

- src/routes/jira/jira-get.test.ts
- src/routes/jira/jira-get.ts
1. Add a redirect for new 5ku experience that on empty state, go directly to the new page.
**Why**
1. One less step for the user.
enable-5ku-experience--cloud-connect
None
Unit test + local
N/A
> None redirect to new exp on empty sub

- src/config/feature-flags.ts
- src/github/push.ts
- src/routes/api/api-router.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/create-branch/github-create-branch-get.ts
- src/routes/github/create-branch/github-create-branch-options-get.ts
- src/routes/github/create-branch/github-create-branch-post.ts
- src/routes/github/manifest/github-manifest-complete-get.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-create-or-edit-get.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-delete.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-post.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-put.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-apps-get.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-delete.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-get.ts
- src/routes/jira/connect/enterprise/jira-connect-enterprise-post.ts
- src/routes/jira/connect/jira-connect-get.ts
- src/routes/jira/jira-delete.ts
- src/routes/jira/jira-get.ts
- src/routes/jira/sync/jira-sync-post.ts
- src/services/subscription-installation-service.ts
- src/sync/installation.ts
- src/util/analytics-client.test.ts
- src/util/analytics-client.ts
Sending analytics event to SQS instead of via analytics client
**Why**
Yes
in title
in ddev
> ARC-2316: start sending analytic events to SQS

- src/routes/jira/atlassian-connect/jira-atlassian-connect-get.ts
- Removing the path  redirection in atlassian-connect.json because the redirect logic is already in `jira-get`.
> 5KU - Removing the path redirection in atlassian-connect.json

- spa/src/components/Error/KnownErrors/index.tsx
- spa/src/components/Error/index.tsx
- spa/src/pages/ConfigSteps/OrgsContainer/index.tsx
- spa/src/pages/ConfigSteps/index.tsx
- spa/src/utils/modifyError.tsx
- Changed the error messages in `modifyError`, making it consistent with the ones in `OrganizationContainer`.
- Code refactoring & cleanup.
- Re-phrasing error messages.
**Why**
- Changes from Test blitz
**Screenshots**
- Action causing Invalid token error
- Action causing SSO Login error
- Action causing GitHub IP blocked error
- Action causing Not an admin error
> 5KU error messages mapping

- spa/src/analytics/types.ts
- spa/src/components/Error/KnownErrors/index.tsx
- spa/src/pages/ConfigSteps/OrgsContainer/index.tsx
- spa/src/utils/modifyError.tsx
- Added URL for list of admin orgs in non-admin errors.
- Added analytics when the link is clicked.
**Why**
- Improving UX for non-admins
- Local
**Video**
- When listing the orgs
https://github.com/atlassian/github-for-jira/assets/13076255/9299e97e-38dd-4d8a-924c-54fed6676920
- When trying to connect to an org
https://github.com/atlassian/github-for-jira/assets/13076255/dd41f6d1-57a6-41e6-ad1b-18fd186c9850
- test and merge
> ARC-2429 - Help Jira admin track down "who is the GH org owner"

- src/config/feature-flags.ts
- src/github/client/github-installation-client.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/subscription/github-subscription-delete.ts
- src/services/subscription-installation-service.ts
- src/util/github-utils.test.ts
- src/util/github-utils.ts
1. Use github installation client to check permission
**Why**
1. The user client is impacted by SSO error. Installation client should not.
use-installation-client-to-check-permission
ARC-2459
Unit test
Local
> ARC-2459 use app client to check user permission

- src/github/pull-request.ts
- src/transforms/transform-pull-request.test.ts
- src/transforms/transform-pull-request.ts
Data Depot used to only accept `APPROVED` and `UNAPPROVED` for a PR Reviewer status. They are now accepting `NEEDSWORK` as well, so we are mapping the `CHANGES_REQUESTED` Reviewers status from GitHub now too.
Data Depot API info: https://developer.atlassian.com/cloud/jira/software/rest/api-group-development-information/#api-rest-devinfo-0-10-bulk-post
GitHub ENUM for PR Review State: https://docs.github.com/en/graphql/reference/enums#pullrequestreviewstate
**Why**
Because of ATLAS-38809
[ARC-2320]
[ARC-2460]
Locally + Added a couple of UTs in this PR
- Mapping Draft PR
- Mapping PR Task Count
- Mapping Deployment triggeredBy
More info [here](https://hello.atlassian.net/wiki/spaces/OTFS/pages/277263 …
> ARC-2460: Map CHANGES_REQUESTED PR reviewer status to NEEDSWORK

- src/routes/healthcheck/healthcheck-get-post.ts
- src/routes/healthcheck/healthcheck-router.test.ts
Stop calling cryptor during healthcheck once it is ready
**Why**
To follow the docs
> NONE: stop calling cryptor in healthchecks once it is ready

- src/main.ts
- src/routes/healthcheck/healthcheck-get-post.ts
- src/util/healthcheck-stopper.test.ts
- src/util/healthcheck-stopper.ts
- src/util/workers-health-monitor.test.ts
- src/util/workers-health-monitor.ts
Temp code to try to understand what's going on with node.js processes (catching SIGTERM and SIGINT)
Temp code to mitigate the issue by forcing cluster to return 500 once more than half processes are detected to be unresponsive/dead
~No tests :coneofshame: as it is tricky (IPC) and some temp code, but I tested it quite thorougly, I SWEAR!~
**Why**
The processes are dying :sadpanda:
Not possible, startup
Locally, unit tests
splunking
> None troubleshoot unresponsive workers

- spa/src/analytics/types.ts
- spa/src/pages/Connected/index.tsx
- spa/src/pages/Connected/test.tsx
- Added events for the two help links in the success page.
**Why**
- To see if those links are actually helping out or not.
> ARC-2469 - Add analytics for the Help links in the connected page

- package.json
- src/util/workers-health-monitor.test.ts
- src/util/workers-health-monitor.ts
- yarn.lock
- Trigger generation of headump on crash
**Why**
- Still no idea what's going on
Existing one
_Jira Issues_
ddev
> NONE: generate heapdump on crash

- src/util/workers-health-monitor.ts
Fixing a bug in comms between master and worker processes
**Why**
No heapdumps were generated tonight :sigh:
Existing one
> NONE: fix master->worker comm for oom heapdump

- src/transforms/transform-code-scanning-alert.ts
- src/transforms/transform-dependabot-alert.ts
- src/transforms/transform-secret-scanning-alert.ts
This PR limits the vulnerability description to 5000 characters 
**Why**
Data depot rejects the vulnerability with description more than 5000 characters
[ISOC-4016]
[ISOC-4016]: https://softwareteams.atlassian.net/browse/ISOC-4016
> ISOC-4016 Limit vulnerability description to 5000 characters

- src/routes/github/repository/github-repository-get.test.ts
- src/routes/github/repository/github-repository-get.ts
- Added `fork:true` qualifier to allow searching for forked repos([source](https://docs.github.com/en/search-github/searching-on-github/searching-in-forks))
**Why**
- One of our customers can not find their forked repo([JST-913160](https://getsupport.atlassian.com/browse/JST-913160))
> JST-913160 - Jira/Github integration not showing forked repos

- src/sync/code-scanning-alerts.ts
- src/sync/dependabot-alerts.ts
- src/sync/secret-scanning-alerts.ts
- src/transforms/transform-code-scanning-alert.ts
- src/transforms/transform-dependabot-alert.ts
- src/transforms/transform-secret-scanning-alert.ts
This PR limits the vulnerability display name to 255 characters
**Why**
Data depot rejects the vulnerability with display name more than 255 characters
[ISOC-4017]
[ISOC-4017]: https://softwareteams.atlassian.net/browse/ISOC-4017
> ISOC-4017 Limit vulnerability display name to 255 characters

- src/github/client/github-client.types.ts
- src/github/client/github-installation-client.ts
- src/sync/code-scanning-alerts.test.ts
- src/sync/code-scanning-alerts.ts
- src/transforms/transform-code-scanning-alert.test.ts
- src/transforms/transform-code-scanning-alert.ts
This PR removes the Impact from code scanning alert description.
**Why**
To fetch impact details, we need to call [code canning alert instances ](https://docs.github.com/en/free-pro-team@latest/rest/code-scanning/code-scanning?apiVersion=2022-11-28#list-instances-of-a-code-scanning-alert)API which is not stable and list of instances could be huge. We're dropping impact from the description for now.
Affected issues
[ISOC-4040]
Unit test
[ISOC-4035]: https://softwareteams.atlassian.net/browse/ISOC-4035
[ISOC-4040]: https://softwareteams.atlassian.net/browse/ISOC-4040
> ISOC-4040 - Remove Impact from code scanning alert description

- src/routes/github/create-branch/github-create-branch-post.test.ts
- src/routes/github/create-branch/github-create-branch-post.ts
- Changing the error message for 403 errors when creating a GitHub branch
**Why**
- The previous error message was not very clear.
> ARC-2490 - Provide accurate error message for Create branch if write access permission is not granted

- src/util/handlebars/handlebar-helpers.ts
- views/partials/jira-configuration-table.hbs
Currently we are still not showing repo count as zero for the org with zero repo 
Issue:
Applying fix for the same.
Fix:
**Why**
https://softwareteams.atlassian.net/browse/ARC-316
NA
[_Jira Issues_](https://softwareteams.atlassian.net/browse/ARC-316)
Manually in local env and via unit test cases
> fix: org with zero repo count display

- src/routes/jira/atlassian-connect/jira-atlassian-connect-get.ts
- src/routes/jira/jira-get.test.ts
- src/routes/jira/jira-get.ts
- test/snapshots/routes/jira/atlassian-connect/jira-atlassian-connect-get.test.ts.snap
- test/snapshots/routes/maintenance/maintenance-router.test.ts.snap
- Changed the `res.redirect` to `AP.navigator.go` in `jira-get`.
- Updated the `atlassian-connect.json` to pass in `from` as query parameters in `/spa` route.
**Why**
- Due to a [recent change ](https://github.com/atlassian/github-for-jira/pull/2392), `/spa` routes now need JWT authentication, so doing a normal `res.redirect` is throwing a 401 error from the server.
- Staging
> Fixing the 500 error when going to `/spa` when no orgs

- src/transforms/push.ts
We have a bunch of push DLQ error because the author on the commit object is undefined :sad: 
This is just broken up a bit to cope with that scenario, i did it for message as well since it was probably the commits object missing and just complaining about author first.
> Defaulting author value

- src/transforms/push.ts
we are getting a lot!! of `Cannot read property 'slice' of undefined` so this is trying to handle files being undefined
> default to empty array when files is undefined

- views/jira-configuration.hbs
- views/partials/jira-configuration-table.hbs
Fixing RepoView link for GHEs. Also noticed that csrfToken suffered same, fixed it as well (although looks like it wasn't used :susp: )
**Why**
Cause it is broken
Existing one
locally
> NONE: fix repoview link for ghe

- github-for-jira.sd.yml
- Updating the node version of lambda to 18.
**Why**
- Cause today is the deadline
- Nothing, but this shouldn't break anything because this lambda is used for the auto deployment in the pipelines.
- Merge and check if the auto deployment is still running in the pipelines.
> UA-9615 - Micros is deprecating Node.js 14.x runtime for lambda - github-for-jira

- test/e2e/utils/jira.ts
- Changing the locator on the e2e test.
**Why**
Now that we've removed the 5KU FF, the very first screen the user will get to is the Get Started page from the 5KU react. So the previous locator defined in the e2e test won't work now.
- In e2e tests.
- Just merge and see everything green again.
> Fixing the broken e2e tests

- src/config/feature-flags.ts
- src/sync/pull-request.ts
- src/transforms/transform-pull-request.test.ts
- src/transforms/transform-pull-request.ts
- Removing FF for Draft PR.
**Why**
- Cause its no longer needed.
- Test cases
> Removing FF for Draft PR

- spa/src/pages/ConfigSteps/test.tsx
Just fix a test warning
**Why**
Seems `render` and `userEvent` already contains a `act()` inside. Wrapping it outside ( and have an react.setState update during the event) will cause the warning.
Just await on the userEvent.click() seems does the trick.
ARC-2592
> ARC-2592 fix test warn

- src/routes/github/configuration/github-configuration-app-installs-get.test.ts
- src/routes/github/configuration/github-configuration-app-installs-get.ts
- src/routes/github/github-5ku-router.test.ts
- src/routes/github/github-5ku-router.ts
- src/routes/github/setup/github-setup-router.test.ts
- static/js/github-setup.js
- views/partials/github-setup-form.hbs
- Added query parameter `state` for installation routes coming from our side.
- Updated test cases.
**Why**
- So that the users do not see any error screen when installing the app from Github side.
**Video**  
https://github.com/atlassian/github-for-jira/assets/13076255/fe835926-34fa-4738-a9a1-fe587c9129ff
- Locally
- Test cases
> ARC-2938 - Support use case starts from GitHub installation

- .github/workflows/dummy-deployment.yml
Add a dummy deployment hook for github action
**Why**
1. So that during BB micros deploy, BB can do `POST https://api.github.com/repos/atlassian/github-for-jira/actions/workflows/75366764/dispatches` with a branch name and env name to trigger this action
2. And then the action will send deployment data via webhook to gh4j
3. Our gh4j will send info to DD in our jira site
4. All deployments will be linked to the correct jira issue
5. Should works for deployment on all branch, but not on sha_commits. (Sha commits is not supported in github rest api for trigger action)
N/A
ARC-2592
Postman
Update BB pipelines to trigger a curl post to above endpoints.
> None trigger action for dummy deployment

- src/routes/github/create-branch/github-create-branch-get.ts
- src/routes/github/create-branch/github-create-branch-options-get.ts
- Changing the url from `github-select-product-page` to `spa-index-page`
**Why**
- Cause it was pointing to the old flow
- Locally
> Fixing the URL when connecting orgs from Create branch option

- spa/src/services/oauth-manager/index.ts
- spa/src/services/oauth-manager/test.ts
1. Use arrays to store the oauth state to allow multiple table for oauth dance.
**Why**
1. We receive some [errors](https://atlassian-2y.sentry.io/issues/4459820321/?project=4505604384292864&query=&referrer=issue-stream&sort=date&statsPeriod=24h&stream_index=0) regarding the the state is not matching. I couldn't figure out why, but suspect it is because user open multi tab for auth (like press the auth button multi times). Because currently we only store the state of last time, hence user may receive error on first tab. 
N/A
N/A
Unit test.
Monitor errors.
> NONE try to relax to allow multiple tabs to auth

- .eslintrc.json
- src/config/logger.ts
- src/github/client/github-client.types.ts
- src/middleware/frontend-log-middleware.ts
- src/middleware/github-server-app-middleware.test.ts
- src/middleware/github-server-app-middleware.ts
- src/middleware/jira-symmetric-jwt-middleware.ts
- src/rest/middleware/jira-admin/jira-admin-check.ts
- src/rest/middleware/jwt/jwt-handler.ts
- src/rest/routes/github-orgs/index.ts
- src/rest/routes/index.d.ts
- src/routes/github/github-router.test.ts
- src/routes/jira/connect/enterprise/app/jira-connect-enterprise-app-router.test.ts
- src/sqs/sqs.ts
- src/sync/transforms/branch.ts
- src/transforms/transform-pull-request.ts
- src/util/curl/curl-utils.test.ts
- src/util/filtering-http-logs-stream.ts
- src/util/handlebars/handlebar-helpers.ts
Lint
**Why**
Lint
None
NONE
Tests
Lint
> NONE: Re-enable eslint rules

- src/config/feature-flags.ts
- src/routes/github/configuration/github-configuration-get.ts
- src/routes/github/subscription/github-subscription-delete.ts
- src/services/subscription-installation-service.ts
- src/util/github-utils.test.ts
- src/util/github-utils.ts
Remove use-installation-client-to-check-permission
**Why**
No need of ff anymore. 100% rolled out
Remove use-installation-client-to-check-permission
None
Unit test
N/A
> Remove use-installation-client-to-check-permission

- etc/poco/bundle/extras-stg-test.json
- etc/poco/bundle/extras-stg.json
Add poco to allow polli test to call api for audit log.
**Why**
To allow polli test
N/A
[ARC-2643]
Unit test.
N/A
> Arc 2643 allow extra polli test

- src/jira/client/jira-client-audit-log-helper.test.ts
- src/jira/client/jira-client-audit-log-helper.ts
prepend entityId with repofull name for uniqueness
**Why**
Coz one subscription can have multiple repo with same pr number or branch name
[ARC-2643]
Unit test
> ARC-2643 prepend entityId with repofull name for uniqueness

- src/github/workflow.test.ts
- src/github/workflow.ts
- src/jira/client/jira-client-audit-log-helper.test.ts
- src/jira/client/jira-client-audit-log-helper.ts
- src/jira/client/jira-client.ts
- src/sync/build.test.ts
- src/sync/installation.ts
1. Add repofull name to audit log of workflow
2. Use state instead of entity action.
**Why**
Polli test needs them.
[arc-2643]
unit test
> ARC-2643 use repo full name in workflow

- src/github/workflow.test.ts
- src/interfaces/github.ts
- src/jira/client/jira-client-audit-log-helper.ts
- src/jira/client/jira-client.ts
- src/sync/build.test.ts
- src/sync/build.ts
- src/transforms/transform-workflow.ts
Use workflow id instead of workflow_run.id as the pipelineId
**Why**
Because `workflow_id` is the pipeline id, `workflow_run.id` is just the id of each run, kind of equivelant of what we use as the "run_number" from the webhook payload.
And this is why both links link to same page
[ARC-2643]
unit and stg
> Arc 2643 workflow log

- src/config/feature-flags.ts
- src/config/metric-names.ts
- src/jira/client/axios.test.ts
- src/jira/client/axios.ts
- src/sqs/backfill-error-handler.test.ts
- src/sqs/backfill-error-handler.ts
- src/sqs/error-handlers.test.ts
- src/sqs/error-handlers.ts
- src/sqs/sqs.ts
- src/sqs/sqs.types.ts
Use the retry-after header in jira api to retry message. 
**Why**
As jira implemented the retry-after info
https://developer.atlassian.com/cloud/jira/software/rest/api-group-development-information/#api-rest-devinfo-0-10-bulk-post
use-ratelimit-on-jira-client
ARC-2713
Unit test
> Arc 2713 use retry after header in jira client

- CONTRIBUTING.md
Fix a doc for supporting local dev
**Why**
New SPA page use a new callback url
> Fix doc to use new callback url for spa

- github-for-jira.sd.yml
Bump our RDS instance from the default t2.small to one size up t2.medium.
we have reached the limits of t2.small with the addition of a new Pollinator, it can cope when things go well but starts pushing the limits when failures start occuring
> updgrade stg rds instance

- src/config/feature-flags.ts
- src/transforms/push.test.ts
- src/transforms/push.ts
- src/util/jira-issue-check-redis-util.ts
Skip processing commit msg when issue not found on jira
**Why**
To avoid lots of 429 on both github and jira api when processing msg and ends up in dlq.
skip-process-queue-when-issue-not-exists
None
Unit test
Turn on FF for a particular customer.
> None check jira issue before commit push

- src/config/feature-flags.ts
- src/transforms/push.test.ts
- src/transforms/push.ts
- src/util/jira-issue-check-redis-util.test.ts
- src/util/jira-issue-check-redis-util.ts
1. Reduce times to called to jira issue status
2. Add redis cache timeout ff
**Why**
skip-process-queue-when-issue-not-exists-timeout
None
Unit test.
> reduce calls to jira issue status

- .github/workflows/on-push.yml
- .yarnrc
- Dockerfile
- Dockerfile.prod
- package.json
- spa/package.json
add dlq-service during BB pipeline
**Why**
1. The public yarn.lock doesn't contains the optional deps
2. But during BB pipeline, it will install the optional, but now the fronzenfile is wrong, so will error.
https://bitbucket.org/atlassian/github-for-jira-deployment/pipelines/results/8402
> add dlq-service during BB pipeline

- src/config/feature-flags.ts
- src/github/client/github-client-errors.ts
- src/github/client/github-client-interceptors.test.ts
- src/github/client/github-client-interceptors.ts
- src/sqs/push.ts
- src/transforms/push.test.ts
- src/transforms/push.ts
Add code to skip the commit if error is "422 not found by sha" when on the last try. Only apply for push queue.
**Why**
I think on the last re-try, if we still couldn't find the commit by sha from either github.com or ghes, it could means either the server is wrong or the commit is gone. We should skip the message instead of putting them in DLQ.
skip-commit-if-sha-not-found-on-last-try
[ARC-2759]
Unit test.
[ARC-2759]: https://softwareteams.atlassian.net/browse/ARC-2759
> ARC-2759 skip the error "Commit not found by sha..." if on last try

- .env.development.local.example
- CONTRIBUTING.md
Update CONTRIBUTING.md and .env.development.local.example to include APP_URL
**Why**
Set up instructions do not work in current state. See slack thread here: https://atlassian.slack.com/archives/C0496DT7MQV/p1701754004930849
N/A
ARC-2784 
- Checked .md on GitHub
- Updated .env file with @sopliu and fixed her issue
> ARC-2784 Update CONTRIBUTING.md and .env.development.local.example to include APP_URL

- etc/poco/bundle/extras-stg-test.json
- etc/poco/bundle/extras-stg.json
- Updating UUID for Config State API pollinator test
**Why**
- Config state for Pollinator test was replaced by a new one.
- Merge and check if the polli test is green now.
> Updating UUID for Config State API pollinator test

- src/rest/rest-router.ts
What's in this PR?
Use existing GitHubAppMiddleware to enforce the security check
Why
We are starting to expose the GHES function to rest-router, we need some security check on it.
> Enforce security check on GHES app

- docker-compose.yml
- We were using a pretty old version of ngrok container in Docker.
- So updating it to the new latest ngrok container.
**Why**
Cause ngrok is removing the free support for old versions of ngrok (older than 3.4).
> Update ngrok in Github for Jira

- src/config/feature-flags.ts
- src/transforms/transform-deployment.test.ts
- src/transforms/transform-deployment.ts
Add a ff to skip sending commits association
**Why**
To send less data for ease on DD 500 error.
And this data is not being used anyway.
https://atlassian.slack.com/archives/C01PERFAUHZ/p1703129216457669
skip-sending-commit-association
[ARC-2803]
Unit test.
Fully rollout the FF.
[ARC-2803]: https://softwareteams.atlassian.net/browse/ARC-2803
> ARC-2803 skip sending commit association for now

- README.md
The Github for Jira repo has been moved to a private repository. Add an update to the README and deprecate repo.
> GUA-126 Deprecate Github for Jira repo 

- docs/ip-allowlist.md
github-for-jira has moved to us-east-1 so the documentation should reflect the new outgoing ip range of 104.192.142.240/28
> Update ip-allowlist.md CIDR range recommendation
